import {PersistentRuntimeError,sha256Digest,type ModelGatewayTicketClaims} from '@lumiclaw/domain';
import {createHmac,timingSafeEqual} from 'node:crypto';

export class ModelGatewayTicketSigner{
  readonly #secret:Buffer;
  public constructor(secret:Buffer|string){this.#secret=Buffer.isBuffer(secret)?Buffer.from(secret):Buffer.from(secret,'utf8');if(this.#secret.length<32)throw new PersistentRuntimeError('RUNTIME_NOT_CONFIGURED','MODEL_TICKET_SIGNING_SECRET_TOO_SHORT');}
  public issue(claims:ModelGatewayTicketClaims):{ticket:string;ticketDigest:string}{const payload=Buffer.from(JSON.stringify(claims),'utf8').toString('base64url');const signature=this.sign(payload);const ticket=`v1.${payload}.${signature}`;return {ticket,ticketDigest:sha256Digest(ticket)};}
  public verify(ticket:string):{claims:ModelGatewayTicketClaims;ticketDigest:string}{const parts=ticket.split('.');if(parts.length!==3||parts[0]!=='v1'||parts[1]===undefined||parts[2]===undefined)throw new PersistentRuntimeError('MODEL_TICKET_REPLAYED','MODEL_TICKET_INVALID');const expected=Buffer.from(this.sign(parts[1]),'base64url');const actual=Buffer.from(parts[2],'base64url');if(actual.length!==expected.length||!timingSafeEqual(actual,expected))throw new PersistentRuntimeError('MODEL_TICKET_REPLAYED','MODEL_TICKET_SIGNATURE_INVALID');let value:unknown;try{value=JSON.parse(Buffer.from(parts[1],'base64url').toString('utf8'));}catch{throw new PersistentRuntimeError('MODEL_TICKET_REPLAYED','MODEL_TICKET_PAYLOAD_INVALID');}if(!ticketClaims(value))throw new PersistentRuntimeError('MODEL_TICKET_REPLAYED','MODEL_TICKET_PAYLOAD_INVALID');return {claims:value,ticketDigest:sha256Digest(ticket)};}
  public fingerprint():string{return createHmac('sha256',this.#secret).update('lumiclaw-model-ticket-signing-key-fingerprint-v1').digest('hex').slice(0,16);}
  private sign(payload:string):string{return createHmac('sha256',this.#secret).update(`v1.${payload}`).digest('base64url');}
}

function ticketClaims(value:unknown):value is ModelGatewayTicketClaims{if(value===null||typeof value!=='object'||Array.isArray(value))return false;const record=value as Record<string,unknown>;const keys=['attemptId','attemptNumber','expiresAt','inputDigest','jobId','leaseTokenDigest','model','nonce','outputSchema','ownerId','phase','policyDigest','requestDigest','runId','runtimeActorId','runtimeTaskId','schemaVersion','taskId','workerIdDigest'];if(Object.keys(record).sort().join(',')!==keys.sort().join(','))return false;return record.schemaVersion===1&&Object.values(record).every((item)=>item!==undefined)&&typeof record.ownerId==='string'&&typeof record.runId==='string'&&typeof record.jobId==='string'&&typeof record.taskId==='string'&&typeof record.attemptId==='string'&&Number.isSafeInteger(record.attemptNumber)&&typeof record.runtimeTaskId==='string'&&record.runtimeTaskId.length>0&&typeof record.runtimeActorId==='string'&&record.runtimeActorId.length>0&&digest(record.workerIdDigest)&&digest(record.leaseTokenDigest)&&['ORCHESTRATE','CLAIM','PLAN','PRODUCE','AUDIT'].includes(String(record.phase))&&['deepseek-v4-flash','deepseek-v4-pro'].includes(String(record.model))&&digest(record.policyDigest)&&digest(record.inputDigest)&&digest(record.requestDigest)&&typeof record.outputSchema==='string'&&typeof record.expiresAt==='string'&&typeof record.nonce==='string';}
function digest(value:unknown):value is string{return typeof value==='string'&&/^[a-f0-9]{64}$/u.test(value);}
