import {createDemoCampaignDocument, sha256Digest} from '@lumiclaw/domain';
import {createShadowMission} from '@lumiclaw/governed-shadow';
import {describe, expect, it} from 'vitest';
import {AgentTeamsV120ShadowAdapter, InMemoryAgentTeamsV120Transport} from './shadow-adapter.js';

const campaign = createDemoCampaignDocument(); const now = () => new Date('2026-08-04T02:00:00Z');
const mission = () => createShadowMission({campaign, campaignVersion: 1, campaignDigest: campaign.missionContract.sourceDigest, now: now()});
const members = (value = mission()) => value.roleContexts.map((context) => ({name: context.roleId, roleIdentityId: context.identityId, runtime: 'copaw' as const, state: 'READY' as const}));

describe('AgentTeams v1.2.0 SHADOW Runtime Adapter', () => {
  it('creates one Project, six-member DAG and observes runtime state', async () => { const value = mission(); const result = await new AgentTeamsV120ShadowAdapter(new InMemoryAgentTeamsV120Transport(members(value)), now).dispatch(value); expect(result.accepted).toBe(true); expect(result.runtime).toMatchObject({state: 'ready'}); expect(Object.keys(result.runtime!.taskStates)).toHaveLength(6); });
  it('fails closed for version, member count and identity collision', async () => { const value = mission(); const bad = members(value).slice(0, 5); bad[1]!.roleIdentityId = bad[0]!.roleIdentityId; const result = await new AgentTeamsV120ShadowAdapter(new InMemoryAgentTeamsV120Transport(bad, `sha256:${'b'.repeat(64)}`, 'v1.1.0'), now).dispatch(value); expect(result.accepted).toBe(false); expect(result.codes).toEqual(expect.arrayContaining(['RUNTIME_VERSION_MISMATCH', 'MEMBER_COUNT_NOT_EXACTLY_SIX', 'MEMBER_IDENTITY_COLLISION'])); });
  it('enforces ACK dependencies and quarantines mismatched Submit', async () => { const value = mission(); const adapter = new AgentTeamsV120ShadowAdapter(new InMemoryAgentTeamsV120Transport(members(value)), now); await adapter.dispatch(value); const planner = value.tasks.find((task) => task.roleId === 'campaign-planner')!; expect((await adapter.acknowledge(value, planner.id, planner.roleId)).codes).toContain('TASK_PREREQUISITE_NOT_ACCEPTED'); const evidence = value.tasks.find((task) => task.roleId === 'evidence-claim-steward')!; const payload = {frozen: true}; const result = await adapter.importSubmission(value, {schemaVersion: 1, missionId: value.id, taskId: evidence.id, roleId: evidence.roleId, roleIdentityId: evidence.roleIdentityId, inputDigest: '0'.repeat(64), skillLockDigest: evidence.skillLockDigest, outputSchema: evidence.outputSchema, outputSchemaVersion: 1, payload, outputDigest: sha256Digest(payload)}); expect(result.accepted).toBe(false); expect(result.codes).toEqual(expect.arrayContaining(['INPUT_DIGEST_MISMATCH', 'OUTPUT_PAYLOAD_SCHEMA_INVALID'])); });
  it('accepts only payloads matching the task output schema and rejects any later submit', async () => { const value = mission(); const adapter = new AgentTeamsV120ShadowAdapter(new InMemoryAgentTeamsV120Transport(members(value)), now); await adapter.dispatch(value); const evidence = value.tasks.find((task) => task.roleId === 'evidence-claim-steward')!; const acknowledged = await adapter.acknowledge(value, evidence.id, evidence.roleId); const payload = {frozen: true, claimEvidenceDigest: 'c'.repeat(64)}; const submission = {schemaVersion: 1 as const, missionId: value.id, taskId: evidence.id, roleId: evidence.roleId, roleIdentityId: evidence.roleIdentityId, inputDigest: evidence.inputDigest, skillLockDigest: evidence.skillLockDigest, outputSchema: evidence.outputSchema, outputSchemaVersion: 1 as const, payload, outputDigest: sha256Digest(payload)}; const accepted = await adapter.importSubmission(acknowledged.mission, submission); expect(accepted.accepted).toBe(true); expect(accepted.mission.tasks.find((task) => task.id === evidence.id)?.state).toBe('ACCEPTED'); const duplicate = await adapter.importSubmission(accepted.mission, submission); expect(duplicate.accepted).toBe(false); expect(duplicate.codes).toContain('DUPLICATE_ACCEPTED_SUBMISSION'); });
  it('recovers unavailable runtime as unknown and never invents success', async () => { const value = mission(); const transport = new InMemoryAgentTeamsV120Transport(members(value)); const result = await new AgentTeamsV120ShadowAdapter(transport, now).recover(value); expect(result.accepted).toBe(false); expect(result.codes).toContain('RUNTIME_RECONCILE_UNAVAILABLE'); expect(result.mission.recovery.status).toBe('UNKNOWN'); expect(result.mission.state).toBe('UNKNOWN_RECOVERY'); });
});
