import {
  ArtifactContractError,GoalPlanContractError,PersistentRuntimeError,createArtifactAuditDecision,createArtifactRevision,parseArtifactAuditFindings,parseProducerSubmission,parseRuntimeOutput,quarantineProducerSubmission,sha256Digest,stableContractId,
  type ArtifactPublishRepository,type ArtifactRevisionV3,type AuditResult,type GoalPlanRepository,type MissionExecutionBundle,type MissionIntentBundle,type PlannerSubmission,type RuntimeLease,type RuntimeMaterializationCandidate,type RuntimeSubmissionEnvelope
} from '@lumiclaw/domain';
import {importPlannerSubmissionV2} from '@lumiclaw/mission-compiler';

export type RuntimeMaterializationPlan={acceptedOutputRef:string;candidates:RuntimeMaterializationCandidate[]};

export class RuntimeOutputAuthority {
  public constructor(private readonly goals:GoalPlanRepository,private readonly artifacts:ArtifactPublishRepository){}

  public async plan(lease:RuntimeLease,envelope:RuntimeSubmissionEnvelope):Promise<RuntimeMaterializationPlan>{
    const bundle=await this.goals.getBundle(lease.run.ownerId,lease.run.bundleId);if(bundle===undefined||bundle.canonicalDigest!==lease.run.bundleDigest)throw new PersistentRuntimeError('SUBMISSION_INPUT_MISMATCH','BUNDLE_AUTHORITY_MISMATCH');
    try{const payload=parseRuntimeOutput(lease.job.contract,envelope.payload);const parsedEnvelope={...envelope,payload};if(lease.job.kind==='ORCHESTRATE'||lease.job.kind==='FREEZE_CLAIMS')return protocolPlan(lease,payload,lease.job.kind==='ORCHESTRATE'?'orchestration':'claim-freeze');if(lease.job.kind==='PLAN_CONTENT')return await this.planContent(bundle,lease,parsedEnvelope);if(lease.job.kind==='PRODUCE_CONTENT')return await this.planProducer(bundle,lease,parsedEnvelope);return await this.planAudits(bundle,lease,parsedEnvelope);}catch(error){if(error instanceof PersistentRuntimeError)throw error;if(error instanceof GoalPlanContractError)throw new PersistentRuntimeError('SUBMISSION_INPUT_MISMATCH',error.code);if(error instanceof ArtifactContractError)throw new PersistentRuntimeError(error.code==='ARTIFACT_SCHEMA_INVALID'?'SUBMISSION_SCHEMA_INVALID':'SUBMISSION_INPUT_MISMATCH',error.code);throw error;}
  }

  private async planContent(bundle:MissionIntentBundle|MissionExecutionBundle,lease:RuntimeLease,envelope:RuntimeSubmissionEnvelope):Promise<RuntimeMaterializationPlan>{
    const submission=plannerSubmission(envelope.payload);if(submission.evidenceMaturity!=='AGENTTEAMS_RUNTIME')throw new PersistentRuntimeError('SUBMISSION_INPUT_MISMATCH','PLANNER_RUNTIME_EVIDENCE_REQUIRED');const intent=bundle.kind==='MISSION_INTENT'?bundle:await this.requireIntent(lease.run.ownerId,bundle);const previous=await this.goals.getPlan(lease.run.ownerId,stableContractId('plan',{missionIntentId:intent.missionIntentId}));const candidate=importPlannerSubmissionV2(intent,submission,envelope.submittedAt,previous);
    if(bundle.kind==='MISSION_EXECUTION'){if(previous===undefined||previous.state!=='APPROVED'||previous.planId!==bundle.approvedPlanId||previous.canonicalDigest!==bundle.approvedPlanDigest||sha256Digest({slots:candidate.slots,currentBrief:candidate.currentBrief,sourceBindings:candidate.sourceBindings})!==sha256Digest({slots:previous.slots,currentBrief:previous.currentBrief,sourceBindings:previous.sourceBindings}))throw new PersistentRuntimeError('SUBMISSION_INPUT_MISMATCH','APPROVED_PLAN_GATE_MISMATCH');return candidatePlan('approved-plan-gate',previous.planId,previous.canonicalDigest,{schemaVersion:1,approvedPlanId:previous.planId,approvedPlanDigest:previous.canonicalDigest});}
    const item:RuntimeMaterializationCandidate={kind:'CONTENT_PLAN',authorityId:candidate.planId,canonicalDigest:candidate.canonicalDigest,expectedHeadDigest:previous?.canonicalDigest??null,payload:candidate};return {acceptedOutputRef:`urn:lumiclaw:content-plan:${candidate.planId}:${candidate.canonicalDigest}`,candidates:[item]};
  }

  private async planProducer(bundle:MissionIntentBundle|MissionExecutionBundle,lease:RuntimeLease,envelope:RuntimeSubmissionEnvelope):Promise<RuntimeMaterializationPlan>{
    if(bundle.kind!=='MISSION_EXECUTION')throw new PersistentRuntimeError('SUBMISSION_INPUT_MISMATCH','EXECUTION_BUNDLE_REQUIRED');const submissions=payloadArray(envelope.payload,'submissions').map(parseProducerSubmission);if(submissions.length===0||submissions.some((item)=>item.evidenceMaturity!=='AGENTTEAMS_RUNTIME'||item.agentTeamsExecuted!==true||item.producerRole!==lease.job.roleId||item.producerIdentityId!==envelope.runtimeActorId))throw new PersistentRuntimeError('SUBMISSION_INPUT_MISMATCH','PRODUCER_RUNTIME_AUTHORITY_MISMATCH');const expectedUnits=bundle.activationUnits.filter((unit)=>unit.producerRole===lease.job.roleId).map((unit)=>unit.activationUnitId).sort();if(sha256Digest(submissions.map((item)=>item.activationUnitId).sort())!==sha256Digest(expectedUnits))throw new PersistentRuntimeError('SUBMISSION_INPUT_MISMATCH','ACTIVATION_UNIT_COVERAGE_MISMATCH');
    const workspace=await this.artifacts.getWorkspace(lease.run.ownerId);const candidates:RuntimeMaterializationCandidate[]=[];for(const submission of submissions){const quarantine=quarantineProducerSubmission(submission,bundle,envelope.submittedAt);if(quarantine!==null)throw new PersistentRuntimeError(quarantine.reasonCode==='ARTIFACT_SCHEMA_INVALID'?'SUBMISSION_SCHEMA_INVALID':'SUBMISSION_INPUT_MISMATCH',quarantine.reasonCode);const head=latest(workspace.revisions,submission.activationUnitId);const revision=createArtifactRevision({ownerId:lease.run.ownerId,submission,bundle,revision:(head?.revision??0)+1,parentRevisionId:head?.id??null,createdAt:envelope.submittedAt});candidates.push({kind:'ARTIFACT_REVISION',authorityId:revision.id,canonicalDigest:revision.canonicalDigest,expectedHeadDigest:head?.canonicalDigest??null,payload:revision});}
    const refDigest=sha256Digest(candidates.map((item)=>({id:item.authorityId,digest:item.canonicalDigest})).sort((left,right)=>left.id.localeCompare(right.id)));return {acceptedOutputRef:`urn:lumiclaw:artifact-revisions:${refDigest}`,candidates};
  }

  private async planAudits(bundle:MissionIntentBundle|MissionExecutionBundle,lease:RuntimeLease,envelope:RuntimeSubmissionEnvelope):Promise<RuntimeMaterializationPlan>{
    if(bundle.kind!=='MISSION_EXECUTION'||lease.job.roleId!=='independent-auditor')throw new PersistentRuntimeError('SUBMISSION_INPUT_MISMATCH','INDEPENDENT_AUDITOR_REQUIRED');const raw=payloadArray(envelope.payload,'audits');const workspace=await this.artifacts.getWorkspace(lease.run.ownerId);const heads=bundle.activationUnits.map((unit)=>latest(workspace.revisions,unit.activationUnitId)).filter((value):value is ArtifactRevisionV3=>value!==undefined);if(heads.length!==bundle.activationUnits.length||raw.length!==heads.length)throw new PersistentRuntimeError('SUBMISSION_INPUT_MISMATCH','AUDIT_COVERAGE_MISMATCH');const candidates:RuntimeMaterializationCandidate[]=[];
    for(const value of raw){if(!exactRecord(value,['artifactRevisionId','auditorIdentityId','createdAt','evidenceBindings','findings','result'])||typeof value.artifactRevisionId!=='string'||value.auditorIdentityId!==envelope.runtimeActorId||typeof value.createdAt!=='string'||!['PASS','FAIL','ESCALATE'].includes(String(value.result))||!Array.isArray(value.evidenceBindings)||value.evidenceBindings.some((item)=>typeof item!=='string'))throw new PersistentRuntimeError('SUBMISSION_SCHEMA_INVALID','AUDIT_SUBMISSION_SCHEMA_INVALID');const revision=heads.find((item)=>item.id===value.artifactRevisionId);if(revision===undefined)throw new PersistentRuntimeError('SUBMISSION_INPUT_MISMATCH','AUDIT_REVISION_MISMATCH');const audit=createArtifactAuditDecision({ownerId:lease.run.ownerId,revision,auditorIdentityId:value.auditorIdentityId,result:value.result as AuditResult,findings:parseArtifactAuditFindings(value.findings),evidenceBindings:value.evidenceBindings as string[],createdAt:value.createdAt});candidates.push({kind:'ARTIFACT_AUDIT',authorityId:audit.id,canonicalDigest:audit.canonicalDigest,expectedRevisionDigest:revision.canonicalDigest,payload:audit});}
    const refDigest=sha256Digest(candidates.map((item)=>({id:item.authorityId,digest:item.canonicalDigest})).sort((left,right)=>left.id.localeCompare(right.id)));return {acceptedOutputRef:`urn:lumiclaw:artifact-audits:${refDigest}`,candidates};
  }

  private async requireIntent(ownerId:string,bundle:MissionExecutionBundle):Promise<MissionIntentBundle>{const intent=await this.goals.getBundle(ownerId,bundle.parentBundleId);if(intent?.kind!=='MISSION_INTENT'||intent.canonicalDigest!==bundle.parentBundleDigest)throw new PersistentRuntimeError('SUBMISSION_INPUT_MISMATCH','PARENT_INTENT_MISMATCH');return intent;}
}

function protocolPlan(lease:RuntimeLease,value:unknown,kind:'orchestration'|'claim-freeze'):RuntimeMaterializationPlan{const keys=kind==='orchestration'?['agentTeamsExecuted','completed','inputDigest','schemaVersion','taskId']:['agentTeamsExecuted','frozenBindingDigest','inputDigest','schemaVersion','taskId'];if(!exactRecord(value,keys)||value.schemaVersion!==1||value.taskId!==lease.job.taskContractId||value.inputDigest!==lease.job.contract.inputDigest||value.agentTeamsExecuted!==true||(kind==='orchestration'&&value.completed!==true)||(kind==='claim-freeze'&&!isDigest(value.frozenBindingDigest)))throw new PersistentRuntimeError('SUBMISSION_SCHEMA_INVALID',`${kind.toUpperCase()}_RECEIPT_INVALID`);const canonicalDigest=sha256Digest(value);return candidatePlan(kind,`${lease.job.taskContractId}:${canonicalDigest}`,canonicalDigest,value);}
function candidatePlan(label:string,authorityId:string,canonicalDigest:string,payload:Record<string,unknown>):RuntimeMaterializationPlan{return {acceptedOutputRef:`urn:lumiclaw:${label}:${authorityId}:${canonicalDigest}`,candidates:[{kind:'PROTOCOL',authorityId,canonicalDigest,payload}]};}
function plannerSubmission(value:unknown):PlannerSubmission{if(!exactRecord(value,['currentBrief','evidenceMaturity','inputDigest','intentBundleDigest','intentBundleId','missionIntentId','outputSchema','outputSchemaDigest','roleId','schemaVersion','skillLockDigest','slots','sourceBindings','taskId']))throw new PersistentRuntimeError('SUBMISSION_SCHEMA_INVALID','PLANNER_SUBMISSION_SCHEMA_INVALID');return value as PlannerSubmission;}
function payloadArray(value:unknown,key:'submissions'|'audits'):unknown[]{if(!exactRecord(value,[key])||!Array.isArray(value[key]))throw new PersistentRuntimeError('SUBMISSION_SCHEMA_INVALID',`${key.toUpperCase()}_SCHEMA_INVALID`);return value[key];}
function latest(values:ArtifactRevisionV3[],activationUnitId:string):ArtifactRevisionV3|undefined{return values.filter((item)=>item.activationUnitId===activationUnitId).sort((left,right)=>right.revision-left.revision)[0];}
function exactRecord(value:unknown,keys:string[]):value is Record<string,unknown>{return value!==null&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).sort().join(',')===[...keys].sort().join(',');}
function isDigest(value:unknown):value is string{return typeof value==='string'&&/^[a-f0-9]{64}$/u.test(value);}
