import {AGENTTEAMS_IMAGE_DIGESTS,AGENTTEAMS_SOURCE_TAR_SHA256,GOAL_ROLE_IDS,PersistentRuntimeError,sha256Digest,type MissionBundle,type PersistentRuntimeRepository,type RuntimeBinding,type RuntimeLease,type RuntimeMaterializationBatch,type RuntimeMaterializationCandidate,type RuntimeSubmissionEnvelope} from '@lumiclaw/domain';
import {runBoundedProcess,type PersistentAgentTeamsDriver} from '@lumiclaw/runtime-agentteams';
import {describe,expect,it,vi} from 'vitest';
import type {RuntimeOutputAuthority} from './output-authority.js';
import {HttpGatewayTicketIssuer,PersistentMissionWorker,assertLoopbackGatewayControlOrigin} from './worker.js';

describe('persistent mission worker gateway boundary',()=>{
  it('allows only an explicit high-port HTTP 127.0.0.1 control origin',()=>{expect(assertLoopbackGatewayControlOrigin('http://127.0.0.1:4303')).toBe('http://127.0.0.1:4303');for(const origin of ['https://127.0.0.1:4303','http://localhost:4303','http://host.docker.internal:4303','http://127.0.0.1:80','http://127.0.0.1:4303/path','http://user@127.0.0.1:4303','https://attacker.invalid'])expect(()=>assertLoopbackGatewayControlOrigin(origin)).toThrow('MODEL_GATEWAY_CONTROL_ORIGIN_FORBIDDEN');});

  it('fails before fetch so a bootstrap cannot be sent to an attacker-controlled URL',async()=>{const fetchSpy=vi.spyOn(globalThis,'fetch');expect(()=>new HttpGatewayTicketIssuer('https://attacker.invalid','bootstrap-must-not-leave-host')).toThrow('MODEL_GATEWAY_CONTROL_ORIGIN_FORBIDDEN');expect(fetchSpy).not.toHaveBeenCalled();fetchSpy.mockRestore();});

  it('heartbeats before dispatch and runs the orchestration-only Leader with zero ticket/provider calls',async()=>{const lease=leaderLease();const order:string[]=[];let intent:RuntimeSubmissionEnvelope|undefined;const tickets={issue:vi.fn()};const driver=driverFixture({order});const runtime=runtimeFixture({lease,order,onIntent:(value)=>{intent=value;}});const worker=new PersistentMissionWorker('worker-alpha',runtime,{} as never,{plan:async(_lease:RuntimeLease,value:RuntimeSubmissionEnvelope)=>({acceptedOutputRef:`urn:test:${value.outputDigest}`,candidates:[{kind:'PROTOCOL' as const,authorityId:value.taskId,canonicalDigest:value.outputDigest,payload:value.payload as Record<string,unknown>} ]})} as unknown as RuntimeOutputAuthority,driver,tickets,'http://host.docker.internal:4303',1_000,undefined,()=>new Date('2026-08-23T00:00:00.000Z'));
    await expect(worker.tick()).resolves.toBe('ACCEPTED');expect(order.indexOf('heartbeat')).toBeLessThan(order.indexOf('ensureBinding'));expect(tickets.issue).not.toHaveBeenCalled();expect(driver.generate).not.toHaveBeenCalled();expect(driver.complete).not.toHaveBeenCalled();expect(intent).toMatchObject({controlledProvider:false,payload:{schemaVersion:1,taskId:lease.job.taskContractId,inputDigest:lease.job.contract.inputDigest,agentTeamsExecuted:true,completed:true}});
  });

  it('recovers an exact submitted intent by observation without another model or submit call',async()=>{const lease=leaderLease('ACKNOWLEDGED');const envelope=envelopeFixture(lease);const tickets={issue:vi.fn()};const driver=driverFixture({observed:envelope});const runtime=runtimeFixture({recovery:{lease,envelope}});const authority={plan:vi.fn(async(_lease:RuntimeLease,value:RuntimeSubmissionEnvelope)=>({acceptedOutputRef:`urn:test:${value.outputDigest}`,candidates:[{kind:'PROTOCOL' as const,authorityId:value.taskId,canonicalDigest:value.outputDigest,payload:value.payload as Record<string,unknown>}]}))} as unknown as RuntimeOutputAuthority;const worker=new PersistentMissionWorker('worker-alpha',runtime,{} as never,authority,driver,tickets,'http://host.docker.internal:4303',1_000,undefined,()=>new Date('2026-08-23T00:01:00.000Z'));
    await expect(worker.tick()).resolves.toBe('RECOVERED_SUBMISSION');expect(driver.observeSubmission).toHaveBeenCalledOnce();expect(driver.submit).not.toHaveBeenCalled();expect(driver.generate).not.toHaveBeenCalled();expect(tickets.issue).not.toHaveBeenCalled();expect(authority.plan).toHaveBeenCalledOnce();
  });

  it('recovers ACK without an intent on the same attempt and performs exactly one provider call',async()=>{const {lease,bundle}=claimRecoveryFixture();let intent:RuntimeSubmissionEnvelope|undefined;const tickets={issue:vi.fn(async()=> 'one-use-ticket')};const driver=driverFixture();const generated={schemaVersion:1,taskId:lease.job.taskContractId,inputDigest:lease.job.contract.inputDigest,agentTeamsExecuted:true,frozenBindingDigest:sha256Digest('approved-claims')};vi.mocked(driver.generate).mockResolvedValue({value:generated,outputDigest:sha256Digest(generated),controlledFake:true});const runtime=runtimeFixture({recovery:{lease,envelope:null},onIntent:(value)=>{intent=value;}});const authority={plan:vi.fn(async(_lease:RuntimeLease,value:RuntimeSubmissionEnvelope)=>({acceptedOutputRef:`urn:test:${value.outputDigest}`,candidates:[{kind:'PROTOCOL' as const,authorityId:value.taskId,canonicalDigest:value.outputDigest,payload:value.payload as Record<string,unknown>}]}))} as unknown as RuntimeOutputAuthority;const goals={getBundle:vi.fn(async()=>bundle)};const worker=new PersistentMissionWorker('worker-recovery',runtime,goals as never,authority,driver,tickets,'http://host.docker.internal:4303',1_000,undefined,()=>new Date('2026-08-23T00:01:30.000Z'));
    await expect(worker.tick()).resolves.toBe('RECOVERED_SUBMISSION');expect(driver.acknowledge).toHaveBeenCalledOnce();expect(tickets.issue).toHaveBeenCalledOnce();expect(driver.generate).toHaveBeenCalledOnce();expect(driver.submit).toHaveBeenCalledOnce();expect(intent).toMatchObject({attemptId:lease.attempt.id,attemptNumber:lease.attempt.attemptNumber,outputDigest:sha256Digest(generated)});
  });

  it('keeps accepted output durable when complete fails, then confirms the same outbox intent on retry',async()=>{const lease=leaderLease('ACCEPTED');const envelope=envelopeFixture(lease);const batch=batchFixture(lease,envelope);let claims=0;let confirmed=0;const runtime=runtimeFixture({pending:()=>claims++<2?{lease,batch}:undefined,onConfirm:()=>{confirmed+=1;}});const driver=driverFixture();vi.mocked(driver.complete).mockRejectedValueOnce(new Error('timeout')).mockResolvedValueOnce();const worker=new PersistentMissionWorker('worker-alpha',runtime,{} as never,{} as RuntimeOutputAuthority,driver,{issue:vi.fn()},'http://host.docker.internal:4303',1_000,undefined,()=>new Date('2026-08-23T00:02:00.000Z'));
    await expect(worker.tick()).resolves.toBe('BLOCKED');expect(confirmed).toBe(0);await expect(worker.tick()).resolves.toBe('CONFIRMED_COMPLETION');expect(driver.complete).toHaveBeenCalledTimes(2);expect(confirmed).toBe(1);
  });

  it('fails closed when cancellation revokes the completion lease after the runtime write',async()=>{const lease=leaderLease('ACCEPTED');const envelope=envelopeFixture(lease);const batch=batchFixture(lease,envelope);let claimed=false;const base=runtimeFixture({pending:()=>claimed?undefined:(claimed=true,{lease,batch})});const runtime={...base,confirmRuntimeCompletion:vi.fn(async()=>{throw new PersistentRuntimeError('JOB_LEASE_LOST','RUN_TERMINAL');})} as PersistentRuntimeRepository;const driver=driverFixture();const worker=new PersistentMissionWorker('worker-alpha',runtime,{} as never,{} as RuntimeOutputAuthority,driver,{issue:vi.fn()},'http://host.docker.internal:4303',1_000,undefined,()=>new Date('2026-08-23T00:02:30.000Z'));
    await expect(worker.tick()).resolves.toBe('BLOCKED');await expect(worker.tick()).resolves.toBe('IDLE');expect(driver.complete).toHaveBeenCalledOnce();expect(runtime.confirmRuntimeCompletion).toHaveBeenCalledOnce();
  });

  it('stops lease heartbeats after a bounded hung driver operation times out',async()=>{const lease=leaderLease();let beats=0;const base=runtimeFixture({lease});const runtime={...base,heartbeatLease:vi.fn(async()=>{beats+=1;return lease.job;})} as PersistentRuntimeRepository;const driver=driverFixture();vi.mocked(driver.ensureBinding).mockImplementation(async()=>{await runBoundedProcess(process.execPath,["-e","process.on('SIGTERM',()=>{});setInterval(()=>{},1000)"],undefined,40,30);return bindingFixture(lease);});const tickets={issue:vi.fn()};const worker=new PersistentMissionWorker('worker-alpha',runtime,{} as never,{} as RuntimeOutputAuthority,driver,tickets,'http://host.docker.internal:4303',1_000,undefined,()=>new Date('2026-08-23T00:03:00.000Z'));
    await expect(worker.tick()).resolves.toBe('BLOCKED');const beatsWhenBlocked=beats;await new Promise((resolve)=>setTimeout(resolve,350));expect(beats).toBe(beatsWhenBlocked);expect(tickets.issue).not.toHaveBeenCalled();expect(driver.submit).not.toHaveBeenCalled();
  });

  it('fences a lost old lease before bind, ticket, provider, or submit',async()=>{const lease=leaderLease();let beats=0;const base=runtimeFixture({lease});const runtime={...base,heartbeatLease:vi.fn(async()=>{beats+=1;if(beats>=4)throw new PersistentRuntimeError('JOB_LEASE_LOST');return lease.job;}),bindRuntime:vi.fn()} as PersistentRuntimeRepository;const driver=driverFixture();const tickets={issue:vi.fn()};const worker=new PersistentMissionWorker('worker-alpha',runtime,{} as never,{} as RuntimeOutputAuthority,driver,tickets,'http://host.docker.internal:4303',1_000,undefined,()=>new Date('2026-08-23T00:04:00.000Z'));
    await expect(worker.tick()).resolves.toBe('BLOCKED');expect(driver.dispatch).toHaveBeenCalledOnce();expect(runtime.bindRuntime).not.toHaveBeenCalled();expect(tickets.issue).not.toHaveBeenCalled();expect(driver.generate).not.toHaveBeenCalled();expect(driver.submit).not.toHaveBeenCalled();
  });
});

function leaderLease(state:'LEASED'|'ACKNOWLEDGED'|'ACCEPTED'='LEASED'):RuntimeLease{const now='2026-08-23T00:00:00.000Z';const taskId='task-leader';const inputDigest=sha256Digest('input');const contract={schemaVersion:1 as const,runId:'run-1',bundleId:'bundle-1',bundleDigest:'a'.repeat(64),generation:2,taskId,roleId:'presence-mission-leader' as const,kind:'ORCHESTRATE' as const,mandate:'Coordinate only.',dependencyIds:[],inputDigest,skillLockDigest:sha256Digest('skill'),outputSchema:'lumiclaw.orchestration-receipt.v2',substantive:false,externalActionAllowed:false as const};return {run:{schemaVersion:1,id:'run-1',ownerId:'00000000-0000-4000-8000-000000000001',bundleId:'bundle-1',bundleDigest:'a'.repeat(64),bundleKind:'MISSION_EXECUTION',generation:2,runtimeRequirement:{runtime:'agentteams',version:'v1.2.0',sourceCommit:'793db242257a569d911b1aa59c1cd554af78511f',sourceTarSha256:AGENTTEAMS_SOURCE_TAR_SHA256,license:'Apache-2.0',imageDigests:AGENTTEAMS_IMAGE_DIGESTS,teamProfileVersion:'1.0.0',teamProfileDigest:'b'.repeat(64)},state:'RUNNING',createdBy:'test',createdAt:now,startedAt:now,finishedAt:null,lastReconciledAt:null,errorCode:null,rowVersion:1},job:{schemaVersion:1,id:'job-1',runId:'run-1',taskContractId:taskId,generation:2,roleId:'presence-mission-leader',kind:'ORCHESTRATE',dependencyIds:[],state,availableAt:now,leaseOwner:'worker-alpha',leaseTokenHash:'c'.repeat(64),leaseExpiresAt:'2026-08-23T00:10:00.000Z',attemptCount:1,acceptedAttemptId:state==='ACCEPTED'?'attempt-1':null,acceptedOutputRef:state==='ACCEPTED'?'urn:test:accepted':null,acceptedOutputDigest:state==='ACCEPTED'?sha256Digest({accepted:true}):null,runtimeTaskId:state==='LEASED'?null:taskId,lastErrorCode:null,rowVersion:1,contract},attempt:{schemaVersion:1,id:'attempt-1',jobId:'job-1',attemptNumber:1,roleId:'presence-mission-leader',runtimeTaskId:state==='LEASED'?null:taskId,runtimeActorId:state==='LEASED'?null:'@leader:matrix.local',inputDigest,skillLockDigest:contract.skillLockDigest,schemaRef:contract.outputSchema,state,ackAt:state==='LEASED'?null:now,submittedAt:state==='ACCEPTED'?now:null,outputDigest:state==='ACCEPTED'?sha256Digest({accepted:true}):null,errorCode:null,createdAt:now,updatedAt:now},leaseToken:'lease-token'};}
function claimRecoveryFixture():{lease:RuntimeLease;bundle:MissionBundle}{const base=leaderLease('ACKNOWLEDGED');const taskId='task-claim';const bundleId='bundle-claim';const bundleDigest=sha256Digest('bundle-claim');const inputDigest=sha256Digest('claim-input');const lock={skillId:'evidence-and-claim-grounding',version:'1.0.0',digest:sha256Digest('claim-skill'),source:'skills/evidence-and-claim-grounding/SKILL.md'};const skillLockDigest=sha256Digest([lock]);const contract={...base.job.contract,runId:base.run.id,bundleId,bundleDigest,taskId,roleId:'evidence-claim-steward' as const,kind:'FREEZE_CLAIMS' as const,mandate:'Freeze approved claims only.',inputDigest,skillLockDigest,outputSchema:'lumiclaw.frozen-claim-set.v2',substantive:true};const job={...base.job,id:'job-claim',taskContractId:taskId,roleId:contract.roleId,kind:contract.kind,runtimeTaskId:taskId,contract};const attempt={...base.attempt,id:'attempt-claim',jobId:job.id,roleId:contract.roleId,runtimeTaskId:taskId,runtimeActorId:'@claim:matrix.local',inputDigest,skillLockDigest,schemaRef:contract.outputSchema};const run={...base.run,bundleId,bundleDigest};const task={taskId,roleId:contract.roleId,kind:contract.kind,dependsOn:[],inputDigest,skillLockDigest,outputSchema:contract.outputSchema};const bundle={kind:'MISSION_EXECUTION',bundleId,canonicalDigest:bundleDigest,generation:run.generation,parentBundleId:'intent-claim',parentBundleDigest:sha256Digest('intent-claim'),tasks:[task],roleContexts:[{roleId:contract.roleId,knowledgeItemIds:[],accountProfileRevisionIds:[],visibleBindings:['APPROVED_SNAPSHOT'],excluded:['SECRETS'],contextDigest:sha256Digest('context')}],skillLocks:[lock],inputBindings:{},activationUnits:[]} as unknown as MissionBundle;return {lease:{run,job,attempt,leaseToken:'recovery-token'},bundle};}
function bindingFixture(lease:RuntimeLease):RuntimeBinding{return {schemaVersion:1,runId:lease.run.id,runtimeInstanceId:'controller',runtimeProjectId:lease.run.id,teamProfileVersion:lease.run.runtimeRequirement.teamProfileVersion,teamProfileDigest:lease.run.runtimeRequirement.teamProfileDigest,runtimeVersion:'v1.2.0',runtimeDigest:AGENTTEAMS_SOURCE_TAR_SHA256,memberBindings:GOAL_ROLE_IDS.map((roleId)=>({roleId,runtimeActorId:roleId===lease.job.roleId?'@leader:matrix.local':`@${roleId}:matrix.local`})),state:'BOUND',boundAt:lease.run.createdAt,lastObservedAt:lease.run.createdAt};}
function envelopeFixture(lease:RuntimeLease):RuntimeSubmissionEnvelope{const payload={schemaVersion:1,taskId:lease.job.taskContractId,inputDigest:lease.job.contract.inputDigest,agentTeamsExecuted:true,completed:true};return {schemaVersion:1,runId:lease.run.id,bundleId:lease.run.bundleId,bundleDigest:lease.run.bundleDigest,generation:lease.run.generation,taskId:lease.job.taskContractId,attemptId:lease.attempt.id,attemptNumber:lease.attempt.attemptNumber,roleId:lease.job.roleId,runtimeTaskId:lease.job.taskContractId,runtimeActorId:'@leader:matrix.local',inputDigest:lease.job.contract.inputDigest,skillLockDigest:lease.job.contract.skillLockDigest,outputSchema:lease.job.contract.outputSchema,payload,outputDigest:sha256Digest(payload),submittedAt:'2026-08-23T00:00:00.000Z',evidenceMaturity:'AGENTTEAMS_RUNTIME',agentTeamsExecuted:true,controlledProvider:false};}
function batchFixture(lease:RuntimeLease,envelope:RuntimeSubmissionEnvelope):RuntimeMaterializationBatch{return {schemaVersion:1,id:'batch-1',ownerId:lease.run.ownerId,runId:lease.run.id,jobId:lease.job.id,attemptId:lease.attempt.id,outputDigest:envelope.outputDigest,acceptedOutputRef:'urn:test:accepted',batchDigest:sha256Digest('batch'),candidates:[{kind:'PROTOCOL',authorityId:envelope.taskId,canonicalDigest:envelope.outputDigest,payload:envelope.payload as Record<string,unknown>}],envelope,state:'COMMITTED',createdAt:envelope.submittedAt,committedAt:envelope.submittedAt};}
function driverFixture(options:{order?:string[];observed?:RuntimeSubmissionEnvelope}={}):PersistentAgentTeamsDriver{const binding=(lease:RuntimeLease)=>bindingFixture(lease);let currentLease:RuntimeLease;return {readiness:vi.fn(async()=>({state:'READY' as const,reasonCode:null,memberCount:6,runtimeVersion:'v1.2.0',runtimeDigest:AGENTTEAMS_SOURCE_TAR_SHA256,sourceCommit:'793db242257a569d911b1aa59c1cd554af78511f',sourceTarSha256:AGENTTEAMS_SOURCE_TAR_SHA256,teamProfileVersion:'1.0.0',teamProfileDigest:'b'.repeat(64),identityEvidence:null})),ensureBinding:vi.fn(async(run,jobs)=>{options.order?.push('ensureBinding');currentLease={...leaderLease(),run,job:jobs[0]??leaderLease().job};return binding(currentLease);}),dispatch:vi.fn(async(_binding,contract)=>{options.order?.push('dispatch');return {runtimeTaskId:contract.taskId,runtimeActorId:'@leader:matrix.local'};}),acknowledge:vi.fn(async()=>{}),generate:vi.fn(),submit:vi.fn(async(_contract,_actor,payload)=>({payload,submittedAt:'2026-08-23T00:00:00.000Z'})),complete:vi.fn(async()=>{}),observe:vi.fn(async()=>({knownRuntimeTaskIds:[],submittedOutputDigests:[]})),observeSubmission:vi.fn(async()=>options.observed===undefined?{state:'MISSING' as const}:{state:'SUBMITTED' as const,payload:options.observed.payload,outputDigest:options.observed.outputDigest,submittedAt:options.observed.submittedAt})};}
function runtimeFixture(options:{lease?:RuntimeLease;recovery?:{lease:RuntimeLease;envelope:RuntimeSubmissionEnvelope|null};pending?:()=>{lease:RuntimeLease;batch:RuntimeMaterializationBatch}|undefined;order?:string[];onIntent?:(value:RuntimeSubmissionEnvelope)=>void;onConfirm?:()=>void}={}):PersistentRuntimeRepository{let acquired=false;const lease=options.lease??options.recovery?.lease??leaderLease();const binding=bindingFixture(lease);return {health:async()=>true,recordWorkerHeartbeat:async()=>{},getWorkerHeartbeat:async()=>null,acquireStagedMaterialization:async()=>undefined,acquirePendingCompletion:async()=>options.pending?.(),acquireSubmissionRecovery:async()=>{if(options.recovery===undefined||acquired)return undefined;acquired=true;return options.recovery;},acquireJob:async()=>{if(options.lease===undefined||acquired)return undefined;acquired=true;return lease;},heartbeatLease:async()=>{options.order?.push('heartbeat');return lease.job;},getProjection:async()=>({runId:lease.run.id,jobs:[lease.job]} as never),getWorkspace:async()=>({bindings:[binding]} as never),bindRuntime:async()=>{},recordAck:async()=>{},recordSubmissionIntent:async(_worker:string,_job:string,_attempt:string,_token:string,value:RuntimeSubmissionEnvelope)=>{options.onIntent?.(value);},stageMaterialization:async(_worker:string,_job:string,_attempt:string,_token:string,envelope:RuntimeSubmissionEnvelope,acceptedOutputRef:string,candidates:RuntimeMaterializationCandidate[])=>({...batchFixture(lease,envelope),acceptedOutputRef,candidates,state:'STAGED' as const,committedAt:null}),finalizeMaterialization:async()=>({accepted:true,duplicate:false,run:lease.run}),confirmRuntimeCompletion:async()=>{options.onConfirm?.();},quarantineSubmission:async()=>{},markAttemptUnknown:async()=>{throw new Error('unexpected mark unknown');}} as unknown as PersistentRuntimeRepository;}
