import {
  ArtifactContractError,createArtifactInvalidation,sha256Digest,verifyManualPublishPackage,
  type ArtifactAuditDecision,type ArtifactInvalidationEvent,type ArtifactOwnerDecision,type ArtifactPublishRepository,type ArtifactRevisionV3,type ArtifactWorkspace,
  type ManualPublishPackage,type PackageHelperEvent,type QuarantinedSubmission,type RegenerationRequest
} from '@lumiclaw/domain';
import {Kysely,PostgresDialect,type Transaction} from 'kysely';
import {Pool} from 'pg';
import type {Database} from './database.js';

export class PostgresArtifactPublishRepository implements ArtifactPublishRepository {
  readonly #pool:Pool;readonly #database:Kysely<Database>;
  public constructor(connectionString:string){this.#pool=new Pool({connectionString,max:4});this.#database=new Kysely<Database>({dialect:new PostgresDialect({pool:this.#pool})});this.#pool.on('error',(error)=>console.error('PostgreSQL artifact-publish idle client error',error.message));}
  public async health(){const result=await this.#pool.query<{exists:boolean}>("select to_regclass('public.artifact_revisions_v3') is not null as exists");return result.rows[0]?.exists===true;}
  public async getWorkspace(ownerId:string):Promise<ArtifactWorkspace>{const [revisionRows,quarantineRows,auditRows,decisionRows,requestRows,packageRows,eventRows,invalidationRows]=await Promise.all([
    this.#database.selectFrom('artifact_revisions_v3').select('payload').where('owner_profile_id','=',ownerId).orderBy('activation_unit_id').orderBy('revision').execute(),this.#database.selectFrom('artifact_submission_quarantines_v3').select('payload').where('owner_profile_id','=',ownerId).orderBy('created_at').execute(),this.#database.selectFrom('artifact_audit_decisions_v3').select('payload').where('owner_profile_id','=',ownerId).orderBy('created_at').execute(),this.#database.selectFrom('artifact_owner_decisions_v3').select('payload').where('owner_profile_id','=',ownerId).orderBy('created_at').execute(),this.#database.selectFrom('artifact_regeneration_requests_v3').select('payload').where('owner_profile_id','=',ownerId).orderBy('created_at').execute(),this.#database.selectFrom('manual_publish_packages_v3').select('payload').where('owner_profile_id','=',ownerId).orderBy('created_at').execute(),this.#database.selectFrom('manual_publish_helper_events_v3').select('payload').where('owner_profile_id','=',ownerId).orderBy('created_at').execute(),this.#database.selectFrom('artifact_invalidation_events_v3').select('payload').where('owner_profile_id','=',ownerId).orderBy('created_at').execute()]);
    return {revisions:revisionRows.map((row)=>json(row.payload)),quarantines:quarantineRows.map((row)=>json(row.payload)),audits:auditRows.map((row)=>json(row.payload)),ownerDecisions:decisionRows.map((row)=>json(row.payload)),regenerationRequests:requestRows.map((row)=>json(row.payload)),packages:packageRows.map((row)=>json(row.payload)),helperEvents:eventRows.map((row)=>json(row.payload)),invalidations:invalidationRows.map((row)=>json(row.payload))};}
  public async getRevision(ownerId:string,id:string){return this.payload<ArtifactRevisionV3>('artifact_revisions_v3',ownerId,'id',id);}
  public async getAudit(ownerId:string,id:string){return this.payload<ArtifactAuditDecision>('artifact_audit_decisions_v3',ownerId,'id',id);}
  public async getOwnerDecision(ownerId:string,id:string){return this.payload<ArtifactOwnerDecision>('artifact_owner_decisions_v3',ownerId,'id',id);}
  public async getPackage(ownerId:string,id:string){return this.payload<ManualPublishPackage>('manual_publish_packages_v3',ownerId,'id',id);}

  public async appendRevision(ownerId:string,revision:ArtifactRevisionV3,expectedHeadDigest:string|null,idempotencyKey:string,now:Date){return this.withIdempotency(ownerId,'REVISION',idempotencyKey,{revision:revision.canonicalDigest,expectedHeadDigest},now,async(trx)=>{
    if(revision.ownerId!==ownerId)throw new ArtifactContractError('OWNER_BOUNDARY_VIOLATION');const bundle=await trx.selectFrom('mission_bundle_generations_v2').select(['canonical_digest','kind']).where('owner_profile_id','=',ownerId).where('bundle_id','=',revision.inputBindings.executionBundle.id).executeTakeFirst();if(bundle===undefined||bundle.kind!=='MISSION_EXECUTION'||bundle.canonical_digest.trim()!==revision.inputBindings.executionBundle.digest)throw new ArtifactContractError('ARTIFACT_INPUT_MISMATCH');
    const head=await trx.selectFrom('artifact_heads_v3').selectAll().where('owner_profile_id','=',ownerId).where('activation_unit_id','=',revision.activationUnitId).forUpdate().executeTakeFirst();if(head===undefined){if(expectedHeadDigest!==null||revision.revision!==1||revision.parentRevisionId!==null)throw new ArtifactContractError('OWNER_DECISION_STALE');}else if(head.canonical_digest.trim()!==expectedHeadDigest||revision.revision!==head.revision+1||revision.parentRevisionId!==head.revision_id)throw new ArtifactContractError('OWNER_DECISION_STALE');
    await trx.insertInto('artifact_revisions_v3').values({owner_profile_id:ownerId,id:revision.id,activation_unit_id:revision.activationUnitId,platform_code:revision.platformCode,revision:revision.revision,parent_revision_id:revision.parentRevisionId,producer_identity_id:revision.producerIdentityId,canonical_digest:revision.canonicalDigest,execution_bundle_id:revision.inputBindings.executionBundle.id,execution_bundle_digest:revision.inputBindings.executionBundle.digest,account_profile_revision_id:revision.inputBindings.accountProfile.id,payload:JSON.stringify(revision),created_at:now}).execute();if(head===undefined)await trx.insertInto('artifact_heads_v3').values({owner_profile_id:ownerId,activation_unit_id:revision.activationUnitId,revision_id:revision.id,revision:revision.revision,canonical_digest:revision.canonicalDigest,row_version:1,updated_at:now}).execute();else await trx.updateTable('artifact_heads_v3').set({revision_id:revision.id,revision:revision.revision,canonical_digest:revision.canonicalDigest,row_version:head.row_version+1,updated_at:now}).where('owner_profile_id','=',ownerId).where('activation_unit_id','=',revision.activationUnitId).executeTakeFirstOrThrow();
    const invalidations:ArtifactInvalidationEvent[]=[];const prior=await trx.selectFrom('artifact_revisions_v3').select(['id','canonical_digest']).where('owner_profile_id','=',ownerId).where('activation_unit_id','=',revision.activationUnitId).where('id','!=',revision.id).execute();for(const row of prior){const event=createArtifactInvalidation({ownerId,artifactRevisionId:row.id,reasonCode:'NEW_REVISION',previousDigest:row.canonical_digest.trim(),currentDigest:revision.canonicalDigest,createdAt:now.toISOString()});const inserted=await this.insertInvalidation(trx,event);if(inserted)invalidations.push(event);}return {revision,invalidations,replayed:false};
  });}
  public async appendQuarantine(ownerId:string,value:QuarantinedSubmission,idempotencyKey:string,now:Date){return this.withIdempotency(ownerId,'QUARANTINE',idempotencyKey,{value},now,async(trx)=>{if(value.ownerId!==ownerId)throw new ArtifactContractError('OWNER_BOUNDARY_VIOLATION');await trx.insertInto('artifact_submission_quarantines_v3').values({owner_profile_id:ownerId,submission_id:value.submissionId,activation_unit_id:value.activationUnitId,reason_code:value.reasonCode,submission_digest:value.submissionDigest,payload:JSON.stringify(value),created_at:now}).execute();return {quarantine:value,replayed:false};});}
  public async appendAudit(ownerId:string,value:ArtifactAuditDecision,expectedRevisionDigest:string,idempotencyKey:string,now:Date){return this.withIdempotency(ownerId,'AUDIT',idempotencyKey,{value:value.canonicalDigest,expectedRevisionDigest},now,async(trx)=>{const revision=await this.requireActiveRevision(trx,ownerId,value.artifactRevisionId,expectedRevisionDigest);if(value.ownerId!==ownerId||value.artifactRevisionDigest!==revision.canonicalDigest)throw new ArtifactContractError('OWNER_DECISION_STALE');await trx.insertInto('artifact_audit_decisions_v3').values({owner_profile_id:ownerId,id:value.id,artifact_revision_id:value.artifactRevisionId,artifact_revision_digest:value.artifactRevisionDigest,auditor_identity_id:value.auditorIdentityId,result:value.result,canonical_digest:value.canonicalDigest,payload:JSON.stringify(value),created_at:now}).execute();return {audit:value,replayed:false};});}
  public async appendOwnerDecision(ownerId:string,value:ArtifactOwnerDecision,expectedAuditDigest:string,idempotencyKey:string,now:Date){return this.withIdempotency(ownerId,'OWNER_DECISION',idempotencyKey,{value:value.canonicalDigest,expectedAuditDigest},now,async(trx)=>{await this.requireActiveRevision(trx,ownerId,value.artifactRevisionId,value.artifactRevisionDigest);const audit=await trx.selectFrom('artifact_audit_decisions_v3').select('canonical_digest').where('owner_profile_id','=',ownerId).where('id','=',value.auditDecisionId).executeTakeFirst();if(value.ownerId!==ownerId||audit?.canonical_digest.trim()!==expectedAuditDigest||value.auditDecisionDigest!==expectedAuditDigest)throw new ArtifactContractError('OWNER_DECISION_STALE');await trx.insertInto('artifact_owner_decisions_v3').values({owner_profile_id:ownerId,id:value.id,artifact_revision_id:value.artifactRevisionId,audit_decision_id:value.auditDecisionId,result:value.result,canonical_digest:value.canonicalDigest,payload:JSON.stringify(value),created_at:now}).execute();return {decision:value,replayed:false};});}
  public async appendRegenerationRequest(ownerId:string,value:RegenerationRequest,expectedRevisionDigest:string,idempotencyKey:string,now:Date){return this.withIdempotency(ownerId,'REGENERATE',idempotencyKey,{value:value.canonicalDigest,expectedRevisionDigest},now,async(trx)=>{await this.requireActiveRevision(trx,ownerId,value.artifactRevisionId,expectedRevisionDigest);if(value.ownerId!==ownerId)throw new ArtifactContractError('OWNER_BOUNDARY_VIOLATION');await trx.insertInto('artifact_regeneration_requests_v3').values({owner_profile_id:ownerId,id:value.id,artifact_revision_id:value.artifactRevisionId,artifact_revision_digest:value.artifactRevisionDigest,canonical_digest:value.canonicalDigest,payload:JSON.stringify(value),created_at:now}).execute();return {request:value,replayed:false};});}
  public async appendPackage(ownerId:string,value:ManualPublishPackage,expectedDecisionDigest:string,idempotencyKey:string,now:Date){return this.withIdempotency(ownerId,'PACKAGE',idempotencyKey,{value:value.manifestDigest,expectedDecisionDigest},now,async(trx)=>{await this.requireActiveRevision(trx,ownerId,value.artifactRevisionId,value.artifactRevisionDigest);const decision=await trx.selectFrom('artifact_owner_decisions_v3').select(['canonical_digest','result']).where('owner_profile_id','=',ownerId).where('id','=',value.ownerDecisionId).executeTakeFirst();if(value.ownerId!==ownerId||decision?.canonical_digest.trim()!==expectedDecisionDigest||decision.result!=='APPROVE'||value.ownerDecisionDigest!==expectedDecisionDigest||!verifyManualPublishPackage(value).ok)throw new ArtifactContractError('PACKAGE_INPUT_INVALIDATED');const existing=await trx.selectFrom('manual_publish_packages_v3').select('payload').where('owner_profile_id','=',ownerId).where('exact_input_digest','=',value.exactInputDigest).executeTakeFirst();if(existing!==undefined)return {package:json<ManualPublishPackage>(existing.payload),replayed:true};await trx.insertInto('manual_publish_packages_v3').values({owner_profile_id:ownerId,id:value.id,artifact_revision_id:value.artifactRevisionId,audit_decision_id:value.auditDecisionId,owner_decision_id:value.ownerDecisionId,exact_input_digest:value.exactInputDigest,manifest_digest:value.manifestDigest,platform_code:value.platformCode,payload:JSON.stringify(value),created_at:now}).execute();await trx.insertInto('manual_publish_package_files_v3').values(value.orderedFiles.map((file)=>({owner_profile_id:ownerId,package_id:value.id,position:file.position,file_name:file.fileName,media_type:file.mediaType,content_digest:file.digest,content:file.content}))).execute();return {package:value,replayed:false};});}
  public async appendHelperEvent(ownerId:string,value:PackageHelperEvent,idempotencyKey:string,now:Date){return this.withIdempotency(ownerId,'HELPER',idempotencyKey,{value:value.canonicalDigest},now,async(trx)=>{const pack=await trx.selectFrom('manual_publish_packages_v3').select(['manifest_digest','payload']).where('owner_profile_id','=',ownerId).where('id','=',value.packageId).executeTakeFirst();const payload=pack===undefined?undefined:json<ManualPublishPackage>(pack.payload);if(pack?.manifest_digest.trim()!==value.packageDigest||payload===undefined||value.ownerId!==ownerId)throw new ArtifactContractError('PACKAGE_INPUT_INVALIDATED');await this.requireActiveRevision(trx,ownerId,payload.artifactRevisionId,payload.artifactRevisionDigest);await trx.insertInto('manual_publish_helper_events_v3').values({owner_profile_id:ownerId,id:value.id,package_id:value.packageId,action:value.action,external_state:'UNVERIFIED_EXTERNAL_STATE',canonical_digest:value.canonicalDigest,payload:JSON.stringify(value),created_at:now}).execute();return {event:value,replayed:false};});}
  public async invalidateBindings(ownerId:string,revisionId:string,reasonCode:ArtifactInvalidationEvent['reasonCode'],previousDigest:string,currentDigest:string,now:Date){return this.#database.transaction().execute(async(trx)=>{await this.requireRevision(trx,ownerId,revisionId,previousDigest);const event=createArtifactInvalidation({ownerId,artifactRevisionId:revisionId,reasonCode,previousDigest,currentDigest,createdAt:now.toISOString()});await this.insertInvalidation(trx,event);return event;});}
  public async close(){await this.#database.destroy();}

  private async payload<T>(table:'artifact_revisions_v3'|'artifact_audit_decisions_v3'|'artifact_owner_decisions_v3'|'manual_publish_packages_v3',ownerId:string,column:'id',id:string):Promise<T|undefined>{const row=await this.#database.selectFrom(table).select('payload').where('owner_profile_id','=',ownerId).where(column,'=',id).executeTakeFirst();return row===undefined?undefined:json(row.payload);}
  private async requireRevision(trx:Transaction<Database>,ownerId:string,id:string,digest:string){const row=await trx.selectFrom('artifact_revisions_v3').select(['canonical_digest','payload']).where('owner_profile_id','=',ownerId).where('id','=',id).executeTakeFirst();if(row===undefined||row.canonical_digest.trim()!==digest)throw new ArtifactContractError('OWNER_DECISION_STALE');return json<ArtifactRevisionV3>(row.payload);}
  private async requireActiveRevision(trx:Transaction<Database>,ownerId:string,id:string,digest:string){const revision=await this.requireRevision(trx,ownerId,id,digest);const invalid=await trx.selectFrom('artifact_invalidation_events_v3').select('id').where('owner_profile_id','=',ownerId).where('artifact_revision_id','=',id).executeTakeFirst();if(invalid!==undefined)throw new ArtifactContractError('PACKAGE_INPUT_INVALIDATED');return revision;}
  private async insertInvalidation(trx:Transaction<Database>,event:ArtifactInvalidationEvent):Promise<boolean>{const result=await trx.insertInto('artifact_invalidation_events_v3').values({owner_profile_id:event.ownerId,id:event.id,artifact_revision_id:event.artifactRevisionId,reason_code:event.reasonCode,previous_digest:event.previousDigest,current_digest:event.currentDigest,canonical_digest:event.canonicalDigest,payload:JSON.stringify(event),created_at:event.createdAt}).onConflict((conflict)=>conflict.columns(['owner_profile_id','artifact_revision_id','reason_code','current_digest']).doNothing()).executeTakeFirst();return Number(result.numInsertedOrUpdatedRows??0)>0;}
  private async withIdempotency<T extends {replayed:boolean}>(ownerId:string,route:string,key:string,request:unknown,now:Date,operation:(trx:Transaction<Database>)=>Promise<T>):Promise<T>{if(key.length<8||key.length>128)throw new ArtifactContractError('IDEMPOTENCY_KEY_REQUIRED');const requestDigest=sha256Digest(request);return this.#database.transaction().execute(async(trx)=>{const existing=await trx.selectFrom('artifact_publish_idempotency_v3').selectAll().where('owner_profile_id','=',ownerId).where('route','=',route).where('idempotency_key','=',key).executeTakeFirst();if(existing!==undefined){if(existing.request_digest.trim()!==requestDigest)throw new ArtifactContractError('IDEMPOTENCY_KEY_REUSED');return {...json<T>(existing.response_body),replayed:true};}const response=await operation(trx);await trx.insertInto('artifact_publish_idempotency_v3').values({owner_profile_id:ownerId,route,idempotency_key:key,request_digest:requestDigest,response_body:JSON.stringify(response),created_at:now}).execute();return response;});}
}
function json<T>(value:unknown):T{return (typeof value==='string'?JSON.parse(value):value) as T;}
