import {PostgresMediaArtifactRepository} from './media-artifact-repository.js';
import {createMediaGenerationSpec,sha256Digest} from '@lumiclaw/domain';
import {Pool} from 'pg';
import {describe,expect,it} from 'vitest';

const url=process.env.SDD012_POSTGRES_URL;const suite=url===undefined?describe.skip:describe;
const owner='018f0000-0000-7000-8000-000000000012';const account='018f0000-0000-7000-8000-000000000013';const baseRevision='xhs-base-revision';const baseDigest=sha256Digest('sdd012-base');

suite('SDD-012 PostgreSQL media authority',()=>{
  it('serializes generation, freezes unknown create outcome, and recovers only the same task id',async()=>{const pool=new Pool({connectionString:url!});await seed(pool);let repository=new PostgresMediaArtifactRepository(url!);try{
    const spec=createMediaGenerationSpec({ownerId:owner,artifactRevisionId:baseRevision,artifactRevisionDigest:baseDigest,imageSpecPosition:1,promptTextPrivateRef:'private-prompt://sdd012/1',promptText:'无文字的杭州城市光影插画背景',altText:'杭州城市光影插画',overlayCopy:'让品牌在每个市场被看见',createdAt:'2026-08-24T00:00:00.000Z'});
    const concurrent=await Promise.all([repository.enqueue(owner,[spec],1,'media-adapter://controlled-fake/v1','sdd012-same-click',new Date('2026-08-24T00:00:00.000Z')),repository.enqueue(owner,[spec],1,'media-adapter://controlled-fake/v1','sdd012-same-click',new Date('2026-08-24T00:00:00.000Z'))]);expect(concurrent.flatMap((value)=>value.jobs)).toHaveLength(2);expect(new Set(concurrent.flatMap((value)=>value.jobs.map((job)=>job.id))).size).toBe(1);expect(concurrent.filter((value)=>value.replayed)).toHaveLength(1);
    let lease=await repository.acquireJob('worker-a',1,new Date('2026-08-24T00:00:01.000Z'));expect(lease).toBeDefined();await repository.persistSubmissionIntent('worker-a',lease!.job.id,lease!.leaseToken,1,new Date('2026-08-24T00:00:01.000Z'));expect(await repository.acquireJob('worker-b',1000,new Date('2026-08-24T00:00:02.000Z'))).toBeUndefined();expect((await repository.getJob(owner,lease!.job.id))!.job).toMatchObject({state:'UNKNOWN_CHARGE_STATE',errorCode:'MEDIA_SUBMIT_UNKNOWN_CHARGE_STATE',providerTaskId:null});
    const second=(await repository.enqueue(owner,[spec],2,'media-adapter://controlled-fake/v1','sdd012-next-generation',new Date('2026-08-24T00:00:03.000Z'))).jobs[0]!;lease=await repository.acquireJob('worker-a',1,new Date('2026-08-24T00:00:04.000Z'));await repository.persistSubmissionIntent('worker-a',lease!.job.id,lease!.leaseToken,1,new Date('2026-08-24T00:00:04.000Z'));await repository.persistSubmissionOutcome('worker-a',lease!.job.id,lease!.leaseToken,{kind:'ACCEPTED',providerTaskId:'task-unified-sdd012-one',providerSubmittedAt:'2026-08-24T00:00:04.000Z',reservedAmount:2,providerUsageDigest:null,observedAt:'2026-08-24T00:00:04.000Z'},new Date('2026-08-24T00:00:04.000Z'));await repository.close();repository=new PostgresMediaArtifactRepository(url!);const recovered=await repository.acquireJob('worker-b',1000,new Date('2026-08-24T00:00:05.000Z'));expect(recovered?.job).toMatchObject({id:second.id,state:'PROVIDER_PENDING',providerTaskId:'task-unified-sdd012-one',attemptCount:1});
    const counts=(await pool.query<{jobs:string;intents:string}>(`select (select count(*) from media_generation_jobs_v2)::text jobs,(select count(*) from media_provider_submission_intents_v2)::text intents`)).rows[0];expect(counts).toEqual({jobs:'2',intents:'2'});
  }finally{await repository.close();await pool.end();}},30_000);
});

async function seed(pool:Pool){await pool.query(`insert into local_owner_profiles(id,singleton_key,schema_version,display_name,state,created_at,updated_at) values($1,true,1,'SDD-012 synthetic owner','PROFILE_READY',now(),now())`,[owner]);await pool.query(`insert into knowledge_profile_revisions(owner_profile_id,id,kind,platform_code,version,digest,payload,created_at) values($1,$2,'ACCOUNT','XIAOHONGSHU',1,$3,$4,now())`,[owner,account,sha256Digest('account'),{classification:'PUBLIC_SAFE_SYNTHETIC'}]);await pool.query(`insert into artifact_revisions_v3(owner_profile_id,id,activation_unit_id,platform_code,revision,parent_revision_id,producer_identity_id,canonical_digest,execution_bundle_id,execution_bundle_digest,account_profile_revision_id,payload,created_at) values($1,$2,'activation-sdd012','XIAOHONGSHU',1,null,'xhs-producer',$3,'bundle-sdd012',$4,$5,$6,now())`,[owner,baseRevision,baseDigest,sha256Digest('bundle'),account,{classification:'PUBLIC_SAFE_SYNTHETIC'}]);}
