import {createHash,randomBytes} from 'node:crypto';
import {Pool,type PoolClient} from 'pg';
import {
  MediaContractError,advanceMediaGenerationJob,applyProviderSubmissionOutcome,applyProviderTaskObservation,
  claimMediaGenerationJob,createMediaGenerationJob,heartbeatMediaGenerationJob,recordProviderSubmissionIntent,sha256Digest,
  type ArtifactRevisionV4,type CompositedMediaAssetV2,type CostReceipt,type ManualPublishPackageV4,type MediaArtifactRepository,
  type MediaAuditDecisionV4,type MediaBlobRef,type MediaBlobStage,type MediaCompositionSpecV1,type MediaGenerationJob,
  type MediaGenerationSpec,type MediaGovernanceInvalidation,type MediaLease,type MediaOwnerDecisionV4,type MediaWorkspace,
  type ProviderSubmissionOutcome,type ProviderTaskObservation,type RawProviderMediaAssetV2,type RightsReceipt
} from '@lumiclaw/domain';

type PayloadRow<T>={payload:T|string};
const eligibleStates=['QUEUED','PROVIDER_PENDING','PROVIDER_PROCESSING','DOWNLOADING','VERIFYING','COMPOSING'] as const;

/** PostgreSQL is the authority for jobs, task/cost/rights receipts and every raw/final lineage edge. */
export class PostgresMediaArtifactRepository implements MediaArtifactRepository {
  readonly #pool:Pool;
  public constructor(connectionString:string){this.#pool=new Pool({connectionString,max:6});this.#pool.on('error',(error)=>console.error('PostgreSQL media repository idle client error',error.message));}
  public async health(){const row=await this.#pool.query<{ready:boolean}>("select to_regclass('public.media_generation_jobs_v2') is not null as ready");return row.rows[0]?.ready===true;}
  public async close(){await this.#pool.end();}

  public async enqueue(ownerId:string,specs:MediaGenerationSpec[],generation:number,providerAdapterRef:string,idempotencyKey:string,now:Date){
    if(idempotencyKey.length<8||idempotencyKey.length>128)throw new MediaContractError('MEDIA_JOB_STATE_INVALID');
    return this.tx(async(client)=>{const route='MEDIA_GENERATION';const requestDigest=sha256Digest({specs:specs.map((value)=>value.canonicalDigest),generation,providerAdapterRef});
      await client.query('select pg_advisory_xact_lock(hashtextextended($1,0))',[`${ownerId}:${route}:${idempotencyKey}`]);
      const replay=await client.query<PayloadRow<{jobs:MediaGenerationJob[]}>&{request_digest:string}>('select request_digest,response_body as payload from media_idempotency_v2 where owner_profile_id=$1 and route=$2 and idempotency_key=$3',[ownerId,route,idempotencyKey]);
      if(replay.rowCount){if(replay.rows[0]!.request_digest.trim()!==requestDigest)throw new MediaContractError('MEDIA_JOB_STATE_INVALID');return {jobs:json<{jobs:MediaGenerationJob[]}>(replay.rows[0]!.payload).jobs,replayed:true};}
      const jobs:MediaGenerationJob[]=[];for(const spec of specs){if(spec.ownerId!==ownerId)throw new MediaContractError('MEDIA_JOB_STATE_INVALID');
        await client.query(`insert into media_generation_specs_v2(owner_profile_id,id,artifact_revision_id,artifact_revision_digest,position,source_prompt_digest,canonical_digest,payload,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9) on conflict(owner_profile_id,id) do nothing`,[ownerId,spec.id,spec.artifactRevisionId,spec.artifactRevisionDigest,spec.imageSpecPosition,spec.sourcePromptDigest,spec.canonicalDigest,spec,spec.createdAt]);
        const job=createMediaGenerationJob({ownerId,generationSpec:spec,generation,providerAdapterRef,createdAt:now.toISOString()});jobs.push(job);
        await client.query(`insert into media_generation_jobs_v2(owner_profile_id,id,spec_id,spec_digest,artifact_revision_digest,position,generation,request_digest,state,provider_adapter_ref,provider_task_id,lease_owner,lease_token_hash,lease_expires_at,attempt_count,error_code,payload,created_at,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19) on conflict(owner_profile_id,id) do nothing`,jobValues(job));
      }
      await client.query('insert into media_idempotency_v2(owner_profile_id,route,idempotency_key,request_digest,response_body,created_at) values($1,$2,$3,$4,$5,$6)',[ownerId,route,idempotencyKey,requestDigest,{jobs},now]);return {jobs,replayed:false};
    });
  }

  public async getWorkspace(ownerId:string):Promise<MediaWorkspace>{const tables=[
    ['media_generation_specs_v2','specs','created_at'],['media_generation_jobs_v2','jobs','created_at'],['media_provider_task_receipts_v2','taskReceipts','observed_at'],['media_cost_receipts_v2','costReceipts','created_at'],['media_rights_receipts_v2','rightsReceipts','created_at'],['media_raw_assets_v2','rawAssets','created_at'],['media_composition_specs_v1','compositionSpecs','created_at'],['media_composited_assets_v2','finalAssets','created_at'],['artifact_revisions_v4','revisions','created_at'],['artifact_audit_decisions_v4','audits','created_at'],['artifact_owner_decisions_v4','ownerDecisions','created_at'],['manual_publish_packages_v4','packages','created_at'],['media_invalidation_events_v1','invalidations','created_at'],['media_blob_staging_v1','staging','created_at']
  ] as const;const workspace={} as unknown as MediaWorkspace;for(const [table,key,order] of tables){const result=await this.#pool.query<PayloadRow<unknown>>(`select payload from ${table} where owner_profile_id=$1 order by ${order}`,[ownerId]);(workspace as unknown as Record<string,unknown>)[key]=result.rows.map((row)=>json(row.payload));}return workspace;}

  public async getJob(ownerId:string,jobId:string){const result=await this.#pool.query<{job:MediaGenerationJob|string;spec:MediaGenerationSpec|string}>(`select j.payload as job,s.payload as spec from media_generation_jobs_v2 j join media_generation_specs_v2 s on s.owner_profile_id=j.owner_profile_id and s.id=j.spec_id where j.owner_profile_id=$1 and j.id=$2`,[ownerId,jobId]);const row=result.rows[0];return row?{job:json(row.job),spec:json(row.spec)}:undefined;}

  public async acquireJob(workerId:string,leaseMs:number,now:Date):Promise<MediaLease|undefined>{return this.tx(async(client)=>{
    await client.query(`update media_generation_jobs_v2 set state='UNKNOWN_CHARGE_STATE',error_code='MEDIA_SUBMIT_UNKNOWN_CHARGE_STATE',payload=jsonb_set(jsonb_set(jsonb_set(payload,'{state}',to_jsonb('UNKNOWN_CHARGE_STATE'::text)),'{errorCode}',to_jsonb('MEDIA_SUBMIT_UNKNOWN_CHARGE_STATE'::text)),'{updatedAt}',to_jsonb($1::text)),updated_at=$1 where state='SUBMITTING' and provider_task_id is null and lease_expires_at < $1`,[now]);
    const selected=await client.query<PayloadRow<MediaGenerationJob>>(`select payload from media_generation_jobs_v2 where state=any($1::text[]) and (lease_expires_at is null or lease_expires_at<$2) order by created_at for update skip locked limit 1`,[eligibleStates,now]);if(!selected.rowCount)return undefined;
    const token=randomBytes(32).toString('base64url');const tokenHash=digest(token);const expiresAt=new Date(now.getTime()+leaseMs).toISOString();const claimed=claimMediaGenerationJob(json(selected.rows[0]!.payload),{leaseOwner:workerId,leaseTokenHash:tokenHash,leaseExpiresAt:expiresAt,claimedAt:now.toISOString()});await saveJob(client,claimed);const specResult=await client.query<PayloadRow<MediaGenerationSpec>>('select payload from media_generation_specs_v2 where owner_profile_id=$1 and id=$2',[claimed.ownerId,claimed.specId]);return {job:claimed,spec:json(specResult.rows[0]!.payload),leaseToken:token};
  });}

  public async heartbeat(workerId:string,jobId:string,leaseToken:string,leaseMs:number,now:Date){return this.tx(async(client)=>{const job=await lockedJob(client,jobId);assertLease(job,workerId,leaseToken,now);const next=heartbeatMediaGenerationJob(job,{leaseOwner:workerId,leaseTokenHash:digest(leaseToken),leaseExpiresAt:new Date(now.getTime()+leaseMs).toISOString(),observedAt:now.toISOString()});await saveJob(client,next);return next;});}
  public async persistSubmissionIntent(workerId:string,jobId:string,leaseToken:string,leaseMs:number,now:Date){return this.tx(async(client)=>{const job=await lockedJob(client,jobId);assertLease(job,workerId,leaseToken,now);const next=recordProviderSubmissionIntent(job,{leaseOwner:workerId,leaseTokenHash:digest(leaseToken),leaseExpiresAt:new Date(now.getTime()+leaseMs).toISOString(),recordedAt:now.toISOString()});await client.query('insert into media_provider_submission_intents_v2(owner_profile_id,job_id,attempt_number,request_digest,intent_digest,lease_token_hash,payload,created_at) values($1,$2,$3,$4,$5,$6,$7,$8)',[next.ownerId,next.id,next.attemptCount,next.requestDigest,next.submissionIntentDigest,next.leaseTokenHash,{jobId:next.id,requestDigest:next.requestDigest,intentDigest:next.submissionIntentDigest,attemptNumber:next.attemptCount},now]);await saveJob(client,next);return next;});}
  public async persistSubmissionOutcome(workerId:string,jobId:string,leaseToken:string,outcome:ProviderSubmissionOutcome,now:Date){return this.tx(async(client)=>{const job=await lockedJob(client,jobId);assertLease(job,workerId,leaseToken,now);const next=applyProviderSubmissionOutcome(job,outcome);await saveJob(client,next);return next;});}
  public async persistTaskObservation(workerId:string,jobId:string,leaseToken:string,observation:ProviderTaskObservation,now:Date){return this.tx(async(client)=>{const job=await lockedJob(client,jobId);assertLease(job,workerId,leaseToken,now);const next=applyProviderTaskObservation(job,observation);const receipt={jobId,providerTaskId:observation.providerTaskRef,state:observation.state,providerUsageDigest:observation.providerUsageDigest??null,observedAt:observation.observedAt};const receiptDigest=sha256Digest(receipt);await client.query('insert into media_provider_task_receipts_v2(owner_profile_id,id,job_id,provider_task_id,observation_state,provider_usage_digest,canonical_digest,private_evidence_ref,payload,observed_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) on conflict(owner_profile_id,job_id,canonical_digest) do nothing',[job.ownerId,`task-receipt-${receiptDigest.slice(0,24)}`,jobId,observation.providerTaskRef,observation.state,observation.providerUsageDigest??null,receiptDigest,'private-evidence://media-provider/redacted',receipt,observation.observedAt]);await saveJob(client,next);return next;});}

  public async stageBlob(ownerId:string,jobId:string,stage:MediaBlobStage['stage'],blobRef:MediaBlobRef,metadata:unknown,now:Date){const value:MediaBlobStage={ownerId,jobId,stage,contentDigest:blobRef.digest,blobRef,state:'STAGED',createdAt:now.toISOString(),committedAt:null};await this.#pool.query(`insert into media_blob_staging_v1(owner_profile_id,job_id,stage,content_digest,blob_ref,state,payload,created_at) values($1,$2,$3,$4,$5,'STAGED',$6,$7) on conflict(owner_profile_id,job_id,stage,content_digest) do nothing`,[ownerId,jobId,stage,blobRef.digest,blobRef,{...value,metadata},now]);return value;}
  public async commitRawPipeline(ownerId:string,jobId:string,cost:CostReceipt,rights:RightsReceipt,asset:RawProviderMediaAssetV2,now:Date){await this.tx(async(client)=>{const job=await lockedJob(client,jobId,ownerId);if(!['DOWNLOADING','VERIFYING'].includes(job.state))throw new MediaContractError('MEDIA_JOB_STATE_INVALID');await client.query('insert into media_cost_receipts_v2(owner_profile_id,id,job_id,state,canonical_digest,payload,created_at) values($1,$2,$3,$4,$5,$6,$7) on conflict(owner_profile_id,job_id,canonical_digest) do nothing',[ownerId,`cost-${cost.canonicalDigest.slice(0,24)}`,jobId,cost.state,cost.canonicalDigest,cost,now]);await client.query('insert into media_rights_receipts_v2(owner_profile_id,id,job_id,canonical_digest,payload,created_at) values($1,$2,$3,$4,$5,$6) on conflict(owner_profile_id,job_id,canonical_digest) do nothing',[ownerId,`rights-${rights.canonicalDigest.slice(0,24)}`,jobId,rights.canonicalDigest,rights,now]);await client.query(`insert into media_raw_assets_v2(owner_profile_id,id,job_id,spec_id,spec_digest,position,content_digest,blob_ref,cost_receipt_digest,rights_receipt_digest,canonical_digest,payload,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) on conflict(owner_profile_id,job_id) do nothing`,[ownerId,asset.id,jobId,asset.generationSpecId,asset.generationSpecDigest,asset.position,asset.contentDigest,asset.blobRef,asset.costReceiptDigest,asset.rightsReceiptDigest,asset.canonicalDigest,asset,now]);await client.query(`update media_blob_staging_v1 set state='COMMITTED',committed_at=$1,payload=jsonb_set(jsonb_set(payload,'{state}',to_jsonb('COMMITTED'::text)),'{committedAt}',to_jsonb($2::text)) where owner_profile_id=$3 and job_id=$4 and stage='RAW_BLOB_WRITTEN' and content_digest=$5`,[now,now.toISOString(),ownerId,jobId,asset.contentDigest]);const verifying=job.state==='DOWNLOADING'?advanceMediaGenerationJob(job,{state:'VERIFYING',observedAt:now.toISOString()}):job;await saveJob(client,advanceMediaGenerationJob(verifying,{state:'COMPOSING',observedAt:now.toISOString()}));});}
  public async commitFinalPipeline(ownerId:string,jobId:string,composition:MediaCompositionSpecV1,asset:CompositedMediaAssetV2,now:Date){await this.tx(async(client)=>{const job=await lockedJob(client,jobId,ownerId);if(job.state!=='COMPOSING')throw new MediaContractError('MEDIA_JOB_STATE_INVALID');await client.query(`insert into media_composition_specs_v1(owner_profile_id,id,raw_asset_id,raw_content_digest,brand_snapshot_digest,knowledge_snapshot_digest,canonical_digest,payload,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9) on conflict(owner_profile_id,id) do nothing`,[ownerId,composition.id,composition.rawAssetId,composition.rawContentDigest,composition.brandSnapshotDigest,composition.knowledgeSnapshotDigest,composition.canonicalDigest,composition,now]);await client.query(`insert into media_composited_assets_v2(owner_profile_id,id,raw_asset_id,composition_spec_id,composition_spec_digest,position,content_digest,blob_ref,canonical_digest,payload,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) on conflict(owner_profile_id,composition_spec_id,content_digest) do nothing`,[ownerId,asset.id,asset.rawAssetId,composition.id,composition.canonicalDigest,asset.position,asset.contentDigest,asset.blobRef,asset.canonicalDigest,asset,now]);await client.query(`update media_blob_staging_v1 set state='COMMITTED',committed_at=$1,payload=jsonb_set(jsonb_set(payload,'{state}',to_jsonb('COMMITTED'::text)),'{committedAt}',to_jsonb($2::text)) where owner_profile_id=$3 and job_id=$4 and stage='FINAL_BLOB_WRITTEN' and content_digest=$5`,[now,now.toISOString(),ownerId,jobId,asset.contentDigest]);await saveJob(client,advanceMediaGenerationJob(job,{state:'READY_FOR_REVIEW',observedAt:now.toISOString()}));});}

  public async appendRevision(ownerId:string,value:ArtifactRevisionV4,now:Date){await this.tx(async(client)=>{await client.query(`insert into artifact_revisions_v4(owner_profile_id,id,parent_revision_id,parent_revision_digest,revision,media_set_digest,brand_snapshot_digest,knowledge_snapshot_digest,canonical_digest,payload,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[ownerId,value.id,value.parentRevisionId,value.parentRevisionDigest,value.revision,value.mediaSetBinding.canonicalDigest,value.brandSnapshot.digest,value.knowledgeSnapshot.digest,value.canonicalDigest,value,now]);for(const item of value.mediaSetBinding.items)await client.query(`insert into media_set_items_v1(owner_profile_id,artifact_revision_id,artifact_revision_digest,position,asset_id,asset_digest,content_digest) values($1,$2,$3,$4,$5,$6,$7)`,[ownerId,value.id,value.canonicalDigest,item.position,item.assetId,item.finalAssetDigest,item.contentDigest]);});return value;}
  public async appendAudit(ownerId:string,value:MediaAuditDecisionV4,now:Date){await this.#pool.query(`insert into artifact_audit_decisions_v4(owner_profile_id,id,artifact_revision_id,artifact_revision_digest,auditor_identity_id,result,canonical_digest,payload,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[ownerId,value.id,value.artifactRevisionId,value.artifactRevisionDigest,value.auditorIdentityId,value.result,value.canonicalDigest,value,now]);return value;}
  public async appendOwnerDecision(ownerId:string,value:MediaOwnerDecisionV4,now:Date){await this.#pool.query(`insert into artifact_owner_decisions_v4(owner_profile_id,id,artifact_revision_id,artifact_revision_digest,audit_decision_id,audit_decision_digest,result,canonical_digest,payload,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[ownerId,value.id,value.artifactRevisionId,value.artifactRevisionDigest,value.auditDecisionId,value.auditDecisionDigest,value.result,value.canonicalDigest,value,now]);return value;}
  public async appendPackage(ownerId:string,value:ManualPublishPackageV4,now:Date){await this.tx(async(client)=>{await client.query(`insert into manual_publish_packages_v4(owner_profile_id,id,artifact_revision_id,artifact_revision_digest,audit_decision_id,audit_decision_digest,owner_decision_id,owner_decision_digest,manifest_digest,external_state,payload,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,[ownerId,value.id,value.artifactRevisionId,value.artifactRevisionDigest,value.auditDecisionId,value.auditDecisionDigest,value.ownerDecisionId,value.ownerDecisionDigest,value.manifestDigest,value.externalState,value,now]);for(const file of value.binaryFiles)await client.query(`insert into manual_publish_package_files_v4(owner_profile_id,package_id,position,file_name,media_type,content_digest,byte_size,blob_ref,text_content) values($1,$2,$3,$4,$5,$6,$7,$8,null)`,[ownerId,value.id,file.position,file.fileName,file.mediaType,file.digest,file.bytes,file.blobRef]);for(const file of value.textFiles)await client.query(`insert into manual_publish_package_files_v4(owner_profile_id,package_id,position,file_name,media_type,content_digest,byte_size,blob_ref,text_content) values($1,$2,$3,$4,$5,$6,$7,null,$8)`,[ownerId,value.id,file.position,file.fileName,file.mediaType,file.digest,file.bytes,file.content]);});return value;}
  public async appendInvalidation(ownerId:string,value:MediaGovernanceInvalidation,now:Date){await this.#pool.query(`insert into media_invalidation_events_v1(owner_profile_id,id,artifact_revision_id,artifact_revision_digest,reason_code,current_digest,canonical_digest,payload,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9) on conflict(owner_profile_id,artifact_revision_id,reason_code,current_digest) do nothing`,[ownerId,value.id,value.artifactRevisionId,value.artifactRevisionDigest,value.reasonCode,value.currentDigest,value.canonicalDigest,value,now]);return value;}

  private async tx<T>(fn:(client:PoolClient)=>Promise<T>):Promise<T>{const client=await this.#pool.connect();try{await client.query('begin');const value=await fn(client);await client.query('commit');return value;}catch(error){await client.query('rollback');throw error;}finally{client.release();}}
}

function digest(value:string){return createHash('sha256').update(value).digest('hex');}
function json<T>(value:T|string):T{return typeof value==='string'?JSON.parse(value) as T:value;}
function jobValues(job:MediaGenerationJob){return [job.ownerId,job.id,job.specId,job.specDigest,job.artifactRevisionDigest,job.imageSpecPosition,job.generation,job.requestDigest,job.state,job.providerAdapterRef,job.providerTaskId,job.leaseOwner,job.leaseTokenHash,job.leaseExpiresAt,job.attemptCount,job.errorCode,job,job.createdAt,job.updatedAt];}
async function lockedJob(client:PoolClient,jobId:string,ownerId?:string){const params=ownerId?[jobId,ownerId]:[jobId];const result=await client.query<PayloadRow<MediaGenerationJob>>(`select payload from media_generation_jobs_v2 where id=$1${ownerId?' and owner_profile_id=$2':''} for update`,params);if(!result.rowCount)throw new MediaContractError('MEDIA_JOB_STATE_INVALID');return json(result.rows[0]!.payload);}
function assertLease(job:MediaGenerationJob,workerId:string,token:string,now:Date){if(job.leaseOwner!==workerId||job.leaseTokenHash!==digest(token)||job.leaseExpiresAt===null||Date.parse(job.leaseExpiresAt)<now.getTime())throw new MediaContractError('MEDIA_LEASE_LOST');}
async function saveJob(client:PoolClient,job:MediaGenerationJob){await client.query(`update media_generation_jobs_v2 set state=$1,provider_task_id=$2,lease_owner=$3,lease_token_hash=$4,lease_expires_at=$5,attempt_count=$6,error_code=$7,payload=$8,updated_at=$9 where owner_profile_id=$10 and id=$11`,[job.state,job.providerTaskId,job.leaseOwner,job.leaseTokenHash,job.leaseExpiresAt,job.attemptCount,job.errorCode,job,job.updatedAt,job.ownerId,job.id]);}
