import {PersistentRuntimeError,runtimeGatewayInputProjection,runtimeGatewayPolicy,runtimeGatewayRequestDigest,sha256Digest,type MissionBundle,type ModelGatewayTicketClaims,type ModelGatewayTicketRepository,type ModelGatewayTicketUseOutcome,type RuntimeTaskContract} from '@lumiclaw/domain';
import {Pool,type PoolClient} from 'pg';

export class PostgresModelGatewayTicketRepository implements ModelGatewayTicketRepository{
  readonly #pool:Pool;
  public constructor(connectionString:string){this.#pool=new Pool({connectionString,max:4});this.#pool.on('error',(error)=>console.error('PostgreSQL model-gateway ticket idle client error',error.message));}
  public async health():Promise<boolean>{const result=await this.#pool.query<{exists:boolean}>("select to_regclass('public.model_gateway_tickets_v1') is not null and to_regclass('public.model_gateway_ticket_uses_v1') is not null as exists");return result.rows[0]?.exists===true;}
  public async issue(claims:ModelGatewayTicketClaims,ticketDigest:string,now:Date):Promise<void>{validateClaims(claims,ticketDigest,now,false);const client=await this.#pool.connect();try{await client.query('begin');await lockLineage(client,claims);const lineage=await activeLineage(client,claims,now);if(lineage===undefined||!validActiveLineage(lineage,claims,now))throw new PersistentRuntimeError('JOB_LEASE_LOST','MODEL_TICKET_ACTIVE_LEASE_REQUIRED');const prior=await client.query('select 1 from model_gateway_tickets_v1 where owner_profile_id=$1 and run_id=$2 and job_id=$3 and attempt_id=$4 and phase=$5',[claims.ownerId,claims.runId,claims.jobId,claims.attemptId,claims.phase]);if(prior.rows[0]!==undefined)throw new PersistentRuntimeError('MODEL_TICKET_REPLAYED','ONE_TICKET_PER_ATTEMPT_PHASE');const publicClaims=safeClaims(claims);await client.query(`insert into model_gateway_tickets_v1(ticket_digest,owner_profile_id,run_id,job_id,task_id,attempt_id,attempt_number,runtime_task_id,runtime_actor_id,worker_id_digest,lease_token_digest,phase,model,policy_digest,input_digest,request_digest,output_schema,nonce_digest,expires_at,public_claims,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21)`,[ticketDigest,claims.ownerId,claims.runId,claims.jobId,claims.taskId,claims.attemptId,claims.attemptNumber,claims.runtimeTaskId,claims.runtimeActorId,claims.workerIdDigest,claims.leaseTokenDigest,claims.phase,claims.model,claims.policyDigest,claims.inputDigest,claims.requestDigest,claims.outputSchema,sha256Digest(claims.nonce),new Date(claims.expiresAt),JSON.stringify(publicClaims),now]);await client.query('commit');}catch(error){await rollback(client);throw error;}finally{client.release();}}
  public async consume(claims:ModelGatewayTicketClaims,ticketDigest:string,now:Date):Promise<ModelGatewayTicketUseOutcome>{validateClaims(claims,ticketDigest,now,true);const client=await this.#pool.connect();try{await client.query('begin');await lockTicket(client,ticketDigest);await lockLineage(client,claims);const ticket=await client.query<{owner_profile_id:string;run_id:string;job_id:string;task_id:string;attempt_id:string;runtime_task_id:string;runtime_actor_id:string;worker_id_digest:string;lease_token_digest:string;expires_at:Date;public_claims:unknown}>('select * from model_gateway_tickets_v1 where ticket_digest=$1 for update',[ticketDigest]);const row=ticket.rows[0];if(row===undefined){await client.query('commit');return 'REJECTED';}const publicClaims=safeClaims(claims);if(row.owner_profile_id!==claims.ownerId||row.run_id!==claims.runId||row.job_id!==claims.jobId||row.task_id!==claims.taskId||row.attempt_id!==claims.attemptId||row.runtime_task_id!==claims.runtimeTaskId||row.runtime_actor_id!==claims.runtimeActorId||row.worker_id_digest.trim()!==claims.workerIdDigest||row.lease_token_digest.trim()!==claims.leaseTokenDigest||sha256Digest(row.public_claims)!==sha256Digest(publicClaims)){await this.appendUse(client,row,ticketDigest,'REJECTED',publicClaims,now);await client.query('commit');return 'REJECTED';}if(row.expires_at.getTime()<=now.getTime()){await this.appendUse(client,row,ticketDigest,'EXPIRED',publicClaims,now);await client.query('commit');return 'EXPIRED';}const lineage=await activeLineage(client,claims,now);if(lineage===undefined||!validActiveLineage(lineage,claims,now)){await this.appendUse(client,row,ticketDigest,'REJECTED',publicClaims,now);await client.query('commit');return 'REJECTED';}const used=await client.query('select 1 from model_gateway_ticket_uses_v1 where ticket_digest=$1 and outcome=\'USED\' limit 1',[ticketDigest]);if(used.rows[0]!==undefined){await this.appendUse(client,row,ticketDigest,'REPLAYED',publicClaims,now);await client.query('commit');return 'REPLAYED';}await this.appendUse(client,row,ticketDigest,'USED',publicClaims,now);await client.query('commit');return 'USED';}catch(error){await rollback(client);throw error;}finally{client.release();}}
  public async close():Promise<void>{await this.#pool.end();}
  private async appendUse(client:PoolClient,row:{owner_profile_id:string;run_id:string;job_id:string;task_id:string;attempt_id:string;runtime_actor_id:string},ticketDigest:string,outcome:ModelGatewayTicketUseOutcome,publicClaims:unknown,now:Date){await client.query('insert into model_gateway_ticket_uses_v1(ticket_digest,owner_profile_id,run_id,job_id,task_id,attempt_id,runtime_actor_id,outcome,occurred_at,public_claims) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[ticketDigest,row.owner_profile_id,row.run_id,row.job_id,row.task_id,row.attempt_id,row.runtime_actor_id,outcome,now,JSON.stringify(publicClaims)]);}
}
type ActiveLineage={
  attempt_count:number; attempt_input_digest:string; attempt_lease_token_hash:string; attempt_number:number; attempt_runtime_actor_id:string|null; attempt_runtime_task_id:string|null; attempt_schema_ref:string; attempt_state:string;
  binding_state:string|null; bundle_payload:unknown; contract_payload:unknown; job_lease_expires_at:Date|null; job_lease_owner:string|null; job_lease_token_hash:string|null; job_runtime_task_id:string|null; job_state:string; member_bindings:unknown; role_id:string;
};
async function activeLineage(client:PoolClient,claims:ModelGatewayTicketClaims,now:Date):Promise<ActiveLineage|undefined>{
  const result=await client.query<ActiveLineage>(`select j.state job_state,j.role_id,j.attempt_count,j.runtime_task_id job_runtime_task_id,j.lease_owner job_lease_owner,j.lease_token_hash job_lease_token_hash,j.lease_expires_at job_lease_expires_at,j.contract_payload,a.attempt_number,a.runtime_task_id attempt_runtime_task_id,a.runtime_actor_id attempt_runtime_actor_id,a.input_digest attempt_input_digest,a.schema_ref attempt_schema_ref,a.lease_token_hash attempt_lease_token_hash,a.state attempt_state,b.state binding_state,b.member_bindings,r.bundle_payload
    from mission_jobs_v1 j
    join agent_task_attempts_v1 a on a.owner_profile_id=j.owner_profile_id and a.run_id=j.run_id and a.job_id=j.id
    join runtime_bindings_v1 b on b.owner_profile_id=j.owner_profile_id and b.run_id=j.run_id
    join mission_runs_v1 r on r.owner_profile_id=j.owner_profile_id and r.id=j.run_id
    where j.owner_profile_id=$1 and j.run_id=$2 and j.id=$3 and j.task_contract_id=$4 and a.id=$5 and j.lease_expires_at>$6
    for update of j,a,b`,[claims.ownerId,claims.runId,claims.jobId,claims.taskId,claims.attemptId,now]);
  return result.rows[0];
}
function validActiveLineage(row:ActiveLineage,claims:ModelGatewayTicketClaims,now:Date):boolean{
  const memberBindings=Array.isArray(row.member_bindings)?row.member_bindings:[];
  const boundActor=memberBindings.find((value):value is {roleId:string;runtimeActorId:string}=>isActorBinding(value)&&value.roleId===row.role_id)?.runtimeActorId;
  let requestAndPolicyMatch=false;try{const contract=json<RuntimeTaskContract>(row.contract_payload);const bundle=json<MissionBundle>(row.bundle_payload);const projection=runtimeGatewayInputProjection(bundle,contract);const policy=runtimeGatewayPolicy(contract,claims.phase,claims.model);requestAndPolicyMatch=runtimeGatewayRequestDigest({ownerId:claims.ownerId,runId:claims.runId,jobId:claims.jobId,taskId:claims.taskId,attemptId:claims.attemptId,attemptNumber:claims.attemptNumber,runtimeTaskId:claims.runtimeTaskId,runtimeActorId:claims.runtimeActorId,workerIdDigest:claims.workerIdDigest,leaseTokenDigest:claims.leaseTokenDigest,phase:claims.phase,model:claims.model,policyDigest:policy.digest,inputDigest:contract.inputDigest,outputSchemaRef:contract.outputSchema,system:policy.system,input:projection,outputSchema:policy.outputSchema})===claims.requestDigest&&policy.digest===claims.policyDigest&&contract.outputSchema===claims.outputSchema&&contract.inputDigest===claims.inputDigest;}catch{return false;}
  return requestAndPolicyMatch&&row.job_state==='ACKNOWLEDGED'&&row.attempt_state==='ACKNOWLEDGED'&&row.attempt_number===claims.attemptNumber&&row.attempt_count===claims.attemptNumber&&row.attempt_input_digest.trim()===claims.inputDigest&&row.attempt_schema_ref===claims.outputSchema&&row.job_runtime_task_id!==null&&row.job_runtime_task_id===claims.runtimeTaskId&&row.job_runtime_task_id===row.attempt_runtime_task_id&&row.attempt_runtime_actor_id!==null&&row.attempt_runtime_actor_id===claims.runtimeActorId&&row.attempt_runtime_actor_id===boundActor&&row.binding_state==='BOUND'&&row.job_lease_owner!==null&&sha256Digest(row.job_lease_owner)===claims.workerIdDigest&&row.job_lease_token_hash!==null&&row.job_lease_token_hash.trim()===claims.leaseTokenDigest&&row.job_lease_token_hash.trim()===row.attempt_lease_token_hash.trim()&&row.attempt_lease_token_hash.trim()===claims.leaseTokenDigest&&row.job_lease_expires_at!==null&&row.job_lease_expires_at.getTime()>now.getTime()&&Date.parse(claims.expiresAt)<=row.job_lease_expires_at.getTime();
}
function isActorBinding(value:unknown):value is {roleId:string;runtimeActorId:string}{return value!==null&&typeof value==='object'&&!Array.isArray(value)&&typeof (value as {roleId?:unknown}).roleId==='string'&&typeof (value as {runtimeActorId?:unknown}).runtimeActorId==='string';}
function safeClaims(claims:ModelGatewayTicketClaims){const {nonce,...rest}=claims;return {...rest,nonceDigest:sha256Digest(nonce)};}
function validateClaims(claims:ModelGatewayTicketClaims,ticketDigest:string,now:Date,allowExpired:boolean){if(!/^[a-f0-9]{64}$/u.test(ticketDigest)||claims.schemaVersion!==1||claims.runtimeTaskId.length===0||claims.runtimeActorId.length===0||!/^[a-f0-9]{64}$/u.test(claims.workerIdDigest)||!/^[a-f0-9]{64}$/u.test(claims.leaseTokenDigest)||!['ORCHESTRATE','CLAIM','PLAN','PRODUCE','AUDIT'].includes(claims.phase)||!['deepseek-v4-flash','deepseek-v4-pro'].includes(claims.model)||!/^[a-f0-9]{64}$/u.test(claims.policyDigest)||!/^[a-f0-9]{64}$/u.test(claims.inputDigest)||!/^[a-f0-9]{64}$/u.test(claims.requestDigest)||claims.nonce.length<32||Number.isNaN(Date.parse(claims.expiresAt))||(!allowExpired&&Date.parse(claims.expiresAt)<=now.getTime()))throw new PersistentRuntimeError('SUBMISSION_SCHEMA_INVALID','MODEL_TICKET_CLAIMS_INVALID');}
async function lockTicket(client:PoolClient,digest:string){await client.query('select pg_advisory_xact_lock(hashtextextended($1,0))',[`MODEL_TICKET:${digest}`]);}
async function lockLineage(client:PoolClient,claims:ModelGatewayTicketClaims){await client.query('select pg_advisory_xact_lock(hashtextextended($1,0))',[`MODEL_TICKET_LINEAGE:${claims.ownerId}:${claims.runId}:${claims.jobId}:${claims.attemptId}:${claims.phase}`]);}
function json<T>(value:unknown):T{return (typeof value==='string'?JSON.parse(value):value) as T;}
async function rollback(client:PoolClient){try{await client.query('rollback');}catch{}}
