import {describe,expect,it} from 'vitest';
import {createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {
  artifactProfiles,artifactSkills,auditCheckCodes,buildManualPublishPackage,createArtifactAuditDecision,createArtifactInvalidation,
  createArtifactOwnerDecision,createArtifactRevision,createOwnerEditRevision,effectiveArtifactState,expectedArtifactBindings,
  officialPublishUrlRegistry,quarantineProducerSubmission,recordPackageHelperEvent,sanitizeOfficialPublishUrlRef,sha256Digest,
  verifyManualPublishPackage,weightedXLength,type ArtifactPayload,type ArtifactWorkspace,type AuditFinding,type MissionExecutionBundle,type ProducerSubmission
} from './index.js';

const digest=(value:string)=>sha256Digest(value);
const owner='owner-public-safe';

function bundle(platform:'X'|'XIAOHONGSHU'='X'):MissionExecutionBundle{
  const unit={activationUnitId:`unit-${platform.toLowerCase()}`,slotId:'slot-1',localDate:'2026-08-23',localTime:'09:00',platformCode:platform,accountProfileRevisionId:`account-${platform.toLowerCase()}`,producerRole:'founder-identity-producer' as const,contentObjective:'Share an evidence-bound release note.',sourceItemIds:['source-1','source-2'],claimConstraints:['Do not claim external publication.']};
  const inputBindings={knowledgeSnapshot:{id:'snapshot-1',digest:digest('snapshot'),state:'APPROVED' as const},operatingGoal:{id:'goal-1',revision:2,digest:digest('goal'),state:'ACTIVE' as const},accountProfiles:[{accountProfileRevisionId:unit.accountProfileRevisionId,revision:1,digest:digest(`account-${platform}`),platformCode:platform,handleOrDisplayName:'@public-safe',producerMandates:['FOUNDER_VOICE' as const,'PRODUCT_EXPERTISE' as const],targetMarket:platform==='X'?'US':'CN',contentLocale:platform==='X'?'en-US':'zh-CN'}],compiler:{version:'selected-platform-compiler.v2',digest:digest('compiler')},teamProfile:{id:'team',version:'2',digest:digest('team'),runtimeCompatibility:'agentteams-v1.2.0'},plannerOutputSchema:{id:'lumiclaw.content-plan.v2' as const,digest:digest('schema')},approvedPlan:{id:'plan-1',revision:2,digest:digest('plan')}};
  const base={schemaVersion:2 as const,kind:'MISSION_EXECUTION' as const,missionIntentId:'mission-1',ownerId:owner,bundleId:`bundle-${platform.toLowerCase()}`,generation:2,parentBundleId:'intent-1',parentBundleDigest:digest('intent'),approvedPlanId:'plan-1',approvedPlanRevision:2,approvedPlanDigest:digest('plan'),state:'COMPILED' as const,compilerVersion:'selected-platform-compiler.v2',inputBindings,roles:[],roleContexts:[],skillLocks:[],selectedPlatforms:[platform],activationUnits:[unit],currentBrief:{briefId:'brief-1',slotId:'slot-1',platformCode:platform,accountProfileRevisionId:unit.accountProfileRevisionId,producerRole:unit.producerRole,theme:'Release',contentObjective:unit.contentObjective,sourceItemIds:unit.sourceItemIds,claimConstraints:unit.claimConstraints},tasks:[],dependencyDag:[],expectedArtifactSchemas:[{platformCode:platform,schemaRef:`lumiclaw.artifact.${platform.toLowerCase()}.v3`,contractStatus:'SDD_010_REQUIRED' as const}],trace:[],evidenceContract:{agentTeamsExecuted:false as const,fixtureAllowed:true as const,externalActionAllowed:false as const}};
  return {...base,canonicalDigest:sha256Digest(base)};
}

function xPayload(mode:'SINGLE'|'THREAD'='SINGLE'):ArtifactPayload{
  const posts=mode==='SINGLE'?[{position:1,text:'LumiClaw now preserves exact evidence bindings before review.',mediaRefs:[],altText:null}]:[
    {position:1,text:'A governed release starts with exact evidence.',mediaRefs:[],altText:null},{position:2,text:'An independent auditor checks every revision.',mediaRefs:[],altText:null},{position:3,text:'The owner approves the exact package. No auto-publish.',mediaRefs:[],altText:null}
  ];return {kind:'X',mode,posts,link:'https://lumiclaw.org/',cta:'Review the public architecture.',language:'en-US',accountProfileRevisionId:'account-x',sourceBindings:sourceBindings()};
}
function xhsPayload():ArtifactPayload{return {kind:'XIAOHONGSHU',title:'一次真正可审阅的内容发布链路',body:'完整内容、来源、账号和计划被锁定后，独立审校才开始。当前图片只是规格，并未生成。',topics:['AI创业','品牌出海'],cta:'查看完整证据链',coverSpec:{purpose:'解释治理链路',aspectRatio:'3:4',visualBrief:'米白底上的四段证据链，不使用真实平台截图。',overlayCopy:'先审校，再交付'},imageSpecs:[{position:1,purpose:'封面',aspectRatio:'3:4',visualBrief:'显示 revision → audit → owner → package',overlayCopy:'完整内容可审阅',altDescription:'四阶段治理链路示意',authorizedMediaRef:null},{position:2,purpose:'来源追踪',aspectRatio:'3:4',visualBrief:'展示公开安全来源卡片和摘要锁。',overlayCopy:null,altDescription:'来源与摘要绑定示意',authorizedMediaRef:null}],language:'zh-CN',accountProfileRevisionId:'account-xiaohongshu',sourceBindings:sourceBindings()};}
function sourceBindings(){return ['source-1','source-2'].map((sourceItemId)=>({sourceItemId,bindingDigest:sha256Digest({knowledgeSnapshotDigest:digest('snapshot'),sourceItemId})}));}
function submission(current:MissionExecutionBundle,payload:ArtifactPayload):ProducerSubmission{const unit=current.activationUnits[0]!;return {schemaVersion:3,evidenceMaturity:'CONTROLLED_FIXTURE',agentTeamsExecuted:false,submissionId:`submission-${payload.kind.toLowerCase()}`,activationUnitId:unit.activationUnitId,producerRole:unit.producerRole,producerIdentityId:'producer-a3',inputBindings:expectedArtifactBindings(current,unit),payload,submittedAt:'2026-08-23T01:00:00.000Z'};}
function passFindings():AuditFinding[]{return auditCheckCodes.map((checkCode)=>({checkCode,result:'PASS',path:'/',message:`${checkCode} passed against exact bindings.`,evidenceBindings:[digest(checkCode)],recoveryAction:null}));}
function chain(current=bundle('X'),payload=xPayload()){
  const revision=createArtifactRevision({ownerId:owner,submission:submission(current,payload),bundle:current,revision:1,parentRevisionId:null,createdAt:'2026-08-23T01:00:00.000Z'});
  const audit=createArtifactAuditDecision({ownerId:owner,revision,auditorIdentityId:'auditor-a5',result:'PASS',findings:passFindings(),evidenceBindings:[revision.inputBindings.knowledgeSnapshot.digest],createdAt:'2026-08-23T01:01:00.000Z'});
  const decision=createArtifactOwnerDecision({ownerId:owner,revision,audit,result:'APPROVE',ownerIdentityId:owner,decidedAt:'2026-08-23T01:02:00.000Z'});return {revision,audit,decision};
}

describe('SDD-010 artifact contracts',()=>{
  it.each(['SINGLE','THREAD'] as const)('validates and freezes X %s with deterministic digest',(mode)=>{const current=bundle('X');const first=createArtifactRevision({ownerId:owner,submission:submission(current,xPayload(mode)),bundle:current,revision:1,parentRevisionId:null,createdAt:'2026-08-23T01:00:00.000Z'});const second=createArtifactRevision({ownerId:owner,submission:submission(current,xPayload(mode)),bundle:current,revision:1,parentRevisionId:null,createdAt:'2026-08-23T01:00:00.000Z'});expect(second).toEqual(first);expect(first.payload.kind).toBe('X');if(first.payload.kind==='X')expect(first.payload.posts.map((post)=>post.position)).toEqual(mode==='SINGLE'?[1]:[1,2,3]);});
  it('validates complete XHS title/body/topics/cover/ordered image specs without pretending images exist',()=>{const current=bundle('XIAOHONGSHU');const revision=createArtifactRevision({ownerId:owner,submission:submission(current,xhsPayload()),bundle:current,revision:1,parentRevisionId:null,createdAt:'2026-08-23T01:00:00.000Z'});expect(revision.payload.kind).toBe('XIAOHONGSHU');if(revision.payload.kind==='XIAOHONGSHU'){expect(revision.payload.imageSpecs.map((item)=>item.position)).toEqual([1,2]);expect(revision.payload.imageSpecs.every((item)=>item.authorizedMediaRef===null)).toBe(true);}});
  it('uses registered, expiring profile and exact repository Skill locks',()=>{expect(artifactProfiles.X.source).toContain('x-platform-rule-pack');expect(artifactProfiles.XIAOHONGSHU.expiresAt).toBe('2026-09-21T16:30:00+08:00');expect(artifactSkills.X.license).toBe('Apache-2.0');expect(artifactSkills.AUDIT.id).toBe('artifact-independent-audit');for(const value of Object.values(artifactSkills)){const bytes=readFileSync(new URL(`../../../${value.source}`,import.meta.url));expect(createHash('sha256').update(bytes).digest('hex')).toBe(value.sourceDigest);}});
  it('applies the deterministic X URL weight and regular limit',()=>{expect(weightedXLength('See https://example.com/a/long/path today')).toBe(33);const payload=xPayload();if(payload.kind!=='X')throw new Error();payload.posts[0]!.text='a'.repeat(281);expect(()=>createArtifactRevision({ownerId:owner,submission:submission(bundle('X'),payload),bundle:bundle('X'),revision:1,parentRevisionId:null,createdAt:'2026-08-23T01:00:00.000Z'})).toThrowError(expect.objectContaining({code:'ARTIFACT_LENGTH_INVALID'}));});
  it.each([
    ['platform',()=>{const value=submission(bundle('X'),xPayload());value.payload=xhsPayload();return value;},'ARTIFACT_PLATFORM_NOT_SELECTED'],
    ['account',()=>{const value=submission(bundle('X'),xPayload());if(value.payload.kind==='X')value.payload.accountProfileRevisionId='wrong';return value;},'ARTIFACT_ACCOUNT_MISMATCH'],
    ['producer',()=>{const value=submission(bundle('X'),xPayload());value.producerRole='product-account-producer';return value;},'ARTIFACT_PRODUCER_MISMATCH'],
    ['source',()=>{const value=submission(bundle('X'),xPayload());value.payload.sourceBindings.pop();return value;},'ARTIFACT_SOURCE_MISMATCH'],
    ['source digest',()=>{const value=submission(bundle('X'),xPayload());value.payload.sourceBindings[0]!.bindingDigest=digest('tamper');return value;},'ARTIFACT_SOURCE_MISMATCH'],
    ['bundle',()=>{const value=submission(bundle('X'),xPayload());value.inputBindings.executionBundle={...value.inputBindings.executionBundle,digest:digest('tamper')};return value;},'ARTIFACT_INPUT_MISMATCH'],
    ['goal',()=>{const value=submission(bundle('X'),xPayload());value.inputBindings.operatingGoal={...value.inputBindings.operatingGoal,digest:digest('tamper')};return value;},'ARTIFACT_INPUT_MISMATCH'],
    ['plan',()=>{const value=submission(bundle('X'),xPayload());value.inputBindings.approvedPlan={...value.inputBindings.approvedPlan,digest:digest('tamper')};return value;},'ARTIFACT_INPUT_MISMATCH'],
    ['knowledge',()=>{const value=submission(bundle('X'),xPayload());value.inputBindings.knowledgeSnapshot={...value.inputBindings.knowledgeSnapshot,digest:digest('tamper')};return value;},'ARTIFACT_INPUT_MISMATCH'],
    ['skill',()=>{const value=submission(bundle('X'),xPayload());value.inputBindings.producerSkill={...value.inputBindings.producerSkill,digest:digest('tamper')};return value;},'ARTIFACT_INPUT_MISMATCH'],
    ['profile',()=>{const value=submission(bundle('X'),xPayload());value.inputBindings.artifactProfile={...value.inputBindings.artifactProfile,digest:digest('tamper')};return value;},'ARTIFACT_INPUT_MISMATCH']
  ] as const)('quarantines wrong %s binding',(_label,mutate,code)=>{const current=bundle('X');expect(quarantineProducerSubmission(mutate(),current,'2026-08-23T01:00:00.000Z')?.reasonCode).toBe(code);});
  it('fails closed on duplicate/gapped order and stale platform constraints',()=>{const current=bundle('X');const value=submission(current,xPayload('THREAD'));if(value.payload.kind!=='X')throw new Error();value.payload.posts[1]!.position=3;expect(quarantineProducerSubmission(value,current,'2026-08-23T01:00:00.000Z')?.reasonCode).toBe('ARTIFACT_ORDER_INVALID');const clean=submission(current,xPayload());expect(quarantineProducerSubmission(clean,current,'2026-09-21T16:31:00+08:00')?.reasonCode).toBe('PLATFORM_CONSTRAINT_STALE');});
  it('requires independent Auditor identity and complete PASS/FAIL/ESCALATE findings',()=>{const revision=chain().revision;expect(()=>createArtifactAuditDecision({ownerId:owner,revision,auditorIdentityId:'producer-a3',result:'PASS',findings:passFindings(),evidenceBindings:[],createdAt:'2026-08-23T01:01:00.000Z'})).toThrowError(expect.objectContaining({code:'AUDITOR_INDEPENDENCE_REQUIRED'}));const failed=passFindings();failed[1]={...failed[1]!,result:'FAIL',recoveryAction:'Bind an approved source.'};expect(createArtifactAuditDecision({ownerId:owner,revision,auditorIdentityId:'auditor-a5',result:'FAIL',findings:failed,evidenceBindings:[],createdAt:'2026-08-23T01:01:00.000Z'}).result).toBe('FAIL');const escalated=passFindings();escalated[6]={...escalated[6]!,result:'ESCALATE',recoveryAction:'Owner risk review.'};expect(createArtifactAuditDecision({ownerId:owner,revision,auditorIdentityId:'auditor-a5',result:'ESCALATE',findings:escalated,evidenceBindings:[],createdAt:'2026-08-23T01:01:00.000Z'}).result).toBe('ESCALATE');});
  it.each(['FAIL','ESCALATE'] as const)('blocks Owner approval and package after %s',(result)=>{const revision=chain().revision;const findings=passFindings();findings[0]={...findings[0]!,result,recoveryAction:'Revise or escalate.'};const audit=createArtifactAuditDecision({ownerId:owner,revision,auditorIdentityId:'auditor-a5',result,findings,evidenceBindings:[],createdAt:'2026-08-23T01:01:00.000Z'});expect(()=>createArtifactOwnerDecision({ownerId:owner,revision,audit,result:'APPROVE',ownerIdentityId:owner,decidedAt:'2026-08-23T01:02:00.000Z'})).toThrowError(expect.objectContaining({code:'AUDIT_PASS_REQUIRED'}));});
  it('creates an immutable Owner edit, requires re-audit, and invalidates old exact history',()=>{const first=chain();const payload=xPayload();if(payload.kind!=='X')throw new Error();payload.posts[0]!.text='Owner edited this exact revision; it must be audited again.';const edited=createOwnerEditRevision({ownerId:owner,ownerIdentityId:owner,base:first.revision,payload,revision:2,createdAt:'2026-08-23T02:00:00.000Z'});const invalidation=createArtifactInvalidation({ownerId:owner,artifactRevisionId:first.revision.id,reasonCode:'NEW_REVISION',previousDigest:first.revision.canonicalDigest,currentDigest:edited.canonicalDigest,createdAt:'2026-08-23T02:00:00.000Z'});const workspace:ArtifactWorkspace={revisions:[first.revision,edited],quarantines:[],audits:[first.audit],ownerDecisions:[first.decision],regenerationRequests:[],packages:[],helperEvents:[],invalidations:[invalidation]};expect(effectiveArtifactState(workspace,first.revision)).toBe('INVALIDATED');expect(effectiveArtifactState(workspace,edited)).toBe('AWAITING_AUDIT');expect(edited.parentRevisionId).toBe(first.revision.id);});
  it('rejects a stale audit/decision binding',()=>{const first=chain();const edited=createOwnerEditRevision({ownerId:owner,ownerIdentityId:owner,base:first.revision,payload:xPayload('THREAD'),revision:2,createdAt:'2026-08-23T02:00:00.000Z'});expect(()=>createArtifactOwnerDecision({ownerId:owner,revision:edited,audit:first.audit,result:'APPROVE',ownerIdentityId:owner,decidedAt:'2026-08-23T02:01:00.000Z'})).toThrowError(expect.objectContaining({code:'OWNER_DECISION_STALE'}));});
});

describe('SDD-010 deterministic ManualPublishPackage',()=>{
  it.each([['X',xPayload(),['manifest.json','content.md','post-01.txt','media-alt-manifest.json']],['XIAOHONGSHU',xhsPayload(),['manifest.json','title.txt','body.md','topics.txt','image-specs.json']]] as const)('builds exact ordered %s files with stable manifest',(platform,payload,names)=>{const first=chain(bundle(platform),payload);const a=buildManualPublishPackage({ownerId:owner,...first,createdAt:'2026-08-23T01:03:00.000Z'});const b=buildManualPublishPackage({ownerId:owner,...first,createdAt:'2026-08-23T01:03:00.000Z'});expect(a).toEqual(b);expect(a.orderedFiles.map((item)=>item.fileName)).toEqual(names);expect(a.orderedFiles.map((item)=>item.position)).toEqual(names.map((_item,index)=>index+1));expect(verifyManualPublishPackage(a)).toEqual({ok:true});expect(JSON.stringify(a)).not.toMatch(/\/Users\/|file:\/\/|password|cookie|secret/iu);});
  it('includes each X thread post in order',()=>{const value=chain(bundle('X'),xPayload('THREAD'));const pack=buildManualPublishPackage({ownerId:owner,...value,createdAt:'2026-08-23T01:03:00.000Z'});expect(pack.orderedFiles.map((item)=>item.fileName)).toEqual(['manifest.json','content.md','post-01.txt','post-02.txt','post-03.txt','media-alt-manifest.json']);});
  it('strips query/hash only for an allowlisted official path and blocks other hosts/expiry',()=>{const withQuery={...officialPublishUrlRegistry.X,url:'https://x.com/compose/post?text=secret#fragment'};expect(sanitizeOfficialPublishUrlRef(withQuery,'2026-08-23T01:00:00.000Z').url).toBe('https://x.com/compose/post');expect(()=>sanitizeOfficialPublishUrlRef({...withQuery,url:'https://evil.example/compose/post'},'2026-08-23T01:00:00.000Z')).toThrowError(expect.objectContaining({code:'OFFICIAL_URL_NOT_ALLOWLISTED'}));expect(()=>sanitizeOfficialPublishUrlRef(officialPublishUrlRegistry.XIAOHONGSHU,'2026-09-06T00:00:00.000Z')).toThrowError(expect.objectContaining({code:'PLATFORM_CONSTRAINT_STALE'}));});
  it.each(['COPY_TEXT','DOWNLOAD_PACKAGE','OPEN_OFFICIAL_PUBLISH_PAGE'] as const)('%s remains local EXPORTED/UNVERIFIED and never PUBLISHED',(action)=>{const value=chain();const pack=buildManualPublishPackage({ownerId:owner,...value,createdAt:'2026-08-23T01:03:00.000Z'});const event=recordPackageHelperEvent({ownerId:owner,value:pack,action,createdAt:'2026-08-23T01:04:00.000Z'});expect(event.state).toBe('EXPORTED');expect(event.externalState).toBe('UNVERIFIED_EXTERNAL_STATE');expect(JSON.stringify(event)).not.toContain('PUBLISHED');});
  it('detects file tampering',()=>{const value=chain();const pack=buildManualPublishPackage({ownerId:owner,...value,createdAt:'2026-08-23T01:03:00.000Z'});pack.orderedFiles[1]!.content='tampered';expect(verifyManualPublishPackage(pack)).toEqual({ok:false,code:'PACKAGE_DIGEST_MISMATCH'});});
});
