'use client';
/* eslint-disable @next/next/no-img-element -- authenticated content-addressed final previews must not pass through the Next image optimizer */

import type {ArtifactAuditDecision, ArtifactOwnerDecision, ArtifactPayload, ArtifactRevisionV3, ManualPublishPackage, MediaWorkspace, MissionExecutionBundle, XArtifactPayload, XiaohongshuArtifactPayload} from '@lumiclaw/domain';
import {Check, Clipboard, Download, ExternalLink, FileCheck2, GitCompareArrows, LockKeyhole, RefreshCw, ShieldCheck, TriangleAlert} from 'lucide-react';
import {useTranslations} from 'next-intl';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {StatusBadge} from '@/components/ui/status-badge';
import {auditArtifact,auditFinalMedia,bindFinalMedia,createControlledArtifact,createManualPublishPackage,decideArtifact,decideFinalMedia,editArtifact,loadGovernedMedia,loadMediaReadiness,packageFinalMedia,ProductApiError,recordPackageEvent,requestArtifactRegeneration,startMediaGeneration} from '@/lib/production-api';
import type {WorkspaceSnapshot} from '@/lib/production-types';

type Props={snapshot:WorkspaceSnapshot;onReload:()=>Promise<void>};
type Notice={tone:'ok'|'error';text:string}|null;

export function ArtifactPublishFeature({snapshot,onReload}:Props){
  const t=useTranslations('ArtifactPublish');const workspace=snapshot.artifacts??emptyWorkspace;const executions=snapshot.goals?.bundles.filter((bundle):bundle is MissionExecutionBundle=>bundle.kind==='MISSION_EXECUTION'&&snapshot.goals?.bundleStates.find((state)=>state.bundleId===bundle.bundleId)?.state!=='INVALIDATED').sort((left,right)=>right.generation-left.generation)??[];const execution=executions[0];
  const [selectedUnit,setSelectedUnit]=useState(execution?.activationUnits[0]?.activationUnitId??'');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState<Notice>(null);const [xMode,setXMode]=useState<'SINGLE'|'THREAD'>('THREAD');
  if(execution===undefined)return <Boundary title={t('noExecutionTitle')} body={t('noExecutionBody')} code="MISSION_EXECUTION_REQUIRED"/>;
  const unit=execution.activationUnits.find((item)=>item.activationUnitId===selectedUnit)??execution.activationUnits[0]!;const revisions=workspace.revisions.filter((item)=>item.activationUnitId===unit.activationUnitId).sort((left,right)=>right.revision-left.revision);const revision=revisions[0];const invalid=revision===undefined?false:workspace.invalidations.some((item)=>item.artifactRevisionId===revision.id);const audit=revision===undefined?undefined:[...workspace.audits].reverse().find((item)=>item.artifactRevisionId===revision.id&&item.artifactRevisionDigest===revision.canonicalDigest);const decision=audit===undefined?undefined:[...workspace.ownerDecisions].reverse().find((item)=>item.artifactRevisionId===audit.artifactRevisionId&&item.auditDecisionId===audit.id);const pack=decision===undefined?undefined:[...workspace.packages].reverse().find((item)=>item.artifactRevisionId===decision.artifactRevisionId&&item.ownerDecisionId===decision.id);const parent=revision?.parentRevisionId===null?undefined:workspace.revisions.find((item)=>item.id===revision?.parentRevisionId);
  const run=async(operation:()=>Promise<unknown>,success:string)=>{setBusy(true);setNotice(null);try{await operation();await onReload();setNotice({tone:'ok',text:success});}catch(error){setNotice({tone:'error',text:error instanceof ProductApiError?t('errorCode',{code:error.code}):t('unexpectedError')});}finally{setBusy(false);}};
  return <section className="lc-artifact-workbench" aria-busy={busy}>
    <header className="lc-artifact-boundary"><div><span className="lc-fixture-stamp">{t('fixtureStamp')}</span><strong>{t('fixtureTitle')}</strong><p>{t('fixtureBody')}</p></div><StatusBadge tone="warning">AgentTeams: NOT RUN</StatusBadge></header>
    <nav className="lc-artifact-rail" aria-label={t('unitsLabel')}>{execution.activationUnits.map((item)=>{const head=[...workspace.revisions].filter((candidate)=>candidate.activationUnitId===item.activationUnitId).sort((a,b)=>b.revision-a.revision)[0];return <button key={item.activationUnitId} type="button" data-active={String(item.activationUnitId===unit.activationUnitId)} onClick={()=>setSelectedUnit(item.activationUnitId)}><span className="lc-platform-mark">{item.platformCode==='X'?'X':'小红书'}</span><span><strong>{item.platformCode==='X'?'X / Twitter':'小红书'}</strong><small>{head===undefined?t('notGenerated'):t('revision',{number:head.revision})}</small></span><i data-ready={String(head!==undefined)}/></button>;})}</nav>
    {revision===undefined?<section className="lc-artifact-empty"><FileCheck2 size={30}/><h2>{t('generateTitle')}</h2><p>{t('generateBody')}</p>{unit.platformCode==='X'?<label className="lc-artifact-mode"><span>{t('xFormat')}</span><select value={xMode} onChange={(event)=>setXMode(event.target.value as 'SINGLE'|'THREAD')}><option value="SINGLE">SINGLE</option><option value="THREAD">THREAD</option></select></label>:<p className="lc-artifact-spec-note">{t('xhsMediaBoundary')}</p>}<Button variant="primary" disabled={busy} onClick={()=>run(()=>createControlledArtifact(execution,unit.activationUnitId,xMode),t('created'))}>{t('generateFixture')}</Button></section>:
      <div className="lc-artifact-main">
        <section className="lc-artifact-editor"><div className="lc-artifact-heading"><div><p className="lc-eyebrow">{t('completeArtifact')}</p><h2>{unit.platformCode==='X'?(revision.payload as XArtifactPayload).mode:'IMAGE_NOTE'} · {t('revision',{number:revision.revision})}</h2></div><div className="flex gap-2"><StatusBadge tone={invalid?'danger':audit?.result==='PASS'?'positive':audit?.result==='FAIL'?'danger':'warning'}>{invalid?t('invalidated'):audit===undefined?t('awaitingAudit'):audit.result}</StatusBadge><StatusBadge tone="info">{revision.origin}</StatusBadge></div></div>
          <ArtifactEditor key={revision.id} revision={revision} parent={parent} busy={busy||invalid} onSave={(payload)=>run(()=>editArtifact(revision,payload),t('newRevisionCreated'))} t={t}/>
          {revision.platformCode==='XIAOHONGSHU'?<GovernedMediaPanel revision={revision}/>:null}
          <Regenerate disabled={busy||invalid} onRequest={(reason)=>run(()=>requestArtifactRegeneration(revision,reason),t('regenerationCreated'))} t={t}/>
          <InputTrace revision={revision} t={t}/>
        </section>
        <aside className="lc-artifact-gates"><GateRail revision={revision} audit={audit} decision={decision} pack={pack} invalid={invalid} busy={busy} run={run} t={t}/></aside>
      </div>}
    <div className="lc-artifact-notice" aria-live="polite">{notice===null?null:<p data-tone={notice.tone}>{notice.tone==='ok'?<Check size={14}/>:<TriangleAlert size={14}/>} {notice.text}</p>}</div>
  </section>;
}

function GovernedMediaPanel({revision}:{revision:ArtifactRevisionV3}){
  const t=useTranslations('GovernedMedia');const [workspace,setWorkspace]=useState<MediaWorkspace|null>(null);const [readiness,setReadiness]=useState<Awaited<ReturnType<typeof loadMediaReadiness>>|null>(null);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);
  const reload=async()=>{const [media,gate]=await Promise.all([loadGovernedMedia(),loadMediaReadiness()]);setWorkspace(media.workspace);setReadiness(gate);};
  useEffect(()=>{let active=true;const refresh=()=>{void Promise.all([loadGovernedMedia(),loadMediaReadiness()]).then(([media,gate])=>{if(active){setWorkspace(media.workspace);setReadiness(gate);}}).catch((value:unknown)=>{if(active)setError(value instanceof ProductApiError?value.code:'MEDIA_CONTROL_PLANE_UNAVAILABLE');});};refresh();const timer=window.setInterval(refresh,1500);return()=>{active=false;window.clearInterval(timer);};},[revision.id]);
  const allJobs=workspace?.jobs.filter((value)=>value.artifactRevisionDigest===revision.canonicalDigest)??[];const jobs=latestJobs(allJobs);const assets=jobs.map((job)=>{const raw=workspace?.rawAssets.find((value)=>value.jobId===job.id);const final=workspace?.finalAssets.find((value)=>value.rawAssetId===raw?.id);return {job,raw,final};});const allFinal=jobs.length>0&&assets.every((value)=>value.final!==undefined);const mediaRevision=workspace?.revisions.find((value)=>value.parentRevisionId===revision.id&&value.parentRevisionDigest===revision.canonicalDigest);const audit=mediaRevision===undefined?undefined:workspace?.audits.find((value)=>value.artifactRevisionId===mediaRevision.id);const decision=audit===undefined?undefined:workspace?.ownerDecisions.find((value)=>value.auditDecisionId===audit.id);const pack=decision===undefined?undefined:workspace?.packages.find((value)=>value.ownerDecisionId===decision.id);
  const act=async(operation:()=>Promise<unknown>)=>{setBusy(true);setError(null);try{await operation();await reload();}catch(value){setError(value instanceof ProductApiError?value.code:'MEDIA_CONTROL_PLANE_UNAVAILABLE');}finally{setBusy(false);}};
  return <section className="lc-governed-media" aria-busy={busy}><header><div><p className="lc-eyebrow">{t('eyebrow')}</p><h3>{t('title')}</h3><p>{t('body')}</p></div><StatusBadge tone={readiness?.configured?'positive':'warning'}>{readiness?.configured?t('ready'):t('notConfigured')}</StatusBadge></header><div className="lc-media-gate"><div><strong>{t('gate')}</strong><code>{readiness?.fingerprint??'—'}</code><small>{t('terminalOnly')} · MODEL_PROVIDER ≠ MEDIA_PROVIDER</small></div><Button size="sm" disabled={busy} onClick={()=>void act(()=>startMediaGeneration(revision,'CONTROLLED_FAKE'))}>{t('fake')}</Button><Button size="sm" variant="primary" disabled={busy||readiness?.configured!==true} onClick={()=>void act(()=>startMediaGeneration(revision,'REAL_PROVIDER'))}>{t('real')}</Button></div>{error===null?null:<p role="alert" className="lc-media-error">{error}</p>}<ol className="lc-media-jobs">{jobs.length===0?<li><TriangleAlert size={15}/><span><strong>{t('empty')}</strong><small>{t('impact')}</small></span></li>:assets.map(({job,raw,final})=>{const cost=workspace?.costReceipts.find((value)=>value.canonicalDigest===raw?.costReceiptDigest);const rights=workspace?.rightsReceipts.find((value)=>value.canonicalDigest===raw?.rightsReceiptDigest);return <li key={job.id}><div className="lc-media-job-head"><span>{String(job.imageSpecPosition).padStart(2,'0')}</span><div><strong>{job.state}</strong><small>{job.providerAdapterRef} · {job.providerTaskId??t('noTask')}</small></div></div>{final===undefined?null:<img src={`/api/v1/media-assets/${final.id}/preview`} alt={final.altText}/>}<dl><div><dt>Final</dt><dd><code>{final?.contentDigest??'—'}</code></dd></div><div><dt>Raw lineage</dt><dd><code>{raw?.contentDigest??'—'}</code></dd></div><div><dt>{t('composition')}</dt><dd><code>{final?.compositionSpecDigest??'—'}</code></dd></div><div><dt>{t('snapshots')}</dt><dd><code>{final===undefined?'—':`${short(final.compositionSpec.brandSnapshotDigest)} / ${short(final.compositionSpec.knowledgeSnapshotDigest)}`}</code></dd></div><div><dt>{t('cost')}</dt><dd>{cost?.state??'UNVERIFIED'} · {cost?.finalAmount??cost?.reservedAmount??'—'}</dd></div><div><dt>{t('rights')}</dt><dd>{rights?.commercialUseStatus??'UNVERIFIED'}</dd></div></dl>{final===undefined?null:<a className="lc-media-link" href={`/api/v1/media-assets/${final.id}/download`}>{t('downloadFinal')}</a>}</li>})}</ol>
    <section className="lc-media-governance"><h4>{t('governance')}</h4><p>{mediaRevision===undefined?t('bindPending'):`v4 · ${short(mediaRevision.canonicalDigest)}`}</p><div className="flex flex-wrap gap-2"><Button size="sm" disabled={busy||!allFinal||mediaRevision!==undefined||workspace===null} onClick={()=>void act(()=>bindFinalMedia(revision,workspace!))}>{t('bindFinal')}</Button><Button size="sm" variant="danger" disabled={busy||mediaRevision===undefined||audit!==undefined} onClick={()=>void act(()=>auditFinalMedia(mediaRevision!,'FAIL'))}>Audit FAIL</Button><Button size="sm" disabled={busy||mediaRevision===undefined||audit!==undefined} onClick={()=>void act(()=>auditFinalMedia(mediaRevision!,'PASS'))}>Audit PASS</Button><Button size="sm" variant="primary" disabled={busy||audit?.result!=='PASS'||decision!==undefined} onClick={()=>void act(()=>decideFinalMedia(mediaRevision!,audit!,'APPROVE'))}>{t('approveFinal')}</Button><Button size="sm" disabled={busy||decision?.result!=='APPROVE'||pack!==undefined} onClick={()=>void act(()=>packageFinalMedia(mediaRevision!,audit!,decision!))}>{t('packageFinal')}</Button>{pack===undefined?null:<a className="lc-media-link" href={`/api/v1/media-publish-packages/${pack.id}/download`}>{t('downloadPackage')}</a>}</div><code>{audit?.result??'AUDIT_PENDING'} · {decision?.result??'OWNER_PENDING'} · {pack?.manifestDigest??'PACKAGE_PENDING'}</code></section><p className="lc-media-boundary">{t('boundary')}</p></section>;
}

function latestJobs(jobs:MediaWorkspace['jobs']){const values=new Map<number,MediaWorkspace['jobs'][number]>();for(const job of jobs){const current=values.get(job.imageSpecPosition);if(current===undefined||job.generation>current.generation||job.generation===current.generation&&job.createdAt>current.createdAt)values.set(job.imageSpecPosition,job);}return [...values.values()].sort((a,b)=>a.imageSpecPosition-b.imageSpecPosition);}

function ArtifactEditor({revision,parent,busy,onSave,t}:{revision:ArtifactRevisionV3;parent:ArtifactRevisionV3|undefined;busy:boolean;onSave:(payload:ArtifactPayload)=>void;t:Translator}){const [draft,setDraft]=useState<ArtifactPayload>(()=>structuredClone(revision.payload));const changed=JSON.stringify(draft)!==JSON.stringify(revision.payload);return <>
  {draft.kind==='X'?<XEditor value={draft} onChange={setDraft}/>:<XhsEditor value={draft} onChange={setDraft} t={t}/>}<div className="lc-artifact-editbar"><span>{changed?t('unsavedChanges'):t('exactSavedContent')}</span><Button variant="primary" disabled={busy||!changed} onClick={()=>onSave(draft)}>{t('saveNewRevision')}</Button></div>
  <details className="lc-artifact-diff" open={parent!==undefined}><summary><GitCompareArrows size={14}/>{t('diffTitle')}</summary>{parent===undefined?<p>{t('firstRevision')}</p>:<div className="lc-diff-grid"><article><small>{t('previous')}</small><pre>{displayContent(parent.payload)}</pre></article><article><small>{t('current')}</small><pre>{displayContent(revision.payload)}</pre></article></div>}</details></>}

function XEditor({value,onChange}:{value:XArtifactPayload;onChange:(value:XArtifactPayload)=>void}){const posts=value.posts;const setPost=(index:number,text:string)=>onChange({...value,posts:posts.map((post,itemIndex)=>itemIndex===index?{...post,text}:post)});const resize=(count:number)=>{const next=Array.from({length:count},(_,index)=>posts[index]??{position:index+1,text:'',mediaRefs:[],altText:null}).map((post,index)=>({...post,position:index+1}));onChange({...value,mode:count===1?'SINGLE':'THREAD',posts:next});};return <div className="lc-x-editor"><div className="lc-artifact-fieldrow"><label><span>Format</span><select value={value.mode} onChange={(event)=>resize(event.target.value==='SINGLE'?1:Math.max(posts.length,2))}><option>SINGLE</option><option>THREAD</option></select></label><label><span>Language</span><input value={value.language} onChange={(event)=>onChange({...value,language:event.target.value})}/></label></div>{posts.map((post,index)=><article key={post.position}><header><strong>POST {post.position}/{posts.length}</strong><span>{Array.from(post.text).length}/280</span></header><textarea aria-label={`Post ${post.position}`} value={post.text} onChange={(event)=>setPost(index,event.target.value)}/>{post.mediaRefs.length===0?<small>No media · alt text not required</small>:<div>{post.mediaRefs.map((media)=><p key={media.digest}>{media.fileName} · {media.altText}</p>)}</div>}</article>)}{value.mode==='THREAD'?<div className="flex gap-2"><Button size="sm" disabled={posts.length>=25} onClick={()=>resize(posts.length+1)}>+ Post</Button><Button size="sm" disabled={posts.length<=2} onClick={()=>resize(posts.length-1)}>− Post</Button></div>:null}<div className="lc-artifact-fieldrow"><label><span>CTA</span><input value={value.cta??''} onChange={(event)=>onChange({...value,cta:event.target.value||null})}/></label><label><span>HTTPS link</span><input value={value.link??''} onChange={(event)=>onChange({...value,link:event.target.value||null})}/></label></div></div>}

function XhsEditor({value,onChange,t}:{value:XiaohongshuArtifactPayload;onChange:(value:XiaohongshuArtifactPayload)=>void;t:Translator}){return <div className="lc-xhs-editor"><label className="lc-artifact-field"><span>{t('title')}</span><input value={value.title} onChange={(event)=>onChange({...value,title:event.target.value})}/></label><label className="lc-artifact-field"><span>{t('body')}</span><textarea value={value.body} onChange={(event)=>onChange({...value,body:event.target.value})}/></label><label className="lc-artifact-field"><span>{t('topics')}</span><input value={value.topics.join(' ')} onChange={(event)=>onChange({...value,topics:event.target.value.split(/\s+/u).map((item)=>item.replace(/^#/u,'')).filter(Boolean)})}/></label><label className="lc-artifact-field"><span>CTA</span><input value={value.cta??''} onChange={(event)=>onChange({...value,cta:event.target.value||null})}/></label><section className="lc-cover-spec"><strong>{t('coverSpec')} · {value.coverSpec.aspectRatio}</strong><input aria-label={t('coverBrief')} value={value.coverSpec.visualBrief} onChange={(event)=>onChange({...value,coverSpec:{...value.coverSpec,visualBrief:event.target.value}})}/><small>{t('notGeneratedMedia')}</small></section><ol className="lc-image-specs">{value.imageSpecs.map((spec,index)=><li key={spec.position}><span>{String(spec.position).padStart(2,'0')}</span><div><input aria-label={`${t('imagePurpose')} ${spec.position}`} value={spec.purpose} onChange={(event)=>onChange({...value,imageSpecs:value.imageSpecs.map((item,itemIndex)=>itemIndex===index?{...item,purpose:event.target.value}:item)})}/><textarea aria-label={`${t('imageBrief')} ${spec.position}`} value={spec.visualBrief} onChange={(event)=>onChange({...value,imageSpecs:value.imageSpecs.map((item,itemIndex)=>itemIndex===index?{...item,visualBrief:event.target.value}:item)})}/><small>{spec.aspectRatio} · {spec.authorizedMediaRef===null?t('specOnly'):spec.authorizedMediaRef.fileName}</small></div></li>)}</ol></div>}

function GateRail({revision,audit,decision,pack,invalid,busy,run,t}:{revision:ArtifactRevisionV3;audit:ArtifactAuditDecision|undefined;decision:ArtifactOwnerDecision|undefined;pack:ManualPublishPackage|undefined;invalid:boolean;busy:boolean;run:(operation:()=>Promise<unknown>,success:string)=>Promise<void>;t:Translator}){const canAudit=!invalid&&audit===undefined;const canDecide=!invalid&&audit!==undefined&&decision===undefined;const canPackage=!invalid&&audit?.result==='PASS'&&decision?.result==='APPROVE'&&pack===undefined;return <div><h2>{t('gatesTitle')}</h2><ol className="lc-gate-steps"><li data-state="done"><span>1</span><div><strong>{t('producer')}</strong><p>{revision.producerIdentityId}</p></div></li><li data-state={audit===undefined?'current':audit.result==='PASS'?'done':'blocked'}><span>2</span><div><strong>{t('independentAudit')}</strong><p>{audit===undefined?t('auditPending'):`${audit.auditorIdentityId} · ${audit.result}`}</p></div></li><li data-state={decision===undefined?'current':decision.result==='APPROVE'?'done':'blocked'}><span>3</span><div><strong>{t('ownerDecision')}</strong><p>{decision===undefined?t('ownerPending'):decision.result}</p></div></li><li data-state={pack===undefined?'current':'done'}><span>4</span><div><strong>{t('manualPackage')}</strong><p>{pack===undefined?t('packagePending'):t('packageReady')}</p></div></li></ol>
  <section className="lc-gate-actions"><h3>{t('auditAction')}</h3><p>{t('auditSeparation')}</p><div className="grid grid-cols-3 gap-1"><Button size="sm" disabled={busy||!canAudit} onClick={()=>run(()=>auditArtifact(revision,'PASS'),t('auditRecorded'))}>PASS</Button><Button size="sm" variant="danger" disabled={busy||!canAudit} onClick={()=>run(()=>auditArtifact(revision,'FAIL'),t('auditRecorded'))}>FAIL</Button><Button size="sm" disabled={busy||!canAudit} onClick={()=>run(()=>auditArtifact(revision,'ESCALATE'),t('auditRecorded'))}>ESCALATE</Button></div>{audit===undefined?null:<div className="lc-findings">{audit.findings.map((finding)=><article key={finding.checkCode} data-result={finding.result}><div><strong>{finding.checkCode}</strong><StatusBadge tone={finding.result==='PASS'?'positive':finding.result==='FAIL'?'danger':'warning'}>{finding.result}</StatusBadge></div><p>{finding.message}</p><code>{finding.path}</code></article>)}</div>}</section>
  <section className="lc-gate-actions"><h3>{t('ownerAction')}</h3><p>{audit?.result!=='PASS'?t('approvalBlocked'):t('approveExact',{digest:short(revision.canonicalDigest)})}</p><div className="grid grid-cols-2 gap-2"><Button variant="primary" disabled={busy||!canDecide||audit?.result!=='PASS'} onClick={()=>run(()=>decideArtifact(revision,audit!,'APPROVE',null),t('decisionRecorded'))}>{t('approve')}</Button><Button variant="danger" disabled={busy||!canDecide} onClick={()=>run(()=>decideArtifact(revision,audit!,'REJECT',t('ownerRejectedReason')),t('decisionRecorded'))}>{t('reject')}</Button></div></section>
  <section className="lc-gate-actions"><h3>{t('packageAction')}</h3><Button className="w-full" disabled={busy||!canPackage} onClick={()=>run(()=>createManualPublishPackage(revision,audit!,decision!),t('packageCreated'))}><FileCheck2 size={14}/>{t('createPackage')}</Button>{pack===undefined?<p className="lc-package-boundary"><LockKeyhole size={13}/>{t('exactPassApproveRequired')}</p>:<PackageActions pack={pack} revision={revision} disabled={busy} run={run} t={t}/>}</section>
  <details className="lc-technical-details"><summary>{t('technicalDetails')}</summary><code>{revision.id}<br/>{revision.canonicalDigest}<br/>{audit?.canonicalDigest??'AUDIT_PENDING'}<br/>{decision?.canonicalDigest??'OWNER_DECISION_PENDING'}<br/>{pack?.manifestDigest??'PACKAGE_PENDING'}</code></details></div>}

function PackageActions({pack,revision,disabled,run,t}:{pack:ManualPublishPackage;revision:ArtifactRevisionV3;disabled:boolean;run:(operation:()=>Promise<unknown>,success:string)=>Promise<void>;t:Translator}){const copy=async()=>{const {promise}=recordPackageEvent(pack,'copy-event');await promise;await navigator.clipboard.writeText(displayContent(revision.payload));};const download=async()=>{const event=recordPackageEvent(pack,'download-event');await event.promise;const response=await fetch(event.downloadUrl,{cache:'no-store'});if(!response.ok)throw new ProductApiError('PACKAGE_DOWNLOAD_FAILED',response.status);const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`lumiclaw-${pack.platformCode.toLowerCase()}-${pack.id}.json`;anchor.click();URL.revokeObjectURL(url);};const open=async()=>{const {promise}=recordPackageEvent(pack,'open-official');const result=await promise;const child=result.officialUrl===null?null:window.open(result.officialUrl,'_blank');if(child===null)throw new ProductApiError('OFFICIAL_PAGE_POPUP_BLOCKED',409);child.opener=null;};return <div className="lc-package-actions"><div><ShieldCheck size={18}/><p><strong>{t('packageReady')}</strong><small>{t('externalUnverified')}</small></p></div><Button size="sm" disabled={disabled} onClick={()=>run(copy,t('copied'))}><Clipboard size={13}/>{t('copy')}</Button><Button size="sm" disabled={disabled} onClick={()=>run(download,t('downloaded'))}><Download size={13}/>{t('download')}</Button><Button size="sm" disabled={disabled} onClick={()=>run(open,t('opened'))}><ExternalLink size={13}/>{t('openOfficial')}</Button><ol>{pack.orderedFiles.map((file)=><li key={file.fileName}><span>{file.position}. {file.fileName}</span><code>{short(file.digest)}</code></li>)}</ol></div>}

function Regenerate({disabled,onRequest,t}:{disabled:boolean;onRequest:(reason:string)=>void;t:Translator}){const [reason,setReason]=useState('');return <section className="lc-regenerate"><div><RefreshCw size={15}/><span><strong>{t('regenerateTitle')}</strong><small>{t('regenerateBody')}</small></span></div><input aria-label={t('regenerateReason')} value={reason} onChange={(event)=>setReason(event.target.value)} placeholder={t('regeneratePlaceholder')}/><Button size="sm" disabled={disabled||reason.trim().length===0} onClick={()=>onRequest(reason)}>{t('requestRegenerate')}</Button></section>}
function InputTrace({revision,t}:{revision:ArtifactRevisionV3;t:Translator}){const bindings:Array<[string,string,string]>=[['Bundle',revision.inputBindings.executionBundle.id,revision.inputBindings.executionBundle.digest],['Goal',revision.inputBindings.operatingGoal.id,revision.inputBindings.operatingGoal.digest],['Plan',revision.inputBindings.approvedPlan.id,revision.inputBindings.approvedPlan.digest],['Knowledge',revision.inputBindings.knowledgeSnapshot.id,revision.inputBindings.knowledgeSnapshot.digest],['Account',revision.inputBindings.accountProfile.id,revision.inputBindings.accountProfile.digest],['Skill',`${revision.inputBindings.producerSkill.id}@${revision.inputBindings.producerSkill.version}`,revision.inputBindings.producerSkill.digest],['Profile',`${revision.artifactProfileRef.id}@${revision.artifactProfileRef.version}`,revision.artifactProfileRef.digest]];return <details className="lc-binding-trace" open><summary>{t('traceTitle')}</summary><div className="lc-trace-list">{bindings.map(([kind,id,digest])=><article key={kind}><span>{kind}</span><code>{id}<br/>{short(digest)}</code></article>)}</div></details>}
function Boundary({title,body,code}:{title:string;body:string;code:string}){return <section className="lc-rule-sheet grid min-h-[360px] place-items-center"><div className="max-w-xl text-center"><LockKeyhole className="mx-auto text-[var(--lc-warning)]"/><h2 className="mt-4 text-xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-6 text-[var(--lc-ink-muted)]">{body}</p><code className="mt-4 block text-xs">{code}</code></div></section>}
function displayContent(payload:ArtifactPayload):string{return payload.kind==='X'?payload.posts.map((post)=>`${post.position}/${payload.posts.length}\n${post.text}`).join('\n\n'):`${payload.title}\n\n${payload.body}\n\n${payload.topics.map((topic)=>`#${topic.replace(/^#/u,'')}`).join(' ')}`;}
function short(value:string):string{return `${value.slice(0,8)}…${value.slice(-6)}`;}
type Translator=ReturnType<typeof useTranslations<'ArtifactPublish'>>;
const emptyWorkspace={revisions:[],quarantines:[],audits:[],ownerDecisions:[],regenerationRequests:[],packages:[],helperEvents:[],invalidations:[]};
