'use client';

import type {ArtifactRevision, CampaignEnvelope, PlatformArtifact} from '@lumiclaw/domain';
import {BookOpenCheck, ChevronRight, CircleAlert, ShieldCheck} from 'lucide-react';
import {useTranslations} from 'next-intl';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Drawer} from '@/components/ui/dialog';
import {StatusBadge} from '@/components/ui/status-badge';

type CampaignFeatureProps = {campaign: CampaignEnvelope};
type CampaignTab = 'overview' | 'readiness' | 'content' | 'review' | 'learn';

export function CampaignFeature({campaign}: CampaignFeatureProps) {
  const t = useTranslations('Production');
  const [tab, setTab] = useState<CampaignTab>('overview');
  const [selected, setSelected] = useState<ArtifactRevision | null>(null);
  const tabs: CampaignTab[] = ['overview', 'readiness', 'content', 'review', 'learn'];
  return <>
    <div className="border-b border-[var(--lc-line)]"><div className="flex items-end justify-between gap-8 pb-5"><div><div className="flex items-center gap-2"><StatusBadge tone={campaign.mode === 'LOCAL_PRIVATE' ? 'info' : 'warning'}>{campaign.mode} · {campaign.mode === 'LOCAL_PRIVATE' ? t('modeLocalPrivate') : t('modePublicSafe')}</StatusBadge><StatusBadge tone={campaign.readiness === 'BLOCKED' ? 'danger' : 'positive'}>{campaign.readiness}</StatusBadge></div><h1 className="mt-3 font-[var(--lc-font-serif)] text-[34px] font-semibold tracking-[-0.035em]">{campaign.document.brief.name}</h1><p className="mt-2 max-w-3xl text-sm text-[var(--lc-ink-muted)]">{campaign.document.brief.objective}</p></div><div className="text-right font-[var(--lc-font-mono)] text-[10px] text-[var(--lc-ink-muted)]"><p>{t('version')} {campaign.version}</p><p className="mt-1 max-w-[250px] truncate">{campaign.digest}</p></div></div><div className="flex gap-6" role="tablist" aria-label={t('campaignWorkspace')}>{tabs.map((item) => <button key={item} role="tab" aria-selected={tab === item} className={`border-b-2 px-0.5 pb-3 text-[12px] font-semibold ${tab === item ? 'border-[var(--lc-accent)] text-[var(--lc-ink)]' : 'border-transparent text-[var(--lc-ink-muted)] hover:text-[var(--lc-ink)]'}`} onClick={() => setTab(item)}>{t(`campaignTabs.${item}`)}</button>)}</div></div>
    <div className="pt-6">{tab === 'overview' ? <Overview campaign={campaign} onView={setSelected} /> : tab === 'readiness' ? <Readiness campaign={campaign} /> : tab === 'content' ? <ContentTable campaign={campaign} onView={setSelected} /> : tab === 'review' ? <ReviewQueue campaign={campaign} onView={setSelected} /> : <LearnBlocked />}</div>
    <ContentDrawer campaign={campaign} revision={selected} onClose={() => setSelected(null)} />
  </>;
}

function Overview({campaign, onView}: {campaign: CampaignEnvelope; onView: (revision: ArtifactRevision) => void}) {
  const t = useTranslations('Production');
  const doc = campaign.document;
  return <div className="grid grid-cols-[minmax(0,1.5fr)_360px] gap-6"><div className="space-y-6"><section className="border border-[var(--lc-line)] bg-[var(--lc-surface)]"><SectionTitle index="01" title={t('campaignBrief')} /><dl className="grid grid-cols-2 gap-px bg-[var(--lc-line)]"><Fact label={t('objective')} value={doc.brief.objective} /><Fact label={t('callToActionShort')} value={doc.brief.callToAction} /><Fact label={t('targetMarket')} value={doc.graph.markets.map((item) => `${item.code} · ${item.displayName}`).join(' / ')} /><Fact label={t('contentLanguage')} value={doc.brief.contentLanguage} /></dl></section><section className="border border-[var(--lc-line)] bg-[var(--lc-surface)]"><SectionTitle index="02" title={t('platformContent')} /><div className="divide-y divide-[var(--lc-line)]">{doc.artifactRevisions.map((revision) => <button key={revision.id} className="flex w-full items-center gap-4 px-5 py-3.5 text-left hover:bg-[var(--lc-surface-muted)]" onClick={() => onView(revision)}><span className="w-24 font-[var(--lc-font-mono)] text-[10px] font-bold">{revision.platform}</span><span className="min-w-0 flex-1 truncate text-[13px] text-[var(--lc-ink-muted)]">{contentSummary(revision.content)}</span><StatusBadge tone="warning">NEEDS_REVIEW · {t('needsReview')}</StatusBadge><ChevronRight size={15} aria-hidden /></button>)}</div></section></div><aside className="space-y-4"><div className="border border-[var(--lc-line)] bg-[var(--lc-sidebar)] p-5 text-white"><p className="font-[var(--lc-font-mono)] text-[9px] font-bold tracking-[0.09em] text-[#ef9b87]">{t('activeAgent')}</p><div className="mt-4 flex items-center gap-3"><div className="grid size-9 place-items-center rounded-full bg-white/10 text-xs font-bold">A5</div><div><strong className="text-sm">{t('agents.A5.name')}</strong><p className="text-[11px] text-white/75">independent-auditor</p></div></div><p className="mt-4 text-xs leading-5 text-white/75">{t('auditResponsibilityBody')}</p><StatusBadge tone="warning">NOT_CONFIGURED</StatusBadge></div><div className="border border-[var(--lc-line)] bg-[var(--lc-surface)] p-5"><p className="text-xs font-semibold">{t('evidence')}</p><div className="mt-4 space-y-3">{doc.claims.map((claim) => <div key={claim.id} className="border-l-2 border-[var(--lc-line)] pl-3"><StatusBadge tone={claim.status === 'APPROVED' ? 'positive' : 'warning'}>{claim.status}</StatusBadge><p className="mt-2 text-xs leading-5 text-[var(--lc-ink-muted)]">{claim.statement}</p></div>)}</div></div></aside></div>;
}

function Readiness({campaign}: {campaign: CampaignEnvelope}) {
  const t = useTranslations('Production');
  const doc = campaign.document;
  return <div className="grid grid-cols-2 gap-6"><section className="border border-[var(--lc-line)] bg-[var(--lc-surface)]"><SectionTitle index="A" title={t('claimEvidence')} /><div className="divide-y divide-[var(--lc-line)]">{doc.claims.map((claim) => <div key={claim.id} className="p-5"><div className="flex items-center justify-between"><StatusBadge tone={claim.status === 'APPROVED' ? 'positive' : 'warning'}>{claim.status}</StatusBadge><span className="font-[var(--lc-font-mono)] text-[10px] text-[var(--lc-ink-muted)]">v{claim.version}</span></div><p className="mt-3 text-[13px] leading-6">{claim.statement}</p><p className="mt-2 text-[11px] text-[var(--lc-ink-muted)]">{t('evidenceRefCount', {count: claim.evidenceRefIds.length})}</p></div>)}</div></section><section className="border border-[var(--lc-line)] bg-[var(--lc-surface)]"><SectionTitle index="B" title={t('accountCapabilities')} /><div className="divide-y divide-[var(--lc-line)]">{doc.capabilitySnapshots.map((item) => <div key={item.id} className="flex items-center gap-4 p-4"><ShieldCheck size={16} aria-hidden className="text-[var(--lc-positive)]" /><div className="min-w-0 flex-1"><strong className="text-xs">{item.platform}</strong><p className="truncate text-[11px] text-[var(--lc-ink-muted)]">{item.source} · {t('expiresOn', {date: item.expiresAt.slice(0, 10)})}</p></div><StatusBadge tone="info">{item.executionMode}</StatusBadge></div>)}</div></section></div>;
}

function ContentTable({campaign, onView}: {campaign: CampaignEnvelope; onView: (revision: ArtifactRevision) => void}) {
  const t = useTranslations('Production');
  return <section className="border border-[var(--lc-line)] bg-[var(--lc-surface)]"><div className="grid grid-cols-[120px_minmax(0,1fr)_110px_170px] border-b border-[var(--lc-line)] bg-[var(--lc-surface-muted)] px-5 py-2.5 font-[var(--lc-font-mono)] text-[9px] font-bold tracking-[0.07em] text-[var(--lc-ink-muted)]"><span>{t('platformColumn')}</span><span>{t('fullContent')}</span><span>{t('version')}</span><span>{t('status')}</span></div>{campaign.document.artifactRevisions.map((revision) => <button key={revision.id} className="grid w-full grid-cols-[120px_minmax(0,1fr)_110px_170px] items-center border-b border-[var(--lc-line)] px-5 py-4 text-left last:border-0 hover:bg-[var(--lc-surface-muted)]" onClick={() => onView(revision)}><strong className="font-[var(--lc-font-mono)] text-[11px]">{revision.platform}</strong><span className="truncate pr-7 text-[13px] text-[var(--lc-ink-muted)]">{contentSummary(revision.content)}</span><span className="text-xs">R{revision.revision}</span><StatusBadge tone="warning">NEEDS_REVIEW · {t('needsReview')}</StatusBadge></button>)}</section>;
}

function ReviewQueue({campaign, onView}: {campaign: CampaignEnvelope; onView: (revision: ArtifactRevision) => void}) {
  const t = useTranslations('Production');
  return <div><div className="mb-5 flex items-center gap-3 rounded-md border border-[var(--lc-warning)]/30 bg-[var(--lc-warning-soft)] px-4 py-3 text-xs text-[var(--lc-warning)]"><CircleAlert size={16} aria-hidden /><span>{t('reviewBlockedBody')}</span></div><div className="grid grid-cols-2 gap-4">{campaign.document.artifactRevisions.map((revision) => <article key={revision.id} className="border border-[var(--lc-line)] bg-[var(--lc-surface)] p-5"><div className="flex items-center justify-between"><StatusBadge tone="neutral">{revision.platform}</StatusBadge><span className="font-[var(--lc-font-mono)] text-[10px] text-[var(--lc-ink-muted)]">R{revision.revision}</span></div><p className="mt-4 line-clamp-3 min-h-[60px] text-[13px] leading-5 text-[var(--lc-ink-muted)]">{contentSummary(revision.content)}</p><Button className="mt-4" size="sm" onClick={() => onView(revision)}><BookOpenCheck size={14} aria-hidden />{t('viewContent')}</Button></article>)}</div></div>;
}
function LearnBlocked() { const t = useTranslations('Production'); return <div className="grid min-h-[360px] place-items-center border border-dashed border-[var(--lc-line)] bg-[var(--lc-surface)]"><div className="max-w-md text-center"><CircleAlert className="mx-auto text-[var(--lc-warning)]" size={28} aria-hidden /><StatusBadge tone="warning">{t('blocked')}</StatusBadge><h2 className="mt-4 font-[var(--lc-font-serif)] text-2xl font-semibold">{t('noFeedback')}</h2><p className="mt-3 text-sm leading-6 text-[var(--lc-ink-muted)]">{t('feedbackBody')}</p></div></div>; }

function ContentDrawer({campaign, revision, onClose}: {campaign: CampaignEnvelope; revision: ArtifactRevision | null; onClose: () => void}) {
  const t = useTranslations('Production');
  const producerCode = revision?.platform === 'X' || revision?.platform === 'XIAOHONGSHU' ? 'A3' : 'A4';
  const producer = `${producerCode} · ${t(`agents.${producerCode}.name`)}`;
  return <Drawer open={revision !== null} onOpenChange={(open) => { if (!open) onClose(); }} title={revision === null ? t('fullContent') : `${revision.platform} · ${t('revision', {number: revision.revision})}`} description={`${t('source')}: ${campaign.mode} · ${campaign.digest.slice(0, 16)}…`} footer={<div className="flex items-center justify-between"><p className="text-xs text-[var(--lc-ink-muted)]">{t('approvalBlocked')}</p><div className="flex gap-2"><Button disabled variant="secondary">{t('changes')}</Button><Button disabled variant="primary">{t('approve')}</Button></div></div>}>
    {revision === null ? null : <div><section aria-label={t('fullContent')} className="rounded-md border border-[var(--lc-line)] bg-white p-5"><p className="whitespace-pre-wrap text-[15px] leading-7">{formatArtifact(revision.content, t('alternativeText'))}</p></section><section className="mt-6 border border-[var(--lc-line)] bg-[var(--lc-surface-muted)] p-4"><p className="font-[var(--lc-font-mono)] text-[9px] font-bold tracking-[0.08em] text-[var(--lc-ink-muted)]">{t('activeAgent')}</p><div className="mt-3 flex items-center gap-3"><div className="grid size-8 place-items-center rounded-full bg-[var(--lc-sidebar)] text-[10px] font-bold text-white">{producerCode}</div><div><strong className="text-xs">{producer}</strong><p className="text-[11px] text-[var(--lc-ink-muted)]">{t('artifactSourceRole')}</p></div></div></section><details className="mt-5 border-y border-[var(--lc-line)] py-3"><summary className="cursor-pointer text-xs font-semibold">{t('trace')}</summary><ol className="mt-4 space-y-3 border-l border-[var(--lc-line)] pl-5 text-xs text-[var(--lc-ink-muted)]"><li><strong className="text-[var(--lc-ink)]">A1 · {t('traceEvidenceFreeze')}</strong><p>{t('traceEvidenceBody')}</p></li><li><strong className="text-[var(--lc-ink)]">{producer} · {t('traceProduce')}</strong><p>{t('traceProduceBody', {mode: campaign.mode, revision: revision.revision})}</p></li><li><strong className="text-[var(--lc-ink)]">A5 · {t('traceAudit')}</strong><p>{t('traceAuditBody')}</p></li></ol></details><section className="mt-5"><p className="text-xs font-semibold">{t('evidence')}</p>{campaign.document.claims.filter((claim) => revision.claimIds.includes(claim.id)).map((claim) => <blockquote key={claim.id} className="mt-3 border-l-2 border-[var(--lc-accent)] pl-4 text-[13px] leading-6 text-[var(--lc-ink-muted)]">{claim.statement}</blockquote>)}</section></div>}
  </Drawer>;
}

function SectionTitle({index, title}: {index: string; title: string}) { return <header className="flex items-center gap-3 border-b border-[var(--lc-line)] px-5 py-3"><span className="font-[var(--lc-font-mono)] text-[9px] font-bold text-[var(--lc-accent)]">{index}</span><h2 className="text-xs font-semibold">{title}</h2></header>; }
function Fact({label, value}: {label: string; value: string}) { return <div className="bg-[var(--lc-surface)] p-5"><dt className="font-[var(--lc-font-mono)] text-[9px] font-bold tracking-[0.06em] text-[var(--lc-ink-muted)]">{label.toUpperCase()}</dt><dd className="mt-2 text-[13px] leading-6">{value}</dd></div>; }
export function contentSummary(content: PlatformArtifact): string { if (content.kind === 'LINKEDIN') return content.commentary; if (content.kind === 'XIAOHONGSHU') return `${content.title} · ${content.body}`; return content.posts.join(' '); }
export function formatArtifact(content: PlatformArtifact, alternativeTextLabel: string): string { if (content.kind === 'LINKEDIN') return `${content.commentary}\n\n${content.linkTitle}\n${content.linkUrl}`; if (content.kind === 'XIAOHONGSHU') return `${content.title}\n\n${content.body}\n\n${content.topics.map((item) => `#${item}`).join(' ')}`; return `${content.posts.join('\n\n')}\n\n${alternativeTextLabel}: ${content.altText}${content.kind === 'BLUESKY' ? `\n${content.embedUrl}` : ''}`; }
