'use client';

import {Bot, ChevronRight, FileCode2} from 'lucide-react';
import {useTranslations} from 'next-intl';
import {useState} from 'react';
import {loadSkill} from '@/lib/production-api';
import type {RepositorySkill, TeamAgent} from '@/lib/production-types';
import {Button} from '@/components/ui/button';
import {Drawer} from '@/components/ui/dialog';
import {StatusBadge} from '@/components/ui/status-badge';

export function TeamFeature({agents, skills}: {agents: TeamAgent[]; skills: RepositorySkill[]}) {
  const t = useTranslations('Production'); const [selected, setSelected] = useState<TeamAgent | null>(null);
  return <><div className="border border-[var(--lc-line)] bg-[var(--lc-surface)]"><div className="grid grid-cols-[72px_minmax(220px,1fr)_minmax(260px,1.5fr)_120px_120px_150px_34px] border-b border-[var(--lc-line)] bg-[var(--lc-surface-muted)] px-5 py-2.5 font-[var(--lc-font-mono)] text-[9px] font-bold tracking-[0.06em] text-[var(--lc-ink-muted)]"><span>CODE</span><span>ROLE</span><span>RESPONSIBILITY</span><span>{t('tokens').toUpperCase()}</span><span>{t('daily').toUpperCase()}</span><span>RUNTIME</span><span /></div>{agents.map((agent) => <button key={agent.code} onClick={() => setSelected(agent)} className="grid w-full grid-cols-[72px_minmax(220px,1fr)_minmax(260px,1.5fr)_120px_120px_150px_34px] items-center border-b border-[var(--lc-line)] px-5 py-4 text-left last:border-0 hover:bg-[var(--lc-surface-muted)]"><div className="grid size-8 place-items-center rounded-full bg-[var(--lc-sidebar)] font-[var(--lc-font-mono)] text-[10px] font-bold text-white">{agent.code}</div><div><strong className="block text-[13px]">{agent.name}</strong><span className="font-[var(--lc-font-mono)] text-[9px] text-[var(--lc-ink-muted)]">{agent.roleId}</span></div><p className="pr-6 text-xs leading-5 text-[var(--lc-ink-muted)]">{agent.responsibility}</p><Metric value={agent.metrics.tokens} source={agent.metrics.source} /><Metric value={agent.metrics.dailyCompleted} source={agent.metrics.source} /><StatusBadge tone={agent.status === 'RUNNING' ? 'positive' : agent.status === 'ERROR' ? 'danger' : 'warning'}>{agent.status}</StatusBadge><ChevronRight size={15} aria-hidden /></button>)}</div><p className="mt-3 text-[11px] text-[var(--lc-ink-muted)]">{t('metricsSource')}: NO_RUNTIME_OBSERVATION · 0 means no authoritative observation, not zero business work.</p><AgentDrawer agent={selected} skills={skills} onClose={() => setSelected(null)} /></>;
}

function Metric({value, source}: {value: number; source: string}) { return <div><strong className="font-[var(--lc-font-mono)] text-sm">{value}</strong><span className="mt-0.5 block max-w-[100px] truncate text-[9px] text-[var(--lc-ink-muted)]" title={source}>{source}</span></div>; }

function AgentDrawer({agent, skills, onClose}: {agent: TeamAgent | null; skills: RepositorySkill[]; onClose: () => void}) {
  const t = useTranslations('Production'); const [skillContent, setSkillContent] = useState<{id: string; content: string} | null>(null); const [error, setError] = useState<string | null>(null);
  const inspect = async (id: string) => { setError(null); try { const result = await loadSkill(id); setSkillContent({id, content: result.skill.content}); } catch (caught) { setError(caught instanceof Error ? caught.message : 'SKILL_LOAD_FAILED'); } };
  return <Drawer open={agent !== null} onOpenChange={(open) => { if (!open) { setSkillContent(null); onClose(); } }} title={agent === null ? 'Agent' : `${agent.code} · ${agent.name}`} description={agent?.roleId ?? ''}>
    {agent === null ? null : <div><div className="grid grid-cols-3 gap-px overflow-hidden rounded-md border border-[var(--lc-line)] bg-[var(--lc-line)]"><AgentFact label="Runtime" value={agent.status} /><AgentFact label={t('tokens')} value={String(agent.metrics.tokens)} /><AgentFact label={t('daily')} value={String(agent.metrics.dailyCompleted)} /></div><section className="mt-6"><h3 className="text-xs font-semibold">Responsibility</h3><p className="mt-2 text-[14px] leading-6 text-[var(--lc-ink-muted)]">{agent.responsibility}</p></section><section className="mt-6"><div className="flex items-center gap-2"><FileCode2 size={15} aria-hidden /><h3 className="text-xs font-semibold">{t('skills')}</h3></div><p className="mt-2 text-[11px] text-[var(--lc-ink-muted)]">{t('skillSource')}</p><div className="mt-3 space-y-2">{agent.skillIds.map((id) => { const skill = skills.find((item) => item.id === id); return <button key={id} onClick={() => inspect(id)} className="flex w-full items-center gap-3 rounded-md border border-[var(--lc-line)] bg-white px-3 py-3 text-left hover:border-[#aaa69c]"><Bot size={15} aria-hidden className="text-[var(--lc-accent)]" /><span className="min-w-0 flex-1"><strong className="block text-xs">{skill?.name ?? id}</strong><small className="font-[var(--lc-font-mono)] text-[9px] text-[var(--lc-ink-muted)]">{id}</small></span><ChevronRight size={14} aria-hidden /></button>; })}</div></section>{error === null ? null : <p role="alert" className="mt-4 text-xs text-[var(--lc-danger)]">{error}</p>}{skillContent === null ? null : <section className="mt-6"><div className="flex items-center justify-between"><h3 className="text-xs font-semibold">{skillContent.id}/SKILL.md</h3><StatusBadge tone="positive">REPOSITORY_OWNED</StatusBadge></div><pre className="lc-scrollbar mt-3 max-h-[420px] overflow-auto whitespace-pre-wrap rounded-md bg-[var(--lc-sidebar)] p-4 font-[var(--lc-font-mono)] text-[11px] leading-5 text-white/75">{skillContent.content}</pre></section>}<div className="mt-6"><Button disabled variant="secondary">Start Agent · SDD-007 required</Button></div></div>}
  </Drawer>;
}
function AgentFact({label, value}: {label: string; value: string}) { return <div className="bg-[var(--lc-surface)] p-4"><p className="font-[var(--lc-font-mono)] text-[9px] font-bold text-[var(--lc-ink-muted)]">{label.toUpperCase()}</p><strong className="mt-2 block text-xs">{value}</strong></div>; }
