'use client';

import type {CampaignEnvelope, PlatformArtifact} from '@lumiclaw/domain';
import type {AppLocale} from '@lumiclaw/i18n';
import {useCallback, useEffect, useState} from 'react';

export type ShadowFixtureState = 'empty' | 'prerequisite-blocked' | 'queued' | 'waiting-runtime' | 'running' | 'waiting-dependency' | 'needs-owner' | 'failed' | 'timed-out' | 'cancelled' | 'unknown-recovery' | 'audit-blocked' | 'revision-required' | 'shadow-complete';
type Role = {roleId: string; identityId: string; responsibility: string; permissions: string[]; orchestrationOnly: boolean; contextDigest: string};
type Task = {id: string; roleId: string; kind: string; attempt: number; state: string; prerequisiteTaskIds: string[]; acceptedOutputDigest: string | null};
type Revision = {id: string; platform: string; revision: number; digest: string; parentRevisionId: string | null; producerRoleId: string; content: PlatformArtifact};
type Audit = {id: string; revisionId: string; outcome: 'PASS' | 'FAIL' | 'ESCALATE'; status: 'ACTIVE' | 'INVALIDATED'; issues: {code: string; message: string; evidenceRefIds: string[]; nextResponsibleRoleId: string}[]};
type Review = {revisionId: string; authority: 'NON_EXECUTABLE_OWNER_REVIEW'; createsActionGrant: false; decision: string};
type Trace = {sequence: number; kind: string; businessLabel: string; detail: Record<string, string | number | boolean | null>; createdAt: string};
type ModelCall = {id: string; taskId: string; provider: 'DEEPSEEK' | 'PUBLIC_SAFE_MOCK'; maturity: 'CANARY' | 'MOCK_CONFORMANCE'; model: string; tokenUsage: {input: number; output: number; cacheHit: number; cacheMiss: number; reasoning: number} | null; estimatedCostUsd: number | null; latencyMs: number; attempts: number; error: {code: string; retryable: boolean} | null; secretPresent: false};
type UiMission = {id: string; state: string; etag: string; runtimeVersion: 'v1.2.0'; sourceCampaignDigest: string; providerMode: 'PUBLIC_SAFE_MOCK' | 'LIVE_DEEPSEEK_UAT'; providerModel: 'deepseek-v4-flash' | 'deepseek-v4-pro'; providerMaturity: 'MOCK_CONFORMANCE' | 'LIVE_PROVIDER_CANARY'; runtimeStatus: {nextResponsible: string; failure: {code: string; retryable: boolean; failedTaskId: string | null; at: string} | null; lastHeartbeatAt: string | null}; externalActionAllowed: false; actionGrantCount: 0; connectorCount: 0; externalActionCount: 0; roleContexts: Role[]; tasks: Task[]; revisions: Revision[]; audits: Audit[]; reviews: Review[]; modelCalls: ModelCall[]; trace: Trace[]; fault: {deniedRevisionId: string | null; correctedRevisionId: string | null; injectedPath: string}};
type ApiError = Error & {code?: string};

const text = {
  'zh-CN': {
    eyebrow: 'GOVERNED SHADOW / NOT_LIVE', title: '六个角色，一条可核验的内容生产线。', subtitle: '你看到的是业务进度；任务 digest、模型快照与 runtime trace 按需展开。这里没有发布能力。',
    start: '创建运行', run: '运行公开安全故障演练', running: '正在读取 PostgreSQL 控制面…', retry: '重新读取控制面',
    choose: '选择本次运行方式', chooseDetail: '两种方式共享同一套治理与审计语义，但成熟度和启动责任不同。选择后不可在运行中切换。', mockTitle: '公开安全 Mock 演练', mockDetail: '全自动、无 Key。用于验证四平台 Revision、故障拒绝、修订与复审；不是真实模型或真实 AgentTeams 证明。', liveTitle: '真实 DeepSeek 测试运行', liveDetail: '本地 UAT Canary。模型固定为 deepseek-v4-flash；创建后等待 Coordinator 启动固定版本六成员 Runner。网页不会接收 API Key，也不会静默回退 Mock。', startMock: '创建 Mock Mission', startLive: '创建真实模型 UAT', localOnly: '本地真实模型 UAT，需要 Coordinator 启动 Runner；不是线上常驻服务。', notPublished: '所有内容都是未发布草稿。', nextAction: '现在该谁处理', waitingRunner: 'Mission 已持久化。请把下面三个公开标识交给 Coordinator，由其在安全交互式终端启动 Runner。刷新页面不会丢失进度。', handoff: '交给 Coordinator 的公开标识', liveFailed: '真实运行已 fail closed。没有切换到 Mock；请由 Coordinator 检查 Secret、Runner 或供应商状态后重新发起受控尝试。', modelReceipts: '真实模型收据', noModelLeader: 'Leader 只编排，不调用模型。其余领域任务分别绑定独立收据。', technical: '展开技术证据',
    noMission: '尚未启动 Mission', noMissionDetail: '先保存 M1 Campaign；系统会固定当前 Campaign digest，再创建六个独立成员。', prereq: 'Campaign 前置条件未满足',
    roster: '责任分工', flow: '任务流', evidence: '证据抽屉', evidenceHint: '只展示 allowlist 字段与 digest；不展示 prompt、Key、Cookie 或原始 Matrix 消息。',
    reviewTitle: '审计台', reviewLead: '先看被拒绝的说法，再比较修正版。Auditor 只能给决定，不能替你改内容。', exactReview: '记录精确 Owner Review', reviewed: '已记录（不可执行）', changes: '修正差异',
    fail: '拒绝', pass: '通过', invalidated: '已失效', nextRole: '下一责任角色', boundEvidence: '绑定 Evidence', noGrant: 'Owner Review ≠ ActionGrant', noGrantDetail: '该确认只绑定 Revision digest 与账号意图；不会创建 Grant、连接器、排程执行或发布动作。',
    truth: '边界检查', trace: '逐条 trace / ledger', source: 'Campaign digest', team: '6 MEMBERS', version: 'AgentTeams v1.2.0', mock: '按钮运行的是公开安全 MOCK_CONFORMANCE；真实 AgentTeams 验收证据单独标注。',
    states: {QUEUED: 'Mock 已排队', WAITING_RUNTIME: '等待本地 Runner', RUNNING: '六成员运行中', WAITING_DEPENDENCY: '等待前置任务', NEEDS_OWNER_REVIEW: '等待 Owner 精确确认', AWAITING_OWNER_REVIEW: '等待 Owner 精确确认', FAILED: '已安全失败', TIMED_OUT: '已超时', CANCELLED: '已取消', UNKNOWN_RECOVERY: '状态未知，正在恢复', AUDIT_BLOCKED: '审计阻断', REVISION_REQUIRED: '需要修订', SHADOW_COMPLETE: 'SHADOW 已完成', COMPLETED_SHADOW: 'SHADOW 已完成'},
    roleNames: {'presence-mission-leader': '任务编排负责人', 'evidence-claim-steward': '证据与主张管理员', 'campaign-planner': 'Campaign 规划员', 'founder-identity-producer': 'Founder 内容制作人', 'product-account-producer': '产品账号内容制作人', 'independent-auditor': '独立审计员', OWNER: 'Owner', COORDINATOR: 'Coordinator', CONTROL_PLANE: '控制面'},
    taskKinds: {PROJECT_COORDINATION: '编排 Project', FREEZE_EVIDENCE: '冻结 Claim / Evidence', PLAN_CAMPAIGN: '分配 Activation Plan', PRODUCE_FOUNDER: '生成 Founder 首版', PRODUCE_PRODUCT: '生成 Product 首版', AUDIT_REVISIONS: '独立首轮审核', PRODUCE_FOUNDER_CORRECTION: '修正被拒绝的 X Revision', REAUDIT_CORRECTION: '独立重审 X v2'}
  },
  en: {
    eyebrow: 'GOVERNED SHADOW / NOT_LIVE', title: 'Six roles. One reviewable production line.', subtitle: 'Business progress first; task digests, model snapshots, and runtime trace stay progressively disclosed. There is no publishing capability.',
    start: 'Create run', run: 'Run public-safe fault flight', running: 'Reading the PostgreSQL control plane…', retry: 'Reload control plane',
    choose: 'Choose this run mode', chooseDetail: 'Both modes share governance and audit semantics, but maturity and startup responsibility differ. A running Mission never switches modes.', mockTitle: 'Public-safe Mock rehearsal', mockDetail: 'Fully automated, no key. Verifies revisions, denial, correction, and re-audit; it is not real-model or real-AgentTeams evidence.', liveTitle: 'Live DeepSeek test run', liveDetail: 'Local UAT Canary pinned to deepseek-v4-flash. After creation, a Coordinator starts the pinned six-member Runner. The browser never receives the key and Live never falls back to Mock.', startMock: 'Create Mock Mission', startLive: 'Create Live UAT', localOnly: 'Local live-model UAT; a Coordinator must start the Runner. This is not an always-on service.', notPublished: 'Every artifact is an unpublished draft.', nextAction: 'Who acts next', waitingRunner: 'The Mission is persisted. Give the three public identifiers below to the Coordinator, who starts the Runner from a secure interactive terminal. Refreshing does not lose progress.', handoff: 'Public identifiers for the Coordinator', liveFailed: 'The Live run failed closed and did not switch to Mock. A Coordinator must inspect the Secret, Runner, or provider state before a controlled retry.', modelReceipts: 'Model receipts', noModelLeader: 'The Leader orchestrates only and never calls a model. Every domain task has a separate receipt.', technical: 'Open technical evidence',
    noMission: 'No Mission has started', noMissionDetail: 'Save the M1 Campaign first. The system freezes its exact digest before creating six distinct members.', prereq: 'Campaign prerequisites are incomplete',
    roster: 'Responsibility map', flow: 'Task flow', evidence: 'Evidence drawer', evidenceHint: 'Only allowlisted fields and digests appear—never prompts, keys, cookies, or raw Matrix messages.',
    reviewTitle: 'Audit desk', reviewLead: 'Inspect the rejected claim first, then compare the correction. The Auditor decides but cannot edit.', exactReview: 'Record exact Owner Review', reviewed: 'Recorded (non-executable)', changes: 'Revision changes',
    fail: 'Denied', pass: 'Pass', invalidated: 'Invalidated', nextRole: 'Next responsible role', boundEvidence: 'Bound Evidence', noGrant: 'Owner Review ≠ ActionGrant', noGrantDetail: 'This intent binds a Revision digest and account. It creates no Grant, connector, due execution, or publishing action.',
    truth: 'Boundary check', trace: 'Trace / ledger events', source: 'Campaign digest', team: '6 MEMBERS', version: 'AgentTeams v1.2.0', mock: 'This button runs public-safe MOCK_CONFORMANCE. Real AgentTeams acceptance evidence is labeled separately.',
    states: {QUEUED: 'Mock queued', WAITING_RUNTIME: 'Waiting for local Runner', RUNNING: 'Six-member run active', WAITING_DEPENDENCY: 'Waiting for dependency', NEEDS_OWNER_REVIEW: 'Exact Owner review needed', AWAITING_OWNER_REVIEW: 'Exact Owner review needed', FAILED: 'Failed closed', TIMED_OUT: 'Timed out', CANCELLED: 'Cancelled', UNKNOWN_RECOVERY: 'Unknown; recovering', AUDIT_BLOCKED: 'Audit blocked', REVISION_REQUIRED: 'Revision required', SHADOW_COMPLETE: 'SHADOW complete', COMPLETED_SHADOW: 'SHADOW complete'},
    roleNames: {'presence-mission-leader': 'Mission orchestration lead', 'evidence-claim-steward': 'Evidence & Claim Steward', 'campaign-planner': 'Campaign Planner', 'founder-identity-producer': 'Founder Content Producer', 'product-account-producer': 'Product Content Producer', 'independent-auditor': 'Independent Auditor', OWNER: 'Owner', COORDINATOR: 'Coordinator', CONTROL_PLANE: 'Control plane'},
    taskKinds: {PROJECT_COORDINATION: 'Coordinate Project', FREEZE_EVIDENCE: 'Freeze Claim / Evidence', PLAN_CAMPAIGN: 'Allocate Activation Plan', PRODUCE_FOUNDER: 'Produce founder first pass', PRODUCE_PRODUCT: 'Produce product first pass', AUDIT_REVISIONS: 'Independent first audit', PRODUCE_FOUNDER_CORRECTION: 'Correct rejected X Revision', REAUDIT_CORRECTION: 'Independently re-audit X v2'}
  }
} as const;

export function ShadowMissionWorkspace({locale, route, campaign, fixtureState}: {locale: AppLocale; route: 'mission' | 'review'; campaign?: CampaignEnvelope; fixtureState?: ShadowFixtureState}) {
  const t = text[locale]; const [mission, setMission] = useState<UiMission | undefined>(() => fixtureState === undefined ? undefined : fixtureMission(fixtureState));
  const [phase, setPhase] = useState<'loading' | 'ready' | 'working' | 'error'>(fixtureState === undefined ? 'loading' : 'ready'); const [error, setError] = useState<string>();
  const load = useCallback(async () => {
    if (fixtureState !== undefined || campaign === undefined) { setPhase('ready'); return; }
    setPhase('loading');
    try { const response = await api<{missions: UiMission[]}>(`/api/v1/campaigns/${campaign.document.id}/shadow-missions`, {headers: orgHeaders(campaign.document.organizationId)}); setMission(response.missions[0]); setPhase('ready'); setError(undefined); }
    catch (failure) { setError((failure as ApiError).code ?? 'CONTROL_PLANE_UNAVAILABLE'); setPhase('error'); }
  }, [campaign, fixtureState]);
  useEffect(() => { const timeout = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timeout); }, [load]);
  useEffect(() => {
    if (fixtureState !== undefined || campaign === undefined || mission?.providerMode !== 'LIVE_DEEPSEEK_UAT' || !['WAITING_RUNTIME', 'RUNNING', 'REVISION_REQUIRED', 'AUDIT_BLOCKED'].includes(mission.state)) return;
    const interval = window.setInterval(() => void api<{mission: UiMission}>(`/api/v1/shadow-missions/${mission.id}`, {headers: orgHeaders(campaign.document.organizationId)}).then((response) => { setMission(response.mission); setError(undefined); }).catch((failure: ApiError) => setError(failure.code ?? 'CONTROL_PLANE_UNAVAILABLE')), 3_000);
    return () => window.clearInterval(interval);
  }, [campaign, fixtureState, mission?.id, mission?.providerMode, mission?.state]);

  const start = useCallback(async (providerMode: 'PUBLIC_SAFE_MOCK' | 'LIVE_DEEPSEEK_UAT') => {
    if (campaign === undefined) return; setPhase('working');
    try { const response = await api<{mission: UiMission}>(`/api/v1/campaigns/${campaign.document.id}/shadow-missions`, {method: 'POST', headers: {...orgHeaders(campaign.document.organizationId), 'content-type': 'application/json', 'idempotency-key': `web-shadow-${crypto.randomUUID()}`, 'if-match': campaign.etag}, body: JSON.stringify({sourceDigest: campaign.digest, fault: 'BETA_TO_GA', providerMode, providerModel: 'deepseek-v4-flash'})}); setMission(response.mission); setPhase('ready'); }
    catch (failure) { setError((failure as ApiError).code); setPhase('error'); }
  }, [campaign]);
  const run = useCallback(async () => {
    if (campaign === undefined || mission === undefined) return; setPhase('working');
    try { const response = await api<{mission: UiMission}>(`/api/v1/shadow-missions/${mission.id}/public-safe-flight`, {method: 'POST', headers: {...orgHeaders(campaign.document.organizationId), 'idempotency-key': `web-flight-${crypto.randomUUID()}`, 'if-match': mission.etag}}); setMission(response.mission); setPhase('ready'); }
    catch (failure) { setError((failure as ApiError).code); setPhase('error'); }
  }, [campaign, mission]);
  const review = useCallback(async (revision: Revision) => {
    if (campaign === undefined || mission === undefined) return; setPhase('working');
    try { const response = await api<{mission: UiMission}>(`/api/v1/shadow-missions/${mission.id}/owner-reviews`, {method: 'POST', headers: {...orgHeaders(campaign.document.organizationId), 'content-type': 'application/json', 'idempotency-key': `web-review-${crypto.randomUUID()}`, 'if-match': mission.etag}, body: JSON.stringify({revisionId: revision.id, revisionDigest: revision.digest, decision: 'READY_FOR_FUTURE_EXECUTION'})}); setMission(response.mission); setPhase('ready'); }
    catch (failure) { setError((failure as ApiError).code); setPhase('error'); }
  }, [campaign, mission]);

  if (phase === 'loading') return <MissionEmpty title={t.running} detail={t.subtitle} state="RUNNING" />;
  if (phase === 'error') return <MissionEmpty title={t.states.FAILED} detail={error ?? 'CONTROL_PLANE_UNAVAILABLE'} state="FAILED"><button className="shadow-button" type="button" onClick={() => void load()}>{t.retry}</button></MissionEmpty>;
  if (fixtureState === 'prerequisite-blocked') return <MissionEmpty title={t.prereq} detail={t.noMissionDetail} state="PREREQUISITE_BLOCKED" />;
  if (campaign === undefined && fixtureState === undefined) return <MissionEmpty title={t.prereq} detail={t.noMissionDetail} state="PREREQUISITE_BLOCKED" />;
  if (mission === undefined) return <StartModePanel t={t} working={phase === 'working'} onStart={start} />;
  return route === 'review' ? <ReviewDesk mission={mission} t={t} working={phase === 'working'} onReview={review} /> : <MissionBoard mission={mission} t={t} working={phase === 'working'} onRun={run} fixture={fixtureState !== undefined} organizationId={campaign?.document.organizationId ?? 'fixture-organization'} />;
}

function MissionBoard({mission, t, working, onRun, fixture, organizationId}: {mission: UiMission; t: typeof text[AppLocale]; working: boolean; onRun: () => void; fixture: boolean; organizationId: string}) {
  return <section className="shadow-console" aria-label="Governed SHADOW Mission">
    <header className="shadow-console-head"><div><p>{fixture ? 'GOVERNED SHADOW / NOT_LIVE FIXTURE' : mission.providerMode === 'LIVE_DEEPSEEK_UAT' ? 'LIVE DEEPSEEK / LOCAL UAT' : t.eyebrow}</p><h2>{t.title}</h2><span>{t.subtitle}</span></div><div className="mission-pulse"><i /><strong>{stateLabel(mission.state, t)}</strong><small>{mission.providerMaturity} · NO EXTERNAL ACTION</small></div></header>
    <div className="mission-facts"><span>{t.team}</span><span>{t.version}</span><span>{mission.providerMode === 'LIVE_DEEPSEEK_UAT' ? `DeepSeek · ${mission.providerModel}` : 'PUBLIC_SAFE_MOCK'}</span><span>{t.source} <code>{mission.sourceCampaignDigest.slice(0, 12)}…</code></span></div>
    <section className="mission-brief"><span>00</span><div><strong>{t.nextAction}: {(t.roleNames as Record<string, string>)[mission.runtimeStatus.nextResponsible] ?? mission.runtimeStatus.nextResponsible}</strong><p>{mission.state === 'WAITING_RUNTIME' ? t.waitingRunner : mission.state === 'FAILED' ? t.liveFailed : t.notPublished}</p>{mission.providerMode === 'LIVE_DEEPSEEK_UAT' && <small>{t.localOnly}</small>}{mission.providerMode === 'LIVE_DEEPSEEK_UAT' && mission.state === 'WAITING_RUNTIME' && <dl className="runner-handoff"><dt>{t.handoff}</dt><dd>Organization ID <code>{organizationId}</code></dd><dd>Mission ID <code>{mission.id}</code></dd><dd>Campaign digest <code>{mission.sourceCampaignDigest}</code></dd></dl>}{mission.runtimeStatus.failure && <code>{mission.runtimeStatus.failure.code} · retryable={String(mission.runtimeStatus.failure.retryable)}</code>}</div></section>
    <section className="roster-section"><div className="section-label"><span>01</span><h3>{t.roster}</h3></div><div className="role-roster">{mission.roleContexts.map((role, index) => <article className={role.roleId === 'independent-auditor' ? 'role-card auditor' : 'role-card'} key={role.roleId}><span>{String(index + 1).padStart(2, '0')}</span><div><strong>{(t.roleNames as Record<string, string>)[role.roleId] ?? roleName(role.roleId)}</strong><p>{(t.taskKinds as Record<string, string>)[mission.tasks.find((task) => task.roleId === role.roleId)?.kind ?? ''] ?? role.responsibility}</p></div><small>{role.permissions.join(' · ')}</small>{role.orchestrationOnly && <em>ORCHESTRATION ONLY · NO MODEL CALL</em>}</article>)}</div></section>
    <section className="task-section"><div className="section-label"><span>02</span><h3>{t.flow}</h3></div><div className="task-flow">{mission.tasks.map((task) => <div className="task-node" data-state={task.state} key={task.id}><i /><span>{(t.taskKinds as Record<string, string>)[task.kind] ?? task.kind}</span><strong>{roleName(task.roleId)} · A{task.attempt}</strong><code>{taskState(task.state)} · {task.acceptedOutputDigest?.slice(0, 8) ?? 'waiting'}</code></div>)}</div></section>
    {mission.state === 'QUEUED' && mission.providerMode === 'PUBLIC_SAFE_MOCK' && <div className="flight-control"><button className="shadow-button signal" disabled={working} type="button" onClick={onRun}>{working ? t.running : t.run}</button><p>{t.mock}</p></div>}
    <NoActionProof mission={mission} t={t} />
    <EvidenceDrawer mission={mission} t={t} />
  </section>;
}

function StartModePanel({t, working, onStart}: {t: typeof text[AppLocale]; working: boolean; onStart: (mode: 'PUBLIC_SAFE_MOCK' | 'LIVE_DEEPSEEK_UAT') => void}) {
  return <section className="mode-choice" aria-label={t.choose}><header><span>GOVERNED SHADOW / NOT_LIVE</span><h2>{t.choose}</h2><p>{t.chooseDetail}</p></header><div><article><small>MOCK_CONFORMANCE</small><h3>{t.mockTitle}</h3><p>{t.mockDetail}</p><button disabled={working} type="button" onClick={() => onStart('PUBLIC_SAFE_MOCK')}>{t.startMock}</button></article><article className="live"><small>LIVE_PROVIDER_CANARY</small><h3>{t.liveTitle}</h3><p>{t.liveDetail}</p><button disabled={working} type="button" onClick={() => onStart('LIVE_DEEPSEEK_UAT')}>{t.startLive}</button></article></div><footer><strong>0 ActionGrant · 0 Connector · 0 External action</strong><span>{t.notPublished}</span></footer></section>;
}

function ReviewDesk({mission, t, working, onReview}: {mission: UiMission; t: typeof text[AppLocale]; working: boolean; onReview: (revision: Revision) => void}) {
  const current = latestPassing(mission); const denied = mission.revisions.find((item) => item.id === mission.fault.deniedRevisionId); const corrected = mission.revisions.find((item) => item.id === mission.fault.correctedRevisionId); const deniedAudit = mission.audits.find((item) => item.revisionId === denied?.id);
  return <section className="review-desk" aria-label="Independent Audit and exact Owner Review">
    <header className="review-desk-head"><div><p>{t.eyebrow}</p><h2>{t.reviewTitle}</h2><span>{t.reviewLead}</span></div><strong>{current.length}/4 PASS</strong></header>
    {denied !== undefined && deniedAudit !== undefined && <section className="fault-case"><div className="fault-flag"><span>AUDIT</span><strong>{t.fail}</strong><small>{deniedAudit.status === 'INVALIDATED' ? t.invalidated : deniedAudit.status}</small></div><div className="fault-copy"><p>{contentText(denied.content)}</p><code>{mission.fault.injectedPath}</code>{deniedAudit.issues.map((issue) => <div className="audit-reason" key={issue.code}><strong>{issue.code}</strong><span>{issue.message}</span><small>{t.nextRole}: {roleName(issue.nextResponsibleRoleId)} · {t.boundEvidence}: {issue.evidenceRefIds.length}</small></div>)}</div>{corrected !== undefined && <div className="revision-diff"><span>{t.changes}</span><del>{contentText(denied.content)}</del><ins>{contentText(corrected.content)}</ins><small>v1 → v2 · digest {corrected.digest.slice(0, 10)}…</small></div>}</section>}
    <div className="revision-grid">{current.map((revision) => { const review = mission.reviews.find((item) => item.revisionId === revision.id); return <article className="revision-card" key={revision.id}><header><span>{revision.platform === 'XIAOHONGSHU' ? '小红书' : revision.platform}</span><strong>v{revision.revision}</strong></header><p>{contentText(revision.content)}</p><dl><div><dt>Producer</dt><dd>{roleName(revision.producerRoleId)}</dd></div><div><dt>Audit</dt><dd>PASS</dd></div><div><dt>Digest</dt><dd><code>{revision.digest.slice(0, 12)}…</code></dd></div></dl><button className="review-action" disabled={working || review !== undefined} type="button" onClick={() => void onReview(revision)}>{review === undefined ? t.exactReview : t.reviewed}</button></article>; })}</div>
    <div className="review-boundary"><span>!</span><div><strong>{t.noGrant}</strong><p>{t.noGrantDetail}</p></div></div><NoActionProof mission={mission} t={t} /><EvidenceDrawer mission={mission} t={t} />
  </section>;
}

function NoActionProof({mission, t}: {mission: UiMission; t: typeof text[AppLocale]}) { return <section className="no-action-proof"><div className="section-label"><span>03</span><h3>{t.truth}</h3></div><div><span><strong>{mission.actionGrantCount}</strong> ActionGrant</span><span><strong>{mission.connectorCount}</strong> Connector</span><span><strong>{mission.externalActionCount}</strong> External action</span><span className="safe"><strong>FALSE</strong> executionAllowed</span></div></section>; }
function EvidenceDrawer({mission, t}: {mission: UiMission; t: typeof text[AppLocale]}) { return <details className="evidence-drawer"><summary><span>{t.technical}</span><small>{mission.trace.length} events · {mission.modelCalls.length} model receipts</small></summary><p>{t.evidenceHint}</p><h3>{t.modelReceipts}</h3><p>{t.noModelLeader}</p><div className="receipt-grid">{mission.modelCalls.map((call) => <article key={call.id}><strong>{mission.tasks.find((task) => task.id === call.taskId)?.kind ?? call.taskId}</strong><span>{call.provider} · {call.model}</span><small>{call.maturity} · {call.tokenUsage?.input ?? 0}+{call.tokenUsage?.output ?? 0} tokens · ${call.estimatedCostUsd ?? 0} · {call.latencyMs}ms</small><code>{call.error?.code ?? call.id.slice(0, 12)}</code></article>)}</div><ol>{mission.trace.map((event) => <li key={event.sequence}><span>{String(event.sequence).padStart(2, '0')}</span><strong>{event.businessLabel}</strong><code>{event.kind}</code></li>)}</ol></details>; }
function MissionEmpty({title, detail, state, children}: {title: string; detail: string; state: string; children?: React.ReactNode}) { return <section className="mission-empty"><span>GOVERNED SHADOW / NOT_LIVE · {state}</span><div><h2>{title}</h2><p>{detail}</p>{children}</div></section>; }

function fixtureMission(state: ShadowFixtureState): UiMission | undefined {
  if (state === 'empty' || state === 'prerequisite-blocked') return undefined; const mapped: Record<Exclude<ShadowFixtureState, 'empty' | 'prerequisite-blocked'>, string> = {queued: 'QUEUED', 'waiting-runtime': 'WAITING_RUNTIME', running: 'RUNNING', 'waiting-dependency': 'WAITING_DEPENDENCY', 'needs-owner': 'NEEDS_OWNER_REVIEW', failed: 'FAILED', 'timed-out': 'TIMED_OUT', cancelled: 'CANCELLED', 'unknown-recovery': 'UNKNOWN_RECOVERY', 'audit-blocked': 'AUDIT_BLOCKED', 'revision-required': 'REVISION_REQUIRED', 'shadow-complete': 'SHADOW_COMPLETE'};
  const roles = ['presence-mission-leader', 'evidence-claim-steward', 'campaign-planner', 'founder-identity-producer', 'product-account-producer', 'independent-auditor'];
  const taskDefinitions = [
    ['presence-mission-leader', 'PROJECT_COORDINATION', 1], ['evidence-claim-steward', 'FREEZE_EVIDENCE', 1], ['campaign-planner', 'PLAN_CAMPAIGN', 1],
    ['founder-identity-producer', 'PRODUCE_FOUNDER', 1], ['product-account-producer', 'PRODUCE_PRODUCT', 1], ['independent-auditor', 'AUDIT_REVISIONS', 1],
    ['founder-identity-producer', 'PRODUCE_FOUNDER_CORRECTION', 2], ['independent-auditor', 'REAUDIT_CORRECTION', 2]
  ] as const;
  const liveFixture = state === 'waiting-runtime';
  return {id: 'fixture-mission', state: mapped[state], etag: '"fixture"', runtimeVersion: 'v1.2.0', sourceCampaignDigest: 'a'.repeat(64), providerMode: liveFixture ? 'LIVE_DEEPSEEK_UAT' : 'PUBLIC_SAFE_MOCK', providerModel: 'deepseek-v4-flash', providerMaturity: liveFixture ? 'LIVE_PROVIDER_CANARY' : 'MOCK_CONFORMANCE', runtimeStatus: {nextResponsible: liveFixture ? 'COORDINATOR' : 'CONTROL_PLANE', failure: mapped[state] === 'FAILED' ? {code: 'FIXTURE_FAILED_CLOSED', retryable: true, failedTaskId: null, at: '2026-08-04T00:00:00Z'} : null, lastHeartbeatAt: null}, externalActionAllowed: false, actionGrantCount: 0, connectorCount: 0, externalActionCount: 0, roleContexts: roles.map((roleId, index) => ({roleId, identityId: `fixture-${index}`, responsibility: roleName(roleId), permissions: index === 0 ? ['ORCHESTRATE'] : index === 5 ? ['AUDIT'] : ['PRODUCE'], orchestrationOnly: index === 0, contextDigest: 'b'.repeat(64)})), tasks: taskDefinitions.map(([roleId, kind, attempt], index) => ({id: `task-${index}`, roleId, kind, attempt, state: index < 3 ? 'ACCEPTED' : mapped[state] === 'WAITING_DEPENDENCY' ? 'WAITING_DEPENDENCY' : 'RUNNING', prerequisiteTaskIds: [], acceptedOutputDigest: index < 3 ? 'c'.repeat(64) : null})), revisions: [], audits: [], reviews: [], modelCalls: [], trace: [{sequence: 1, kind: 'MISSION', businessLabel: 'SHADOW Mission fixture', detail: {}, createdAt: '2026-08-04T00:00:00Z'}], fault: {deniedRevisionId: null, correctedRevisionId: null, injectedPath: '/content/posts/0'}};
}

function latestPassing(mission: UiMission): Revision[] { return ['X', 'BLUESKY', 'LINKEDIN', 'XIAOHONGSHU'].flatMap((platform) => mission.revisions.filter((revision) => revision.platform === platform && mission.audits.some((audit) => audit.revisionId === revision.id && audit.status === 'ACTIVE' && audit.outcome === 'PASS')).sort((a, b) => b.revision - a.revision).slice(0, 1)); }
function stateLabel(state: string, t: typeof text[AppLocale]): string { return (t.states as Record<string, string>)[state] ?? state; }
function roleName(role: string): string { return ({'presence-mission-leader': 'Presence Mission Leader', 'evidence-claim-steward': 'Evidence & Claim Steward', 'campaign-planner': 'Campaign Planner', 'founder-identity-producer': 'Founder Identity Producer', 'product-account-producer': 'Product Account Producer', 'independent-auditor': 'Independent Auditor'} as Record<string, string>)[role] ?? role; }
function taskState(state: string): string { return state.replaceAll('_', ' ').toLowerCase(); }
function contentText(content: PlatformArtifact): string { switch (content.kind) { case 'X': case 'BLUESKY': return content.posts.join(' / '); case 'LINKEDIN': return content.commentary; case 'XIAOHONGSHU': return `${content.title} — ${content.body}`; } }
function orgHeaders(organizationId: string): Record<string, string> { return {'x-lumiclaw-organization-id': organizationId}; }
async function api<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(path, {...init, cache: 'no-store'}); const body = await response.json() as T & {code?: string}; if (!response.ok) { const error = new Error(body.code ?? `HTTP_${response.status}`) as ApiError; if (body.code !== undefined) error.code = body.code; throw error; } return body; }
