exports.up = (pgm) => {
  pgm.createTable('artifact_submission_quarantines_v3',{owner_profile_id:{type:'uuid',notNull:true,references:'local_owner_profiles',onDelete:'RESTRICT'},submission_id:{type:'text',notNull:true},activation_unit_id:{type:'text',notNull:true},reason_code:{type:'text',notNull:true},submission_digest:{type:'char(64)',notNull:true},payload:{type:'jsonb',notNull:true},created_at:{type:'timestamptz',notNull:true}},{constraints:{primaryKey:['owner_profile_id','submission_id']}});
  pgm.createTable('artifact_revisions_v3',{owner_profile_id:{type:'uuid',notNull:true,references:'local_owner_profiles',onDelete:'RESTRICT'},id:{type:'text',notNull:true},activation_unit_id:{type:'text',notNull:true},platform_code:{type:'text',notNull:true,check:"platform_code IN ('X','XIAOHONGSHU')"},revision:{type:'integer',notNull:true,check:'revision > 0'},parent_revision_id:{type:'text'},producer_identity_id:{type:'text',notNull:true},canonical_digest:{type:'char(64)',notNull:true},execution_bundle_id:{type:'text',notNull:true},execution_bundle_digest:{type:'char(64)',notNull:true},account_profile_revision_id:{type:'uuid',notNull:true},payload:{type:'jsonb',notNull:true},created_at:{type:'timestamptz',notNull:true}},{constraints:{primaryKey:['owner_profile_id','id'],foreignKeys:[{columns:['owner_profile_id','account_profile_revision_id'],references:'knowledge_profile_revisions(owner_profile_id,id)',onDelete:'RESTRICT'}]}});
  pgm.addConstraint('artifact_revisions_v3','artifact_revision_v3_unit_revision_unique',{unique:['owner_profile_id','activation_unit_id','revision']});
  pgm.addConstraint('artifact_revisions_v3','artifact_revision_v3_unit_digest_unique',{unique:['owner_profile_id','activation_unit_id','canonical_digest']});
  pgm.addConstraint('artifact_revisions_v3','artifact_revision_v3_exact_lineage_unique',{unique:['owner_profile_id','id','canonical_digest']});
  pgm.addConstraint('artifact_revisions_v3','artifact_revision_v3_parent_shape',{check:'(revision = 1 AND parent_revision_id IS NULL) OR (revision > 1 AND parent_revision_id IS NOT NULL)'});
  pgm.createTable('artifact_heads_v3',{owner_profile_id:{type:'uuid',notNull:true,references:'local_owner_profiles',onDelete:'RESTRICT'},activation_unit_id:{type:'text',notNull:true},revision_id:{type:'text',notNull:true},revision:{type:'integer',notNull:true},canonical_digest:{type:'char(64)',notNull:true},row_version:{type:'integer',notNull:true,check:'row_version > 0'},updated_at:{type:'timestamptz',notNull:true}},{constraints:{primaryKey:['owner_profile_id','activation_unit_id'],foreignKeys:[{columns:['owner_profile_id','revision_id'],references:'artifact_revisions_v3(owner_profile_id,id)',onDelete:'RESTRICT'}]}});
  pgm.createTable('artifact_audit_decisions_v3',{owner_profile_id:{type:'uuid',notNull:true},id:{type:'text',notNull:true},artifact_revision_id:{type:'text',notNull:true},artifact_revision_digest:{type:'char(64)',notNull:true},auditor_identity_id:{type:'text',notNull:true},result:{type:'text',notNull:true,check:"result IN ('PASS','FAIL','ESCALATE')"},canonical_digest:{type:'char(64)',notNull:true},payload:{type:'jsonb',notNull:true},created_at:{type:'timestamptz',notNull:true}},{constraints:{primaryKey:['owner_profile_id','id'],unique:['owner_profile_id','artifact_revision_id'],foreignKeys:[{columns:['owner_profile_id','artifact_revision_id','artifact_revision_digest'],references:'artifact_revisions_v3(owner_profile_id,id,canonical_digest)',onDelete:'RESTRICT'}]}});
  pgm.addConstraint('artifact_audit_decisions_v3','artifact_audit_v3_exact_lineage_unique',{unique:['owner_profile_id','id','artifact_revision_id','artifact_revision_digest','canonical_digest']});
  pgm.createTable('artifact_owner_decisions_v3',{owner_profile_id:{type:'uuid',notNull:true},id:{type:'text',notNull:true},artifact_revision_id:{type:'text',notNull:true},artifact_revision_digest:{type:'char(64)',notNull:true},audit_decision_id:{type:'text',notNull:true},audit_decision_digest:{type:'char(64)',notNull:true},result:{type:'text',notNull:true,check:"result IN ('APPROVE','REJECT')"},canonical_digest:{type:'char(64)',notNull:true},payload:{type:'jsonb',notNull:true},created_at:{type:'timestamptz',notNull:true}},{constraints:{primaryKey:['owner_profile_id','id'],unique:['owner_profile_id','artifact_revision_id'],foreignKeys:[{columns:['owner_profile_id','artifact_revision_id','artifact_revision_digest'],references:'artifact_revisions_v3(owner_profile_id,id,canonical_digest)',onDelete:'RESTRICT'},{columns:['owner_profile_id','audit_decision_id','artifact_revision_id','artifact_revision_digest','audit_decision_digest'],references:'artifact_audit_decisions_v3(owner_profile_id,id,artifact_revision_id,artifact_revision_digest,canonical_digest)',onDelete:'RESTRICT'}]}});
  pgm.addConstraint('artifact_owner_decisions_v3','artifact_owner_decision_v3_exact_lineage_unique',{unique:['owner_profile_id','id','artifact_revision_id','artifact_revision_digest','audit_decision_id','audit_decision_digest','canonical_digest']});
  pgm.createTable('artifact_regeneration_requests_v3',{owner_profile_id:{type:'uuid',notNull:true},id:{type:'text',notNull:true},artifact_revision_id:{type:'text',notNull:true},artifact_revision_digest:{type:'char(64)',notNull:true},canonical_digest:{type:'char(64)',notNull:true},payload:{type:'jsonb',notNull:true},created_at:{type:'timestamptz',notNull:true}},{constraints:{primaryKey:['owner_profile_id','id'],foreignKeys:[{columns:['owner_profile_id','artifact_revision_id'],references:'artifact_revisions_v3(owner_profile_id,id)',onDelete:'RESTRICT'}]}});
  pgm.createTable('manual_publish_packages_v3',{owner_profile_id:{type:'uuid',notNull:true},id:{type:'text',notNull:true},artifact_revision_id:{type:'text',notNull:true},artifact_revision_digest:{type:'char(64)',notNull:true},audit_decision_id:{type:'text',notNull:true},audit_decision_digest:{type:'char(64)',notNull:true},owner_decision_id:{type:'text',notNull:true},owner_decision_digest:{type:'char(64)',notNull:true},exact_input_digest:{type:'char(64)',notNull:true},manifest_digest:{type:'char(64)',notNull:true},platform_code:{type:'text',notNull:true,check:"platform_code IN ('X','XIAOHONGSHU')"},payload:{type:'jsonb',notNull:true},created_at:{type:'timestamptz',notNull:true}},{constraints:{primaryKey:['owner_profile_id','id'],unique:['owner_profile_id','exact_input_digest'],foreignKeys:[{columns:['owner_profile_id','artifact_revision_id','artifact_revision_digest'],references:'artifact_revisions_v3(owner_profile_id,id,canonical_digest)',onDelete:'RESTRICT'},{columns:['owner_profile_id','audit_decision_id','artifact_revision_id','artifact_revision_digest','audit_decision_digest'],references:'artifact_audit_decisions_v3(owner_profile_id,id,artifact_revision_id,artifact_revision_digest,canonical_digest)',onDelete:'RESTRICT'},{columns:['owner_profile_id','owner_decision_id','artifact_revision_id','artifact_revision_digest','audit_decision_id','audit_decision_digest','owner_decision_digest'],references:'artifact_owner_decisions_v3(owner_profile_id,id,artifact_revision_id,artifact_revision_digest,audit_decision_id,audit_decision_digest,canonical_digest)',onDelete:'RESTRICT'}]}});
  pgm.createTable('manual_publish_package_files_v3',{owner_profile_id:{type:'uuid',notNull:true},package_id:{type:'text',notNull:true},position:{type:'integer',notNull:true,check:'position > 0'},file_name:{type:'text',notNull:true},media_type:{type:'text',notNull:true},content_digest:{type:'char(64)',notNull:true},content:{type:'text',notNull:true}},{constraints:{primaryKey:['owner_profile_id','package_id','position'],unique:['owner_profile_id','package_id','file_name'],foreignKeys:[{columns:['owner_profile_id','package_id'],references:'manual_publish_packages_v3(owner_profile_id,id)',onDelete:'RESTRICT'}]}});
  pgm.createTable('manual_publish_helper_events_v3',{owner_profile_id:{type:'uuid',notNull:true},id:{type:'text',notNull:true},package_id:{type:'text',notNull:true},action:{type:'text',notNull:true,check:"action IN ('COPY_TEXT','DOWNLOAD_PACKAGE','OPEN_OFFICIAL_PUBLISH_PAGE')"},external_state:{type:'text',notNull:true,check:"external_state = 'UNVERIFIED_EXTERNAL_STATE'"},canonical_digest:{type:'char(64)',notNull:true},payload:{type:'jsonb',notNull:true},created_at:{type:'timestamptz',notNull:true}},{constraints:{primaryKey:['owner_profile_id','id'],foreignKeys:[{columns:['owner_profile_id','package_id'],references:'manual_publish_packages_v3(owner_profile_id,id)',onDelete:'RESTRICT'}]}});
  pgm.createTable('artifact_invalidation_events_v3',{owner_profile_id:{type:'uuid',notNull:true},id:{type:'text',notNull:true},artifact_revision_id:{type:'text',notNull:true},reason_code:{type:'text',notNull:true},previous_digest:{type:'char(64)',notNull:true},current_digest:{type:'char(64)',notNull:true},canonical_digest:{type:'char(64)',notNull:true},payload:{type:'jsonb',notNull:true},created_at:{type:'timestamptz',notNull:true}},{constraints:{primaryKey:['owner_profile_id','id'],unique:['owner_profile_id','artifact_revision_id','reason_code','current_digest'],foreignKeys:[{columns:['owner_profile_id','artifact_revision_id'],references:'artifact_revisions_v3(owner_profile_id,id)',onDelete:'RESTRICT'}]}});
  pgm.createTable('artifact_publish_idempotency_v3',{owner_profile_id:{type:'uuid',notNull:true,references:'local_owner_profiles',onDelete:'RESTRICT'},route:{type:'text',notNull:true},idempotency_key:{type:'text',notNull:true},request_digest:{type:'char(64)',notNull:true},response_body:{type:'jsonb',notNull:true},created_at:{type:'timestamptz',notNull:true}},{constraints:{primaryKey:['owner_profile_id','route','idempotency_key']}});
  pgm.sql(`
    CREATE FUNCTION reject_sdd010_authority_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'SDD010_APPEND_ONLY_AUTHORITY'; END $$;
    CREATE TRIGGER artifact_submission_quarantines_v3_immutable BEFORE UPDATE OR DELETE ON artifact_submission_quarantines_v3 FOR EACH ROW EXECUTE FUNCTION reject_sdd010_authority_mutation();
    CREATE TRIGGER artifact_revisions_v3_immutable BEFORE UPDATE OR DELETE ON artifact_revisions_v3 FOR EACH ROW EXECUTE FUNCTION reject_sdd010_authority_mutation();
    CREATE TRIGGER artifact_audit_decisions_v3_immutable BEFORE UPDATE OR DELETE ON artifact_audit_decisions_v3 FOR EACH ROW EXECUTE FUNCTION reject_sdd010_authority_mutation();
    CREATE TRIGGER artifact_owner_decisions_v3_immutable BEFORE UPDATE OR DELETE ON artifact_owner_decisions_v3 FOR EACH ROW EXECUTE FUNCTION reject_sdd010_authority_mutation();
    CREATE TRIGGER artifact_regeneration_requests_v3_immutable BEFORE UPDATE OR DELETE ON artifact_regeneration_requests_v3 FOR EACH ROW EXECUTE FUNCTION reject_sdd010_authority_mutation();
    CREATE TRIGGER manual_publish_packages_v3_immutable BEFORE UPDATE OR DELETE ON manual_publish_packages_v3 FOR EACH ROW EXECUTE FUNCTION reject_sdd010_authority_mutation();
    CREATE TRIGGER manual_publish_package_files_v3_immutable BEFORE UPDATE OR DELETE ON manual_publish_package_files_v3 FOR EACH ROW EXECUTE FUNCTION reject_sdd010_authority_mutation();
    CREATE TRIGGER manual_publish_helper_events_v3_immutable BEFORE UPDATE OR DELETE ON manual_publish_helper_events_v3 FOR EACH ROW EXECUTE FUNCTION reject_sdd010_authority_mutation();
    CREATE TRIGGER artifact_invalidation_events_v3_immutable BEFORE UPDATE OR DELETE ON artifact_invalidation_events_v3 FOR EACH ROW EXECUTE FUNCTION reject_sdd010_authority_mutation();
    CREATE TRIGGER artifact_publish_idempotency_v3_immutable BEFORE UPDATE OR DELETE ON artifact_publish_idempotency_v3 FOR EACH ROW EXECUTE FUNCTION reject_sdd010_authority_mutation();
  `);
};

exports.down = (pgm) => {
  pgm.sql(`DO $$ BEGIN IF (SELECT (SELECT count(*) FROM artifact_submission_quarantines_v3)+(SELECT count(*) FROM artifact_revisions_v3)+(SELECT count(*) FROM artifact_audit_decisions_v3)+(SELECT count(*) FROM artifact_owner_decisions_v3)+(SELECT count(*) FROM artifact_regeneration_requests_v3)+(SELECT count(*) FROM manual_publish_packages_v3)+(SELECT count(*) FROM manual_publish_helper_events_v3)+(SELECT count(*) FROM artifact_invalidation_events_v3)+(SELECT count(*) FROM artifact_publish_idempotency_v3)) > 0 THEN RAISE EXCEPTION 'SDD010_DOWN_BLOCKED_DATA_EXPORT_AND_OWNER_DECISION_REQUIRED'; END IF; END $$;`);
  for(const table of ['artifact_submission_quarantines_v3','artifact_revisions_v3','artifact_audit_decisions_v3','artifact_owner_decisions_v3','artifact_regeneration_requests_v3','manual_publish_packages_v3','manual_publish_package_files_v3','manual_publish_helper_events_v3','artifact_invalidation_events_v3','artifact_publish_idempotency_v3'])pgm.sql(`DROP TRIGGER IF EXISTS ${table}_immutable ON ${table}`);
  pgm.sql('DROP FUNCTION IF EXISTS reject_sdd010_authority_mutation()');
  for(const table of ['artifact_publish_idempotency_v3','artifact_invalidation_events_v3','manual_publish_helper_events_v3','manual_publish_package_files_v3','manual_publish_packages_v3','artifact_regeneration_requests_v3','artifact_owner_decisions_v3','artifact_audit_decisions_v3','artifact_heads_v3','artifact_revisions_v3','artifact_submission_quarantines_v3'])pgm.dropTable(table);
};
