import {
  buildManualPublishPackage,controlledAuditFindings,createArtifactAuditDecision,createArtifactOwnerDecision,createArtifactRevision,createControlledProducerSubmission,sha256Digest,
  type ArtifactAuditDecision,type ArtifactOwnerDecision,type ArtifactRevisionV3,type ManualPublishPackage,type MissionExecutionBundle
} from '@lumiclaw/domain';

export const authorityOwnerId='018f47a1-aaaa-7aaa-8aaa-aaaaaaaaaaaa';
export const authorityAccountId='018f47a1-bbbb-7bbb-8bbb-bbbbbbbbbbbb';
export const authoritySnapshotId='018f47a1-cccc-7ccc-8ccc-cccccccccccc';
export const authorityNow='2026-08-23T01:00:00.000Z';

export function authorityBundle():MissionExecutionBundle{
  const digest=(value:string)=>sha256Digest(value);const account={accountProfileRevisionId:authorityAccountId,revision:1,digest:digest('authority-account'),platformCode:'X' as const,handleOrDisplayName:'@authority-fixture',producerMandates:['FOUNDER_VOICE' as const],targetMarket:'US',contentLocale:'en-US'};
  const units=[1,2,3].map((ordinal)=>({activationUnitId:`authority-unit-${ordinal}`,slotId:`authority-slot-${ordinal}`,localDate:`2026-08-${23+ordinal}`,localTime:'09:30',platformCode:'X' as const,accountProfileRevisionId:authorityAccountId,producerRole:'founder-identity-producer' as const,contentObjective:`Explain exact repository authority ${ordinal}.`,sourceItemIds:[`authority-source-${ordinal}`],claimConstraints:['No external publication claim.']}));
  const inputBindings={knowledgeSnapshot:{id:authoritySnapshotId,digest:digest('authority-knowledge'),state:'APPROVED' as const},operatingGoal:{id:'authority-goal',revision:1,digest:digest('authority-goal'),state:'ACTIVE' as const},accountProfiles:[account],compiler:{version:'selected-platform-compiler.v2',digest:digest('authority-compiler')},teamProfile:{id:'authority-team',version:'2',digest:digest('authority-team'),runtimeCompatibility:'agentteams-v1.2.0'},plannerOutputSchema:{id:'lumiclaw.content-plan.v2' as const,digest:digest('authority-schema')},approvedPlan:{id:'authority-plan',revision:1,digest:digest('authority-plan')}};
  const base={schemaVersion:2 as const,kind:'MISSION_EXECUTION' as const,missionIntentId:'authority-mission',ownerId:authorityOwnerId,bundleId:'authority-execution',generation:2,parentBundleId:'authority-intent',parentBundleDigest:digest('authority-intent'),approvedPlanId:'authority-plan',approvedPlanRevision:1,approvedPlanDigest:digest('authority-plan'),state:'COMPILED' as const,compilerVersion:'selected-platform-compiler.v2',inputBindings,roles:[],roleContexts:[],skillLocks:[],selectedPlatforms:['X' as const],activationUnits:units,currentBrief:{briefId:'authority-brief',slotId:units[0]!.slotId,platformCode:'X' as const,accountProfileRevisionId:authorityAccountId,producerRole:'founder-identity-producer' as const,theme:'Authority',contentObjective:units[0]!.contentObjective,sourceItemIds:units[0]!.sourceItemIds,claimConstraints:units[0]!.claimConstraints},tasks:[],dependencyDag:[],expectedArtifactSchemas:[{platformCode:'X' as const,schemaRef:'lumiclaw.artifact.x.v3',contractStatus:'SDD_010_REQUIRED' as const}],trace:[],evidenceContract:{agentTeamsExecuted:false as const,fixtureAllowed:true as const,externalActionAllowed:false as const}};
  return {...base,canonicalDigest:sha256Digest(base)};
}

export function authorityRevision(bundle:MissionExecutionBundle,index:number):ArtifactRevisionV3{const unit=bundle.activationUnits[index];if(unit===undefined)throw new Error('AUTHORITY_UNIT_MISSING');const submission=createControlledProducerSubmission(bundle,unit,{xMode:'SINGLE',submittedAt:authorityNow});return createArtifactRevision({ownerId:authorityOwnerId,submission,bundle,revision:1,parentRevisionId:null,createdAt:authorityNow});}
export function authorityAudit(revision:ArtifactRevisionV3,index:number,result:'PASS'|'FAIL'|'ESCALATE'='PASS'):ArtifactAuditDecision{return createArtifactAuditDecision({ownerId:authorityOwnerId,revision,auditorIdentityId:`authority-auditor-${index}`,result,findings:controlledAuditFindings(result),evidenceBindings:[revision.inputBindings.knowledgeSnapshot.digest],createdAt:`2026-08-23T01:0${index}:00.000Z`});}
export function authorityDecision(revision:ArtifactRevisionV3,audit:ArtifactAuditDecision,index:number,result:'APPROVE'|'REJECT'='APPROVE'):ArtifactOwnerDecision{return createArtifactOwnerDecision({ownerId:authorityOwnerId,revision,audit,result,ownerIdentityId:authorityOwnerId,decidedAt:`2026-08-23T01:1${index}:00.000Z`});}
export function authorityPackage(revision:ArtifactRevisionV3,audit:ArtifactAuditDecision,decision:ArtifactOwnerDecision,index:number):ManualPublishPackage{return buildManualPublishPackage({ownerId:authorityOwnerId,revision,audit,decision,createdAt:`2026-08-23T01:2${index}:00.000Z`});}
