import {PostgresArtifactPublishRepository} from '@lumiclaw/db';
import {sha256Digest,type ArtifactAuditDecision,type ArtifactOwnerDecision,type ManualPublishPackage} from '@lumiclaw/domain';
import {Pool} from 'pg';
import {describe,expect,it} from 'vitest';
import {
  authorityAccountId,authorityAudit,authorityBundle,authorityDecision,authorityNow,authorityOwnerId,authorityPackage,authorityRevision,authoritySnapshotId
} from './artifact-publish-test-fixture.js';

const connectionString=process.env.SDD010_POSTGRES_AUTHORITY_URL;
const suite=connectionString===undefined?describe.skip:describe;

suite('SDD-010 fresh PostgreSQL artifact authority regressions',()=>{
  it('rejects malformed/cross-revision authority and serializes same-key and exact-package concurrency',async()=>{
    const bundle=authorityBundle();const first=authorityRevision(bundle,0);const second=authorityRevision(bundle,1);const third=authorityRevision(bundle,2);const probe=new Pool({connectionString:connectionString!});await seedAuthority(probe,bundle);
    let repository=new PostgresArtifactPublishRepository(connectionString!);try{
    await repository.appendRevision(authorityOwnerId,first,null,'pg-revision-first',new Date(authorityNow));await repository.appendRevision(authorityOwnerId,second,null,'pg-revision-second',new Date(authorityNow));await repository.appendRevision(authorityOwnerId,third,null,'pg-revision-third',new Date(authorityNow));

    const firstAudit=authorityAudit(first,1);const sameKey=await Promise.all([repository.appendAudit(authorityOwnerId,firstAudit,first.canonicalDigest,'pg-audit-same-key',new Date(authorityNow)),repository.appendAudit(authorityOwnerId,firstAudit,first.canonicalDigest,'pg-audit-same-key',new Date(authorityNow))]);expect(sameKey.map((item)=>item.replayed).sort()).toEqual([false,true]);
    await repository.close();repository=new PostgresArtifactPublishRepository(connectionString!);expect((await repository.appendAudit(authorityOwnerId,firstAudit,first.canonicalDigest,'pg-audit-same-key',new Date(authorityNow))).replayed).toBe(true);

    const secondAudit=authorityAudit(second,2);const duplicateFinding={...secondAudit,findings:[...secondAudit.findings,{...secondAudit.findings[0]!}]} as ArtifactAuditDecision;await expect(repository.appendAudit(authorityOwnerId,duplicateFinding,second.canonicalDigest,'pg-audit-duplicate',new Date(authorityNow))).rejects.toMatchObject({code:'AUDIT_FINDINGS_INCOMPLETE'});const policyMismatch={...secondAudit,policyDigest:'0'.repeat(64)} as ArtifactAuditDecision;await expect(repository.appendAudit(authorityOwnerId,policyMismatch,second.canonicalDigest,'pg-audit-policy',new Date(authorityNow))).rejects.toMatchObject({code:'ARTIFACT_INPUT_MISMATCH'});await repository.appendAudit(authorityOwnerId,secondAudit,second.canonicalDigest,'pg-audit-second',new Date(authorityNow));
    const failedAudit=authorityAudit(third,3,'FAIL');await repository.appendAudit(authorityOwnerId,failedAudit,third.canonicalDigest,'pg-audit-failed',new Date(authorityNow));const validReject=authorityDecision(third,failedAudit,3,'REJECT');const forbiddenApprove={...validReject,result:'APPROVE'} as ArtifactOwnerDecision;await expect(repository.appendOwnerDecision(authorityOwnerId,forbiddenApprove,failedAudit.canonicalDigest,'pg-approve-failed',new Date(authorityNow))).rejects.toMatchObject({code:'AUDIT_PASS_REQUIRED'});

    const firstDecision=authorityDecision(first,firstAudit,1);const repositoryCrossDecision={...firstDecision,artifactRevisionId:second.id,artifactRevisionDigest:second.canonicalDigest} as ArtifactOwnerDecision;await expect(repository.appendOwnerDecision(authorityOwnerId,repositoryCrossDecision,firstAudit.canonicalDigest,'pg-decision-cross-repository',new Date(authorityNow))).rejects.toMatchObject({code:'OWNER_DECISION_STALE'});
    await expectForeignKey(probe.query(`insert into artifact_owner_decisions_v3(owner_profile_id,id,artifact_revision_id,artifact_revision_digest,audit_decision_id,audit_decision_digest,result,canonical_digest,payload,created_at) values($1,$2,$3,$4,$5,$6,'APPROVE',$7,$8::jsonb,$9)`,[authorityOwnerId,'pg-cross-decision',second.id,second.canonicalDigest,firstAudit.id,firstAudit.canonicalDigest,sha256Digest('pg-cross-decision'),JSON.stringify({classification:'PUBLIC_SAFE_SYNTHETIC'}),authorityNow]));
    await repository.appendOwnerDecision(authorityOwnerId,firstDecision,firstAudit.canonicalDigest,'pg-decision-first',new Date(authorityNow));const secondDecision=authorityDecision(second,secondAudit,2);await repository.appendOwnerDecision(authorityOwnerId,secondDecision,secondAudit.canonicalDigest,'pg-decision-second',new Date(authorityNow));

    const pack=authorityPackage(second,secondAudit,secondDecision,2);const repositoryCrossPackage={...pack,auditDecisionId:firstAudit.id,auditDecisionDigest:firstAudit.canonicalDigest} as ManualPublishPackage;await expect(repository.appendPackage(authorityOwnerId,repositoryCrossPackage,secondDecision.canonicalDigest,'pg-package-cross-repository',new Date(authorityNow))).rejects.toMatchObject({code:'PACKAGE_INPUT_INVALIDATED'});
    await expectForeignKey(probe.query(`insert into manual_publish_packages_v3(owner_profile_id,id,artifact_revision_id,artifact_revision_digest,audit_decision_id,audit_decision_digest,owner_decision_id,owner_decision_digest,exact_input_digest,manifest_digest,platform_code,payload,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'X',$11::jsonb,$12)`,[authorityOwnerId,'pg-cross-package',second.id,second.canonicalDigest,firstAudit.id,firstAudit.canonicalDigest,secondDecision.id,secondDecision.canonicalDigest,sha256Digest('pg-cross-package-input'),sha256Digest('pg-cross-package-manifest'),JSON.stringify({classification:'PUBLIC_SAFE_SYNTHETIC'}),authorityNow]));

    const distinctKeys=await Promise.all([repository.appendPackage(authorityOwnerId,pack,secondDecision.canonicalDigest,'pg-package-distinct-key-a',new Date(authorityNow)),repository.appendPackage(authorityOwnerId,pack,secondDecision.canonicalDigest,'pg-package-distinct-key-b',new Date(authorityNow))]);expect(distinctKeys.map((item)=>item.replayed).sort()).toEqual([false,true]);expect(distinctKeys[0]!.package).toEqual(distinctKeys[1]!.package);
    await repository.close();repository=new PostgresArtifactPublishRepository(connectionString!);expect((await repository.appendPackage(authorityOwnerId,pack,secondDecision.canonicalDigest,'pg-package-distinct-key-a',new Date(authorityNow))).replayed).toBe(true);

    const rows=(await probe.query<{revisions:string;audits:string;decisions:string;packages:string;files:string;idempotency:string}>(`select (select count(*) from artifact_revisions_v3)::text revisions,(select count(*) from artifact_audit_decisions_v3)::text audits,(select count(*) from artifact_owner_decisions_v3)::text decisions,(select count(*) from manual_publish_packages_v3)::text packages,(select count(*) from manual_publish_package_files_v3)::text files,(select count(*) from artifact_publish_idempotency_v3)::text idempotency`)).rows[0];expect(rows).toEqual({revisions:'3',audits:'3',decisions:'2',packages:'1',files:'4',idempotency:'10'});expect((await repository.getWorkspace(authorityOwnerId)).packages).toHaveLength(1);
    }finally{await repository.close();await probe.end();}
  },60_000);
});

async function seedAuthority(pool:Pool,bundle:ReturnType<typeof authorityBundle>):Promise<void>{
  const now=authorityNow;await pool.query(`insert into local_owner_profiles(id,singleton_key,schema_version,display_name,state,created_at,updated_at) values($1,true,1,'Public-safe Authority Owner','PROFILE_READY',$2,$2)`,[authorityOwnerId,now]);
  await pool.query(`insert into knowledge_snapshots(owner_profile_id,id,version,state,session_row_version,canonical_digest,source_revision_digests,profile_revision_digests,item_bindings,conflict_decisions,gaps,approved_by,approved_at,created_at) values($1,$2,1,'APPROVED',1,$3,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,$1,$4,$4)`,[authorityOwnerId,authoritySnapshotId,bundle.inputBindings.knowledgeSnapshot.digest,now]);
  const account=bundle.inputBindings.accountProfiles[0]!;await pool.query(`insert into knowledge_profile_revisions(owner_profile_id,id,kind,platform_code,version,digest,payload,created_at) values($1,$2,'ACCOUNT','X',1,$3,$4::jsonb,$5)`,[authorityOwnerId,authorityAccountId,account.digest,JSON.stringify({classification:'PUBLIC_SAFE_SYNTHETIC'}),now]);
  await pool.query(`insert into operating_goal_revisions(owner_profile_id,goal_id,revision,state,canonical_digest,parent_digest,knowledge_snapshot_id,knowledge_snapshot_digest,selected_account_ids,payload,created_at) values($1,$2,1,'ACTIVE',$3,null,$4,$5,$6::jsonb,$7::jsonb,$8)`,[authorityOwnerId,bundle.inputBindings.operatingGoal.id,bundle.inputBindings.operatingGoal.digest,authoritySnapshotId,bundle.inputBindings.knowledgeSnapshot.digest,JSON.stringify([authorityAccountId]),JSON.stringify({classification:'PUBLIC_SAFE_SYNTHETIC'}),now]);
  await pool.query(`insert into mission_bundle_generations_v2(owner_profile_id,bundle_id,mission_intent_id,generation,kind,canonical_digest,compiler_version,parent_bundle_id,goal_id,goal_revision,goal_digest,plan_id,plan_revision,plan_digest,payload,created_at) values($1,$2,$3,2,'MISSION_EXECUTION',$4,$5,$6,$7,1,$8,$9,1,$10,$11::jsonb,$12)`,[authorityOwnerId,bundle.bundleId,bundle.missionIntentId,bundle.canonicalDigest,bundle.compilerVersion,bundle.parentBundleId,bundle.inputBindings.operatingGoal.id,bundle.inputBindings.operatingGoal.digest,bundle.approvedPlanId,bundle.approvedPlanDigest,JSON.stringify(bundle),now]);
}

async function expectForeignKey(operation:Promise<unknown>):Promise<void>{await expect(operation).rejects.toMatchObject({code:'23503'});}
