import {ArtifactContractError,type ArtifactAuditDecision,type ArtifactOwnerDecision,type ManualPublishPackage} from '@lumiclaw/domain';
import {describe,expect,it} from 'vitest';
import {MemoryArtifactPublishRepository} from './memory-artifact-publish-repository.js';
import {authorityAudit,authorityBundle,authorityDecision,authorityNow,authorityOwnerId,authorityPackage,authorityRevision} from './artifact-publish-test-fixture.js';

describe('SDD-010 Memory repository authority',()=>{
  it('revalidates audit, decision and package lineage instead of trusting typed callers',async()=>{
    const repository=new MemoryArtifactPublishRepository();const bundle=authorityBundle();const first=authorityRevision(bundle,0);const second=authorityRevision(bundle,1);const third=authorityRevision(bundle,2);await repository.appendRevision(authorityOwnerId,first,null,'memory-revision-first',new Date(authorityNow));await repository.appendRevision(authorityOwnerId,second,null,'memory-revision-second',new Date(authorityNow));await repository.appendRevision(authorityOwnerId,third,null,'memory-revision-third',new Date(authorityNow));
    const validAudit=authorityAudit(first,1);const sameProducer={...validAudit,auditorIdentityId:first.producerIdentityId} as ArtifactAuditDecision;await expect(repository.appendAudit(authorityOwnerId,sameProducer,first.canonicalDigest,'memory-audit-producer',new Date(authorityNow))).rejects.toMatchObject({code:'AUDITOR_INDEPENDENCE_REQUIRED'});
    const malformedFinding={...validAudit,findings:[null]} as unknown as ArtifactAuditDecision;await expect(repository.appendAudit(authorityOwnerId,malformedFinding,first.canonicalDigest,'memory-audit-malformed',new Date(authorityNow))).rejects.toMatchObject({code:'ARTIFACT_SCHEMA_INVALID'});
    const duplicateFinding={...validAudit,findings:[...validAudit.findings,{...validAudit.findings[0]!}]} as ArtifactAuditDecision;await expect(repository.appendAudit(authorityOwnerId,duplicateFinding,first.canonicalDigest,'memory-audit-duplicate',new Date(authorityNow))).rejects.toMatchObject({code:'AUDIT_FINDINGS_INCOMPLETE'});
    const resultMismatch={...validAudit,result:'FAIL'} as ArtifactAuditDecision;await expect(repository.appendAudit(authorityOwnerId,resultMismatch,first.canonicalDigest,'memory-audit-result',new Date(authorityNow))).rejects.toMatchObject({code:'AUDIT_FINDINGS_INCOMPLETE'});const policyMismatch={...validAudit,policyDigest:'0'.repeat(64)} as ArtifactAuditDecision;await expect(repository.appendAudit(authorityOwnerId,policyMismatch,first.canonicalDigest,'memory-audit-policy',new Date(authorityNow))).rejects.toMatchObject({code:'ARTIFACT_INPUT_MISMATCH'});const canonicalMismatch={...validAudit,canonicalDigest:'0'.repeat(64)} as ArtifactAuditDecision;await expect(repository.appendAudit(authorityOwnerId,canonicalMismatch,first.canonicalDigest,'memory-audit-canonical',new Date(authorityNow))).rejects.toMatchObject({code:'ARTIFACT_INPUT_MISMATCH'});
    const [original,replay]=await Promise.all([repository.appendAudit(authorityOwnerId,validAudit,first.canonicalDigest,'memory-audit-same-key',new Date(authorityNow)),repository.appendAudit(authorityOwnerId,validAudit,first.canonicalDigest,'memory-audit-same-key',new Date(authorityNow))]);expect([original.replayed,replay.replayed].sort()).toEqual([false,true]);
    const secondAudit=authorityAudit(second,2);await repository.appendAudit(authorityOwnerId,secondAudit,second.canonicalDigest,'memory-audit-second',new Date(authorityNow));
    const failedAudit=authorityAudit(third,3,'FAIL');await repository.appendAudit(authorityOwnerId,failedAudit,third.canonicalDigest,'memory-audit-failed',new Date(authorityNow));const validReject=authorityDecision(third,failedAudit,3,'REJECT');const forbiddenApprove={...validReject,result:'APPROVE'} as ArtifactOwnerDecision;await expect(repository.appendOwnerDecision(authorityOwnerId,forbiddenApprove,failedAudit.canonicalDigest,'memory-approve-failed',new Date(authorityNow))).rejects.toMatchObject({code:'AUDIT_PASS_REQUIRED'});
    const validDecision=authorityDecision(first,validAudit,1);const crossDecision={...validDecision,artifactRevisionId:second.id,artifactRevisionDigest:second.canonicalDigest} as ArtifactOwnerDecision;await expect(repository.appendOwnerDecision(authorityOwnerId,crossDecision,validAudit.canonicalDigest,'memory-decision-cross',new Date(authorityNow))).rejects.toBeInstanceOf(ArtifactContractError);await repository.appendOwnerDecision(authorityOwnerId,validDecision,validAudit.canonicalDigest,'memory-decision-first',new Date(authorityNow));
    const secondDecision=authorityDecision(second,secondAudit,2);await repository.appendOwnerDecision(authorityOwnerId,secondDecision,secondAudit.canonicalDigest,'memory-decision-second',new Date(authorityNow));const validPackage=authorityPackage(second,secondAudit,secondDecision,2);const crossPackage={...validPackage,auditDecisionId:validAudit.id,auditDecisionDigest:validAudit.canonicalDigest} as ManualPublishPackage;await expect(repository.appendPackage(authorityOwnerId,crossPackage,secondDecision.canonicalDigest,'memory-package-cross',new Date(authorityNow))).rejects.toMatchObject({code:'PACKAGE_INPUT_INVALIDATED'});expect((await repository.getWorkspace(authorityOwnerId)).packages).toHaveLength(0);
  });
});
