import {expectedPlanDates,stableContractId,type MissionIntentBundle,type OperatingGoalRevision,type PlannerSubmission,type ProducerRoleId} from '@lumiclaw/domain';
import {CONTENT_PLAN_SCHEMA_DIGEST,CONTENT_PLAN_SCHEMA_ID} from '@lumiclaw/mission-compiler';
import {describe,expect,it} from 'vitest';
import {MemoryGoalPlanRepository} from './memory-goal-plan-repository.js';
import {MemoryKnowledgeRepository} from './memory-knowledge-repository.js';
import {MemoryLocalPresenceRepository} from './memory-local-presence-repository.js';
import {buildApi} from './server.js';

const persona={displayName:'Fixture Owner',role:'Founder',voice:'Evidence first',viewpoints:['Governed missions should be inspectable'],expressionBoundaries:['No outcome guarantees'],firstPersonRelationship:'First person for founder experience only',expressionExamples:['I will show the source.']};
const organization={name:'Public Safe Studio',brandName:'LumiClaw fixture',description:'Synthetic engineering fixture.',audiences:['AI builders'],facts:['Release status is engineering candidate'],approvedClaims:[{statement:'Persistent goal compiler is under engineering verification',evidence:'Public repository tests'}]};
const product={name:'Presence fixture',description:'Governed public presence mission fixture.',valueProposition:'Make planning inputs and approvals visible.',audiences:['Product teams'],facts:['No external action'],approvedClaims:[{statement:'The fixture performs no external action',evidence:'Execution contract externalActionAllowed false'}]};
const account=(platformCode:'X'|'XIAOHONGSHU')=>({platformCode,accountExists:false,handleOrDisplayName:platformCode==='X'?'@public_safe_founder':'公开安全产品手记',producerMandates:platformCode==='X'?['FOUNDER_VOICE'] as const:['PRODUCT_EXPERTISE'] as const,rolePersona:platformCode==='X'?'Founder build notes':'Product explanation',audience:['AI builders'],targetMarket:platformCode==='X'?'US':'CN',contentLocale:platformCode==='X'?'en-US':'zh-CN',contentPillars:['Build notes'],expressionExamples:['Show the source.'],dos:['Be exact'],donts:['No outcome promise'],ctaPolicy:'Invite review',cadenceHint:'Daily fixture slot'});

describe('SDD-009 Goal/Plan/Bundle API',()=>{
  it('persists the full exact-digest workflow, rejects tamper and exposes selected-platform Execution trace',async()=>{
    const now=()=>new Date('2026-08-22T09:00:00.000Z');const goalPlanRepository=new MemoryGoalPlanRepository();const knowledgeRepository=new MemoryKnowledgeRepository();const localPresenceRepository=new MemoryLocalPresenceRepository();const app=buildApi({now,goalPlanRepository,knowledgeRepository,localPresenceRepository});
    const approved=await approveKnowledge(app);
    const goalInput={objective:'持续解释公开构建进展并学习账号表达差异。',horizonDays:7,startsAt:'2026-08-24',endsAt:'2026-08-30',cadence:'DAILY',selectedAccountIds:[approved.xId,approved.xhsId],targetMarket:'US',contentLocale:'en-US',timeZone:'Asia/Singapore',successSignals:[{code:'PUBLISHING_CADENCE',observation:'记录计划槽位是否进入 Owner 审阅。'}],knowledgeSnapshotId:approved.snapshotId,knowledgeSnapshotDigest:approved.snapshotDigest};
    const created=await app.inject({method:'POST',url:'/api/v1/goals',headers:{'if-match':approved.etag,'idempotency-key':'goal-create-0001'},payload:goalInput});expect(created.statusCode,created.body).toBe(201);const draft=created.json().goal as OperatingGoalRevision;expect(draft.state).toBe('DRAFT');
    const replay=await app.inject({method:'POST',url:'/api/v1/goals',headers:{'if-match':approved.etag,'idempotency-key':'goal-create-0001'},payload:goalInput});expect(replay.statusCode,replay.body).toBe(200);expect(replay.json().goal.canonicalDigest).toBe(draft.canonicalDigest);
    const goalEditPayload={...goalInput,objective:'持续解释公开构建进展，并记录账号表达差异。',canonicalDigest:draft.canonicalDigest};const goalEdited=await app.inject({method:'PATCH',url:`/api/v1/goals/${draft.goalId}`,headers:{'if-match':created.headers.etag!,'idempotency-key':'goal-edit-0001'},payload:goalEditPayload});expect(goalEdited.statusCode,goalEdited.body).toBe(200);const revisedDraft=goalEdited.json().goal as OperatingGoalRevision;expect(revisedDraft.revision).toBe(2);
    const goalEditReplay=await app.inject({method:'PATCH',url:`/api/v1/goals/${draft.goalId}`,headers:{'if-match':created.headers.etag!,'idempotency-key':'goal-edit-0001'},payload:goalEditPayload});expect(goalEditReplay.statusCode,goalEditReplay.body).toBe(200);expect(goalEditReplay.headers['idempotency-replayed']).toBe('true');expect(goalEditReplay.json().goal.canonicalDigest).toBe(revisedDraft.canonicalDigest);
    const goalEditWithNewKey=await app.inject({method:'PATCH',url:`/api/v1/goals/${draft.goalId}`,headers:{'if-match':created.headers.etag!,'idempotency-key':'goal-edit-new-key'},payload:goalEditPayload});expect(goalEditWithNewKey.statusCode).toBe(412);
    const activated=await app.inject({method:'POST',url:`/api/v1/goals/${draft.goalId}/activate`,headers:{'if-match':goalEdited.headers.etag!,'idempotency-key':'goal-activate-0001'},payload:{canonicalDigest:revisedDraft.canonicalDigest}});expect(activated.statusCode,activated.body).toBe(200);const active=activated.json().goal as OperatingGoalRevision;expect(active.state).toBe('ACTIVE');
    const activateReplay=await app.inject({method:'POST',url:`/api/v1/goals/${draft.goalId}/activate`,headers:{'if-match':goalEdited.headers.etag!,'idempotency-key':'goal-activate-0001'},payload:{canonicalDigest:revisedDraft.canonicalDigest}});expect(activateReplay.statusCode,activateReplay.body).toBe(200);expect(activateReplay.headers['idempotency-replayed']).toBe('true');expect(activateReplay.json().goal.canonicalDigest).toBe(active.canonicalDigest);
    const activateWithNewKey=await app.inject({method:'POST',url:`/api/v1/goals/${draft.goalId}/activate`,headers:{'if-match':goalEdited.headers.etag!,'idempotency-key':'goal-activate-new-key'},payload:{canonicalDigest:revisedDraft.canonicalDigest}});expect(activateWithNewKey.statusCode).toBe(412);
    const stale=await app.inject({method:'POST',url:`/api/v1/goals/${draft.goalId}/pause`,headers:{'if-match':created.headers.etag!,'idempotency-key':'goal-stale-0001'},payload:{canonicalDigest:draft.canonicalDigest}});expect(stale.statusCode).toBe(412);
    const compiled=await app.inject({method:'POST',url:'/api/v1/missions/compile',headers:{'if-match':activated.headers.etag!,'idempotency-key':'intent-compile-0001'},payload:{goalId:active.goalId,goalDigest:active.canonicalDigest}});expect(compiled.statusCode,compiled.body).toBe(201);const intent=compiled.json().bundle as MissionIntentBundle;expect(intent.roles).toHaveLength(6);expect(intent.selectedPlatforms).toEqual(['X','XIAOHONGSHU']);expect(compiled.json().plannerExecution).toEqual({status:'NOT_RUN',fixtureAllowedForEngineering:true,agentTeamsExecuted:false});
    const submission=plannerSubmission(intent,active);const tamper=await app.inject({method:'POST',url:'/api/v1/content-plans',headers:{'if-match':compiled.headers.etag!,'idempotency-key':'plan-tamper-0001'},payload:{...submission,skillLockDigest:'0'.repeat(64)}});expect(tamper.statusCode).toBe(422);expect(tamper.json().code).toBe('PLANNER_SUBMISSION_SKILL_MISMATCH');
    const imported=await app.inject({method:'POST',url:'/api/v1/content-plans',headers:{'if-match':compiled.headers.etag!,'idempotency-key':'plan-import-0001'},payload:submission});expect(imported.statusCode,imported.body).toBe(201);const plan=imported.json().plan;expect(plan.state).toBe('NEEDS_OWNER');expect(plan.slots).toHaveLength(7);expect(imported.json().agentTeamsExecuted).toBe(false);
    const slots=structuredClone(plan.slots);slots[0].theme='Owner adjusted build note';const brief={...plan.currentBrief,theme:slots[0].theme};const planEditPayload={canonicalDigest:plan.canonicalDigest,slots,currentBrief:brief,sourceBindings:plan.sourceBindings};const edited=await app.inject({method:'PATCH',url:`/api/v1/content-plans/${plan.planId}`,headers:{'if-match':imported.headers.etag!,'idempotency-key':'plan-edit-0001'},payload:planEditPayload});expect(edited.statusCode,edited.body).toBe(200);expect(edited.json().plan.revision).toBe(2);expect(edited.json().plan.canonicalDigest).not.toBe(plan.canonicalDigest);
    const planEditReplay=await app.inject({method:'PATCH',url:`/api/v1/content-plans/${plan.planId}`,headers:{'if-match':imported.headers.etag!,'idempotency-key':'plan-edit-0001'},payload:planEditPayload});expect(planEditReplay.statusCode,planEditReplay.body).toBe(200);expect(planEditReplay.headers['idempotency-replayed']).toBe('true');expect(planEditReplay.json().plan.canonicalDigest).toBe(edited.json().plan.canonicalDigest);
    const planEditWithNewKey=await app.inject({method:'PATCH',url:`/api/v1/content-plans/${plan.planId}`,headers:{'if-match':imported.headers.etag!,'idempotency-key':'plan-edit-new-key'},payload:planEditPayload});expect(planEditWithNewKey.statusCode).toBe(412);
    const approvedPlan=await app.inject({method:'POST',url:`/api/v1/content-plans/${plan.planId}/approve`,headers:{'if-match':edited.headers.etag!,'idempotency-key':'plan-approve-0001'},payload:{canonicalDigest:edited.json().plan.canonicalDigest}});expect(approvedPlan.statusCode,approvedPlan.body).toBe(200);const execution=approvedPlan.json().bundle;expect(execution.kind).toBe('MISSION_EXECUTION');expect(execution.roles).toHaveLength(6);expect(execution.tasks.filter((task:{kind:string})=>task.kind==='PRODUCE_CONTENT')).toHaveLength(2);expect(new Set(execution.activationUnits.map((unit:{platformCode:string})=>unit.platformCode))).toEqual(new Set(['X','XIAOHONGSHU']));expect(execution.evidenceContract).toEqual({agentTeamsExecuted:false,fixtureAllowed:true,externalActionAllowed:false});expect(execution.trace.map((event:{code:string})=>event.code)).toEqual(['INTENT_BINDINGS_VERIFIED','PLAN_EXACT_DIGEST_APPROVED','SELECTED_PLATFORM_DAG_COMPILED']);
    const approvalReplay=await app.inject({method:'POST',url:`/api/v1/content-plans/${plan.planId}/approve`,headers:{'if-match':edited.headers.etag!,'idempotency-key':'plan-approve-0001'},payload:{canonicalDigest:edited.json().plan.canonicalDigest}});expect(approvalReplay.statusCode,approvalReplay.body).toBe(200);expect(approvalReplay.headers['idempotency-replayed']).toBe('true');expect(approvalReplay.json().bundle.canonicalDigest).toBe(execution.canonicalDigest);
    const approvalWithNewKey=await app.inject({method:'POST',url:`/api/v1/content-plans/${plan.planId}/approve`,headers:{'if-match':edited.headers.etag!,'idempotency-key':'plan-approve-new-key'},payload:{canonicalDigest:edited.json().plan.canonicalDigest}});expect(approvalWithNewKey.statusCode).toBe(412);
    const reopened=await app.inject({method:'GET',url:`/api/v1/mission-bundles/${execution.bundleId}`});expect(reopened.statusCode).toBe(200);expect(reopened.json().bundle.canonicalDigest).toBe(execution.canonicalDigest);const workspace=await app.inject({method:'GET',url:'/api/v1/goals'});expect(workspace.json().workspace.goals).toHaveLength(3);expect(workspace.json().workspace.plans).toHaveLength(3);expect(workspace.json().workspace.bundles).toHaveLength(2);
    await app.close();
  });
});

async function approveKnowledge(app:ReturnType<typeof buildApi>){
  await app.inject({method:'POST',url:'/api/v1/local-owner-profile',payload:{displayName:'Fixture Owner'}});const response=await app.inject({method:'GET',url:'/api/v1/onboarding/session'});let overview=response.json().overview;
  const mutate=async(method:'PUT'|'POST',url:string,payload:Record<string,unknown>,key:string)=>{const result=await app.inject({method,url,headers:{'if-match':`"knowledge-${overview.session.rowVersion}"`,'idempotency-key':key},payload});expect(result.statusCode,result.body).toBeLessThan(300);overview=result.json().overview;return result;};
  await mutate('PUT','/api/v1/profiles/persona',persona,'sdd009-persona');await mutate('PUT','/api/v1/profiles/organization',organization,'sdd009-org');await mutate('PUT','/api/v1/profiles/product',product,'sdd009-product');await mutate('POST','/api/v1/knowledge/sources/text',{label:'Public-safe source',text:'The compiler fixture performs no external platform action.'},'sdd009-source');await mutate('PUT','/api/v1/profiles/accounts/X',account('X'),'sdd009-x-account');await mutate('PUT','/api/v1/profiles/accounts/XIAOHONGSHU',account('XIAOHONGSHU'),'sdd009-xhs-account');await mutate('PUT','/api/v1/onboarding/session',{currentStep:'REVIEW',targetMarket:'US',contentLocale:'en-US',timeZone:'Asia/Singapore'},'sdd009-context');
  const draft=overview.draft;const approved=await mutate('POST','/api/v1/knowledge/snapshots/approve',{snapshotId:draft.id,canonicalDigest:draft.canonicalDigest},'sdd009-approve');const xId=overview.profiles.accounts.X.id;const xhsId=overview.profiles.accounts.XIAOHONGSHU.id;return {snapshotId:draft.id,snapshotDigest:draft.canonicalDigest,xId,xhsId,etag:approved.headers.etag!};
}

function plannerSubmission(intent:MissionIntentBundle,goal:OperatingGoalRevision):PlannerSubmission{
  const planner=intent.tasks.find((task)=>task.roleId==='campaign-planner')!;const items=intent.roleContexts.find((context)=>context.roleId==='campaign-planner')!.knowledgeItemIds.slice(0,2);const dates=expectedPlanDates(goal);const slots=dates.map((localDate,index)=>{const producerRole:ProducerRoleId=index%2===0?'founder-identity-producer':'product-account-producer';const mandate=producerRole==='founder-identity-producer'?'FOUNDER_VOICE':'PRODUCT_EXPERTISE';const account=intent.inputBindings.accountProfiles.find((candidate)=>candidate.producerMandates.includes(mandate))!;return {slotId:stableContractId('slot',{localDate,index}),localDate,localTime:index%2===0?'09:30':'18:30',platformCode:account.platformCode,accountProfileRevisionId:account.accountProfileRevisionId,producerRole,theme:`Public-safe theme ${index+1}`,contentObjective:producerRole==='founder-identity-producer'?'Explain a founder decision.':'Explain a product workflow.',claimConstraints:['No AgentTeams run claim','No business outcome claim'],sourceItemIds:items,status:'PLANNED' as const};});const first=slots[0]!;return {schemaVersion:2,roleId:'campaign-planner',missionIntentId:intent.missionIntentId,intentBundleId:intent.bundleId,intentBundleDigest:intent.canonicalDigest,taskId:planner.taskId,inputDigest:planner.inputDigest,outputSchema:CONTENT_PLAN_SCHEMA_ID,outputSchemaDigest:CONTENT_PLAN_SCHEMA_DIGEST,skillLockDigest:planner.skillLockDigest,slots,currentBrief:{briefId:stableContractId('brief',{slotId:first.slotId}),slotId:first.slotId,platformCode:first.platformCode,accountProfileRevisionId:first.accountProfileRevisionId,producerRole:first.producerRole,theme:first.theme,contentObjective:first.contentObjective,sourceItemIds:[...first.sourceItemIds],claimConstraints:[...first.claimConstraints]},sourceBindings:[{snapshotId:goal.knowledgeSnapshotId,snapshotDigest:goal.knowledgeSnapshotDigest,sourceItemIds:items,claimConstraints:['Approved evidence only']}],evidenceMaturity:'CONTROLLED_FIXTURE'};}
