import {createOperatingGoalRevision,expectedPlanDates,stableContractId,type AccountProfileBinding,type GoalKnowledgeGuard,type KnowledgeRoleContext,type OperatingGoalInput,type OperatingGoalRevision,type PlannerSubmission,type ProducerRoleId} from '@lumiclaw/domain';
import {approveContentPlanV2,compileMissionIntentV2,continueSelectedPlatformMissionV2,importPlannerSubmissionV2} from '@lumiclaw/mission-compiler';
import {describe,expect,it} from 'vitest';
import {MemoryGoalPlanRepository} from './memory-goal-plan-repository.js';

describe('SDD-009 Memory binding-scoped invalidation',()=>{
  it('keeps Goal/Plan B valid when only Goal/Plan A changes',async()=>{
    const repository=new MemoryGoalPlanRepository();const fixture=createFixture();const ownerId=fixture.goal.ownerId;const value=goalInput(fixture.goal);const goalA=createOperatingGoalRevision({ownerId,goalId:'goal-a',revision:1,state:'ACTIVE',parentDigest:null,value,createdAt:'2026-08-22T00:00:00.000Z'});const goalB=createOperatingGoalRevision({ownerId,goalId:'goal-b',revision:1,state:'ACTIVE',parentDigest:null,value,createdAt:'2026-08-22T00:00:00.000Z'});const guard:GoalKnowledgeGuard={rowVersion:1,snapshotId:fixture.knowledge.snapshotId,snapshotDigest:fixture.knowledge.snapshotDigest,accountProfileDigests:fixture.accounts.map((account)=>({revisionId:account.accountProfileRevisionId,digest:account.digest}))};
    await repository.appendGoal(ownerId,goalA,fixture.accounts,null,guard,'goal-a-create-0001',new Date('2026-08-22T00:00:00.000Z'));await repository.appendGoal(ownerId,goalB,fixture.accounts,null,guard,'goal-b-create-0001',new Date('2026-08-22T00:00:01.000Z'));
    const first=await compileCycle(repository,goalA,fixture.knowledge,fixture.accounts,'a');const second=await compileCycle(repository,goalB,fixture.knowledge,fixture.accounts,'b');
    const nextPlan=importPlannerSubmissionV2(first.intent,plannerSubmission(first.intent,goalA,fixture.accounts),'2026-08-23T00:00:00.000Z',first.approvedPlan);await repository.appendPlan(ownerId,nextPlan,first.approvedPlan.canonicalDigest,'plan-a-next-0001',new Date('2026-08-23T00:00:00.000Z'));
    let workspace=await repository.getWorkspace(ownerId);expect(state(workspace,first.execution.bundleId)).toBe('INVALIDATED');expect(state(workspace,second.intent.bundleId)).toBe('COMPILED');expect(state(workspace,second.execution.bundleId)).toBe('COMPILED');expect(workspace.invalidations.filter((event)=>event.reasonCode==='PLAN_REVISION_CHANGED')).toHaveLength(1);
    const goalA2=createOperatingGoalRevision({ownerId,goalId:goalA.goalId,revision:2,state:'ACTIVE',parentDigest:goalA.canonicalDigest,value:{...value,objective:'Only Goal A changed.'},createdAt:'2026-08-24T00:00:00.000Z'});await repository.appendGoal(ownerId,goalA2,fixture.accounts,goalA.canonicalDigest,guard,'goal-a-change-0001',new Date('2026-08-24T00:00:00.000Z'));
    workspace=await repository.getWorkspace(ownerId);expect(state(workspace,first.intent.bundleId)).toBe('INVALIDATED');expect(state(workspace,second.intent.bundleId)).toBe('COMPILED');expect(state(workspace,second.execution.bundleId)).toBe('COMPILED');expect(workspace.invalidations.some((event)=>event.bundleId===second.intent.bundleId||event.bundleId===second.execution.bundleId)).toBe(false);
  });
});

async function compileCycle(repository:MemoryGoalPlanRepository,goal:OperatingGoalRevision,knowledge:KnowledgeRoleContext,accounts:AccountProfileBinding[],suffix:string){const intent=compileMissionIntentV2({goal,knowledge,accountProfiles:accounts});await repository.appendBundle(goal.ownerId,intent,goal.canonicalDigest,`intent-${suffix}-append-0001`,new Date('2026-08-22T01:00:00.000Z'));const plan=importPlannerSubmissionV2(intent,plannerSubmission(intent,goal,accounts),'2026-08-22T02:00:00.000Z');await repository.appendPlan(goal.ownerId,plan,null,`plan-${suffix}-append-0001`,new Date('2026-08-22T02:00:00.000Z'));const approvedPlan=approveContentPlanV2(intent,plan,plan.canonicalDigest,'2026-08-22T03:00:00.000Z');const execution=continueSelectedPlatformMissionV2(intent,approvedPlan);await repository.approvePlanAndAppendBundle(goal.ownerId,plan.canonicalDigest,approvedPlan,execution,`plan-${suffix}-approve-0001`,new Date('2026-08-22T03:00:00.000Z'));return {intent,approvedPlan,execution};}
function goalInput(goal:OperatingGoalRevision):OperatingGoalInput{return {objective:goal.objective,horizonDays:goal.horizonDays,startsAt:goal.startsAt,endsAt:goal.endsAt,cadence:goal.cadence,selectedAccountIds:[...goal.selectedAccountIds],targetMarket:goal.targetMarket,contentLocale:goal.contentLocale,timeZone:goal.timeZone,successSignals:structuredClone(goal.successSignals),knowledgeSnapshotId:goal.knowledgeSnapshotId,knowledgeSnapshotDigest:goal.knowledgeSnapshotDigest};}
function state(workspace:Awaited<ReturnType<MemoryGoalPlanRepository['getWorkspace']>>,bundleId:string){return workspace.bundleStates.find((item)=>item.bundleId===bundleId)?.state;}

function createFixture(){const ownerId='owner-a';const snapshotId='snapshot-approved';const snapshotDigest='a'.repeat(64);const accounts:AccountProfileBinding[]=[{accountProfileRevisionId:'account-x',revision:1,digest:'b'.repeat(64),platformCode:'X',handleOrDisplayName:'@founder',producerMandates:['FOUNDER_VOICE'],targetMarket:'US',contentLocale:'en-US'},{accountProfileRevisionId:'account-xhs',revision:1,digest:'c'.repeat(64),platformCode:'XIAOHONGSHU',handleOrDisplayName:'产品号',producerMandates:['PRODUCT_EXPERTISE'],targetMarket:'US',contentLocale:'en-US'}];const value:OperatingGoalInput={objective:'Review two independent missions.',horizonDays:7,startsAt:'2026-08-24',endsAt:'2026-08-30',cadence:'DAILY',selectedAccountIds:accounts.map((account)=>account.accountProfileRevisionId),targetMarket:'US',contentLocale:'en-US',timeZone:'Asia/Singapore',successSignals:[{code:'PUBLISHING_CADENCE',observation:'Record Owner-reviewed slots.'}],knowledgeSnapshotId:snapshotId,knowledgeSnapshotDigest:snapshotDigest};const goal=createOperatingGoalRevision({ownerId,goalId:'fixture',revision:1,state:'ACTIVE',parentDigest:null,value,createdAt:'2026-08-22T00:00:00.000Z'});const items=[{id:'claim',kind:'CLAIM' as const,normalizedValue:'Public-safe claim.',sourceRevisionIds:['source'],profileRevisionIds:[],ownerAuthority:'ORGANIZATION_APPROVED_PRIVATE' as const},{id:'evidence',kind:'EVIDENCE' as const,normalizedValue:'Public-safe evidence.',sourceRevisionIds:['source'],profileRevisionIds:[],ownerAuthority:'ORGANIZATION_APPROVED_PRIVATE' as const}];const knowledge:KnowledgeRoleContext={snapshotId,snapshotDigest,ownerId,targetMarket:'US',contentLocale:'en-US',timeZone:'Asia/Singapore',items,sourceDigests:[{revisionId:'source',digest:'d'.repeat(64)}],profileDigests:accounts.map((account)=>({revisionId:account.accountProfileRevisionId,digest:account.digest}))};return {goal,knowledge,accounts};}

function plannerSubmission(intent:ReturnType<typeof compileMissionIntentV2>,goal:OperatingGoalRevision,accounts:AccountProfileBinding[]):PlannerSubmission{const planner=intent.tasks.find((task)=>task.roleId==='campaign-planner')!;const slots=expectedPlanDates(goal).map((localDate,index)=>{const producerRole:ProducerRoleId=index%2===0?'founder-identity-producer':'product-account-producer';const mandate=producerRole==='founder-identity-producer'?'FOUNDER_VOICE':'PRODUCT_EXPERTISE';const account=accounts.find((candidate)=>candidate.producerMandates.includes(mandate))!;return {slotId:stableContractId('slot',{goalId:goal.goalId,localDate}),localDate,localTime:null,platformCode:account.platformCode,accountProfileRevisionId:account.accountProfileRevisionId,producerRole,theme:`Theme ${index}`,contentObjective:`Objective ${index}`,claimConstraints:['Approved evidence only'],sourceItemIds:['claim','evidence'],status:'PLANNED' as const};});const first=slots[0]!;return {schemaVersion:2,roleId:'campaign-planner',missionIntentId:intent.missionIntentId,intentBundleId:intent.bundleId,intentBundleDigest:intent.canonicalDigest,taskId:planner.taskId,inputDigest:planner.inputDigest,outputSchema:'lumiclaw.content-plan.v2',outputSchemaDigest:intent.plannerRequirements.outputSchemaDigest,skillLockDigest:planner.skillLockDigest,slots,currentBrief:{briefId:stableContractId('brief',{slotId:first.slotId}),slotId:first.slotId,platformCode:first.platformCode,accountProfileRevisionId:first.accountProfileRevisionId,producerRole:first.producerRole,theme:first.theme,contentObjective:first.contentObjective,sourceItemIds:[...first.sourceItemIds],claimConstraints:[...first.claimConstraints]},sourceBindings:[{snapshotId:goal.knowledgeSnapshotId,snapshotDigest:goal.knowledgeSnapshotDigest,sourceItemIds:['claim','evidence'],claimConstraints:['Approved evidence only']}],evidenceMaturity:'CONTROLLED_FIXTURE'};}
