import {
  ArtifactContractError,createArtifactInvalidation,effectiveArtifactState,sha256Digest,verifyManualPublishPackage,
  type ArtifactAuditDecision,type ArtifactInvalidationEvent,type ArtifactOwnerDecision,type ArtifactPublishRepository,type ArtifactRevisionV3,
  type ArtifactWorkspace,type ManualPublishPackage,type PackageHelperEvent,type QuarantinedSubmission,type RegenerationRequest
} from '@lumiclaw/domain';

export class MemoryArtifactPublishRepository implements ArtifactPublishRepository {
  readonly #workspace:ArtifactWorkspace={revisions:[],quarantines:[],audits:[],ownerDecisions:[],regenerationRequests:[],packages:[],helperEvents:[],invalidations:[]};
  readonly #idempotency=new Map<string,{digest:string;response:unknown}>();
  public async health(){return true;}
  public async getWorkspace(ownerId:string){return clone(filterWorkspace(this.#workspace,ownerId));}
  public async getRevision(ownerId:string,id:string){return cloneOrUndefined(this.#workspace.revisions.find((item)=>item.ownerId===ownerId&&item.id===id));}
  public async getAudit(ownerId:string,id:string){return cloneOrUndefined(this.#workspace.audits.find((item)=>item.ownerId===ownerId&&item.id===id));}
  public async getOwnerDecision(ownerId:string,id:string){return cloneOrUndefined(this.#workspace.ownerDecisions.find((item)=>item.ownerId===ownerId&&item.id===id));}
  public async getPackage(ownerId:string,id:string){return cloneOrUndefined(this.#workspace.packages.find((item)=>item.ownerId===ownerId&&item.id===id));}

  public async appendRevision(ownerId:string,revision:ArtifactRevisionV3,expectedHeadDigest:string|null,idempotencyKey:string,now:Date){return this.idempotent(ownerId,'REVISION',idempotencyKey,{revision:revision.canonicalDigest,expectedHeadDigest},()=>{
    if(revision.ownerId!==ownerId)throw new ArtifactContractError('OWNER_BOUNDARY_VIOLATION');const revisions=this.#workspace.revisions.filter((item)=>item.ownerId===ownerId&&item.activationUnitId===revision.activationUnitId).sort((a,b)=>b.revision-a.revision);const head=revisions[0];
    if(head===undefined){if(expectedHeadDigest!==null||revision.revision!==1||revision.parentRevisionId!==null)throw new ArtifactContractError('OWNER_DECISION_STALE');}else if(expectedHeadDigest!==head.canonicalDigest||revision.revision!==head.revision+1||revision.parentRevisionId!==head.id)throw new ArtifactContractError('OWNER_DECISION_STALE');
    this.#workspace.revisions.push(clone(revision));const invalidations:ArtifactInvalidationEvent[]=[];for(const prior of revisions){if(this.#workspace.invalidations.some((item)=>item.artifactRevisionId===prior.id))continue;const event=createArtifactInvalidation({ownerId,artifactRevisionId:prior.id,reasonCode:'NEW_REVISION',previousDigest:prior.canonicalDigest,currentDigest:revision.canonicalDigest,createdAt:now.toISOString()});this.#workspace.invalidations.push(event);invalidations.push(event);}return {revision:clone(revision),invalidations:clone(invalidations),replayed:false};
  });}
  public async appendQuarantine(ownerId:string,value:QuarantinedSubmission,idempotencyKey:string,_now:Date){void _now;return this.idempotent(ownerId,'QUARANTINE',idempotencyKey,{value},()=>{if(value.ownerId!==ownerId)throw new ArtifactContractError('OWNER_BOUNDARY_VIOLATION');this.#workspace.quarantines.push(clone(value));return {quarantine:clone(value),replayed:false};});}
  public async appendAudit(ownerId:string,value:ArtifactAuditDecision,expectedRevisionDigest:string,idempotencyKey:string,_now:Date){void _now;return this.idempotent(ownerId,'AUDIT',idempotencyKey,{value:value.canonicalDigest,expectedRevisionDigest},()=>{
    const revision=this.#workspace.revisions.find((item)=>item.ownerId===ownerId&&item.id===value.artifactRevisionId);if(revision===undefined||revision.canonicalDigest!==expectedRevisionDigest||value.ownerId!==ownerId||value.artifactRevisionDigest!==expectedRevisionDigest||effectiveArtifactState(this.#workspace,revision)==='INVALIDATED')throw new ArtifactContractError('OWNER_DECISION_STALE');if(this.#workspace.audits.some((item)=>item.artifactRevisionId===revision.id))throw new ArtifactContractError('OWNER_DECISION_STALE');this.#workspace.audits.push(clone(value));return {audit:clone(value),replayed:false};
  });}
  public async appendOwnerDecision(ownerId:string,value:ArtifactOwnerDecision,expectedAuditDigest:string,idempotencyKey:string,_now:Date){void _now;return this.idempotent(ownerId,'OWNER_DECISION',idempotencyKey,{value:value.canonicalDigest,expectedAuditDigest},()=>{
    const revision=this.#workspace.revisions.find((item)=>item.ownerId===ownerId&&item.id===value.artifactRevisionId);const audit=this.#workspace.audits.find((item)=>item.ownerId===ownerId&&item.id===value.auditDecisionId);if(revision===undefined||audit===undefined||value.ownerId!==ownerId||audit.canonicalDigest!==expectedAuditDigest||value.auditDecisionDigest!==expectedAuditDigest||effectiveArtifactState(this.#workspace,revision)==='INVALIDATED')throw new ArtifactContractError('OWNER_DECISION_STALE');if(this.#workspace.ownerDecisions.some((item)=>item.artifactRevisionId===revision.id))throw new ArtifactContractError('OWNER_DECISION_STALE');this.#workspace.ownerDecisions.push(clone(value));return {decision:clone(value),replayed:false};
  });}
  public async appendRegenerationRequest(ownerId:string,value:RegenerationRequest,expectedRevisionDigest:string,idempotencyKey:string,_now:Date){void _now;return this.idempotent(ownerId,'REGENERATE',idempotencyKey,{value:value.canonicalDigest,expectedRevisionDigest},()=>{const revision=this.#workspace.revisions.find((item)=>item.ownerId===ownerId&&item.id===value.artifactRevisionId);if(revision===undefined||revision.canonicalDigest!==expectedRevisionDigest||value.ownerId!==ownerId||effectiveArtifactState(this.#workspace,revision)==='INVALIDATED')throw new ArtifactContractError('OWNER_DECISION_STALE');this.#workspace.regenerationRequests.push(clone(value));return {request:clone(value),replayed:false};});}
  public async appendPackage(ownerId:string,value:ManualPublishPackage,expectedDecisionDigest:string,idempotencyKey:string,_now:Date){void _now;return this.idempotent(ownerId,'PACKAGE',idempotencyKey,{value:value.manifestDigest,expectedDecisionDigest},()=>{const revision=this.#workspace.revisions.find((item)=>item.ownerId===ownerId&&item.id===value.artifactRevisionId);const decision=this.#workspace.ownerDecisions.find((item)=>item.ownerId===ownerId&&item.id===value.ownerDecisionId);if(revision===undefined||decision===undefined||value.ownerId!==ownerId||decision.canonicalDigest!==expectedDecisionDigest||value.ownerDecisionDigest!==expectedDecisionDigest||effectiveArtifactState(this.#workspace,revision)!=='APPROVED'||!verifyManualPublishPackage(value).ok)throw new ArtifactContractError('PACKAGE_INPUT_INVALIDATED');const existing=this.#workspace.packages.find((item)=>item.exactInputDigest===value.exactInputDigest);if(existing!==undefined)return {package:clone(existing),replayed:true};this.#workspace.packages.push(clone(value));return {package:clone(value),replayed:false};});}
  public async appendHelperEvent(ownerId:string,value:PackageHelperEvent,idempotencyKey:string,_now:Date){void _now;return this.idempotent(ownerId,'HELPER',idempotencyKey,{value:value.canonicalDigest},()=>{const pack=this.#workspace.packages.find((item)=>item.ownerId===ownerId&&item.id===value.packageId);const revision=pack===undefined?undefined:this.#workspace.revisions.find((item)=>item.ownerId===ownerId&&item.id===pack.artifactRevisionId);if(pack===undefined||revision===undefined||pack.manifestDigest!==value.packageDigest||effectiveArtifactState(this.#workspace,revision)==='INVALIDATED')throw new ArtifactContractError('PACKAGE_INPUT_INVALIDATED');this.#workspace.helperEvents.push(clone(value));return {event:clone(value),replayed:false};});}
  public async invalidateBindings(ownerId:string,revisionId:string,reasonCode:ArtifactInvalidationEvent['reasonCode'],previousDigest:string,currentDigest:string,now:Date){const revision=this.#workspace.revisions.find((item)=>item.ownerId===ownerId&&item.id===revisionId);if(revision===undefined||revision.canonicalDigest!==previousDigest)throw new ArtifactContractError('OWNER_BOUNDARY_VIOLATION');const event=createArtifactInvalidation({ownerId,artifactRevisionId:revisionId,reasonCode,previousDigest,currentDigest,createdAt:now.toISOString()});this.#workspace.invalidations.push(event);return clone(event);}
  public async close(){}
  private async idempotent<T>(ownerId:string,route:string,key:string,request:unknown,operation:()=>T):Promise<T>{if(key.length<8||key.length>128)throw new ArtifactContractError('IDEMPOTENCY_KEY_REQUIRED');const id=`${ownerId}:${route}:${key}`;const digest=sha256Digest(request);const existing=this.#idempotency.get(id);if(existing!==undefined){if(existing.digest!==digest)throw new ArtifactContractError('IDEMPOTENCY_KEY_REUSED');const response=clone(existing.response) as T&{replayed?:boolean};if(response!==null&&typeof response==='object'&&'replayed'in response)response.replayed=true;return response;}const response=operation();this.#idempotency.set(id,{digest,response:clone(response)});return response;}
}

function filterWorkspace(value:ArtifactWorkspace,ownerId:string):ArtifactWorkspace{return {revisions:value.revisions.filter((item)=>item.ownerId===ownerId),quarantines:value.quarantines.filter((item)=>item.ownerId===ownerId),audits:value.audits.filter((item)=>item.ownerId===ownerId),ownerDecisions:value.ownerDecisions.filter((item)=>item.ownerId===ownerId),regenerationRequests:value.regenerationRequests.filter((item)=>item.ownerId===ownerId),packages:value.packages.filter((item)=>item.ownerId===ownerId),helperEvents:value.helperEvents.filter((item)=>item.ownerId===ownerId),invalidations:value.invalidations.filter((item)=>item.ownerId===ownerId)};}
function clone<T>(value:T):T{return structuredClone(value);}function cloneOrUndefined<T>(value:T|undefined):T|undefined{return value===undefined?undefined:clone(value);}
