import {campaignDocumentSchema, organizationGraphSchema} from '@lumiclaw/domain';

export const openApiDocument = {
  openapi: '3.1.0',
  info: {title: 'LumiClaw Presence Control API', version: '0.3.0-sdd006', description: 'Local-first Production UX and governed SHADOW Campaign control plane. No browser Secret collection, published-state shortcut, ActionGrant, connector, schedule execution, or external platform action endpoint exists.'},
  servers: [{url: '/'}],
  paths: {
    '/api/v1/local-workspace': {get: {summary: 'Reopen the PostgreSQL-owned local profile, onboarding, materials, Campaign, historical handoffs and publish-authorization gate', responses: {'200': {description: 'No-store local workspace snapshot; publishing remains blocked without Audit PASS plus exact external-action OwnerDecision'}}}},
    '/api/v1/local-owner-profile': {post: {summary: 'Create the single local display-name-only Owner profile', requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/LocalOwnerProfileInput'}}}}, responses: {'201': {description: 'Local profile ready; no email, password or remote registration'}, '422': {description: 'Closed schema or browser Secret field rejected'}}}},
    '/api/v1/local-onboarding/example': {post: {summary: 'Choose the public-safe example Organization and Campaign path exactly once', responses: {'201': {description: 'Public-safe example context persisted; external action remains disabled'}, '409': {description: 'LOCAL_ONBOARDING_ALREADY_COMPLETED; completed authority cannot be reopened or replaced'}, '428': {description: 'Local profile required'}}}},
    '/api/v1/local-onboarding/materials-path': {post: {summary: 'Choose the real local-material path before onboarding completion', responses: {'200': {description: 'MD/TXT support and PDF/DOCX PLANNED status returned'}, '409': {description: 'LOCAL_ONBOARDING_ALREADY_COMPLETED; completed authority cannot be reopened'}, '428': {description: 'Local profile required'}}}},
    '/api/v1/local-onboarding/context': {post: {summary: 'Persist Market, content Locale, Platform and IANA Time Zone as separate stable codes before completion', requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/LocalOnboardingContext'}}}}, responses: {'200': {description: 'Context persisted'}, '409': {description: 'LOCAL_ONBOARDING_ALREADY_COMPLETED; completed context is immutable through onboarding endpoints'}, '422': {description: 'Closed schema, invalid code or browser Secret field rejected'}, '428': {description: 'Local profile required'}}}},
    '/api/v1/local-onboarding/complete': {post: {summary: 'Create a user-confirmed LOCAL_PRIVATE Organization, Brand, Product and Campaign exactly once', requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/LocalCampaignIdentityInput'}}}}, responses: {'200': {description: 'Authoritative LOCAL_PRIVATE Campaign persisted; external action remains disabled'}, '409': {description: 'LOCAL_ONBOARDING_ALREADY_COMPLETED; completed authority cannot be replaced'}, '422': {description: 'Materials/context not ready or closed identity schema invalid'}, '428': {description: 'Local profile required'}}}},
    '/api/v1/local-materials': {
      get: {summary: 'List local material manifests without returning raw Blob bytes', responses: {'200': {description: 'No-store material manifests'}, '428': {description: 'Local profile required'}}},
      post: {summary: 'Extract and persist one UTF-8 MD/TXT file server-side before onboarding completion', parameters: [{name: 'X-LumiClaw-File-Name', in: 'header', required: true, schema: {type: 'string', minLength: 3, maxLength: 180}}], requestBody: {required: true, content: {'text/markdown': {schema: {type: 'string', format: 'binary', maxLength: 2097152}}, 'text/plain': {schema: {type: 'string', format: 'binary', maxLength: 2097152}}}}, responses: {'201': {description: 'Manifest and content-addressed Blob persisted'}, '409': {description: 'LOCAL_ONBOARDING_ALREADY_COMPLETED; use a future authoritative Campaign update/invalidation flow'}, '413': {description: '2 MiB limit exceeded'}, '422': {description: 'Filename, UTF-8, binary or media type rejected; PDF/DOCX return PLANNED code'}, '428': {description: 'Local profile required'}}}
    },
    '/api/v1/local-materials/{materialId}': {delete: {summary: 'Delete an unbound onboarding material; completed-Campaign evidence fails closed', parameters: [{name: 'materialId', in: 'path', required: true, schema: {type: 'string', format: 'uuid'}}], responses: {'200': {description: 'Unbound material deleted'}, '404': {description: 'Material not found'}, '409': {description: 'LOCAL_MATERIAL_BOUND_TO_CAMPAIGN; use a future retract/invalidate flow'}}}},
    '/api/v1/environment-readiness': {get: {summary: 'Probe Web/API/PostgreSQL/AgentTeams adapter/runtime using deterministic provenance-bearing states', responses: {'200': {description: 'No-store readiness; unconfigured runtime reports SDD_007_REQUIRED and never fabricated green'}}}},
    '/api/v1/ai-team': {get: {summary: 'Return the six stable Agent roles and NO_RUNTIME_OBSERVATION metrics', responses: {'200': {description: 'A0-A5 responsibility roster; zero means no authoritative observation'}}}},
    '/api/v1/skills': {get: {summary: 'List repository-owned Skills and role bindings', responses: {'200': {description: 'Repository Skill summaries'}}}},
    '/api/v1/skills/{skillId}': {get: {summary: 'Read one repository-owned SKILL.md', parameters: [{name: 'skillId', in: 'path', required: true, schema: {type: 'string'}}], responses: {'200': {description: 'Skill source and metadata'}, '404': {description: 'Skill not found'}}}},
    '/api/v1/manual-publish-handoffs': {
      get: {summary: 'List historical desktop manual-publish receipts and the current fail-closed authorization gate', responses: {'200': {description: 'Read-only history plus MANUAL_PUBLISH_AUDIT_OWNER_DECISION_REQUIRED'}}},
      post: {summary: 'Fail closed until an independent Audit PASS and exact external-action OwnerDecision authorize the Revision', requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/ManualPublishHandoffInput'}}}}, responses: {'409': {description: 'No handoff row created; Audit PASS and exact external-action OwnerDecision are absent'}, '404': {description: 'Exact Campaign/artifact/platform binding not found'}, '422': {description: 'Closed schema or browser Secret field rejected; review exports are not handoff actions'}}}
    },
    '/api/v1/campaigns': {
      get: {summary: 'List organization-scoped Campaigns', parameters: [organizationHeader()], responses: {'200': {description: 'Campaign summaries'}}},
      post: {summary: 'Create a DEMO_SEED Campaign; LOCAL_PRIVATE authority can be created only by the local onboarding route', parameters: [organizationHeader(), idempotencyHeader()], requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/CampaignDocument'}}}}, responses: {'201': {description: 'Created'}, '403': {description: 'LOCAL_PRIVATE creation rejected outside onboarding'}, '409': {description: 'Idempotency conflict'}, '422': {description: 'Domain validation failed'}, '428': {description: 'Required control header missing'}}}
    },
    '/api/v1/campaigns/{campaignId}': {
      get: {summary: 'Reopen a Campaign', parameters: [organizationHeader(), campaignId()], responses: {'200': {description: 'Campaign aggregate'}, '404': {description: 'Not found'}}},
      put: {summary: 'Save a new Campaign snapshot and server-derive any appended schedule rows', parameters: [organizationHeader(), idempotencyHeader(), ifMatchHeader(), campaignId()], requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/CampaignDocument'}}}}, responses: {'200': {description: 'Saved'}, '409': {description: 'Idempotency conflict'}, '412': {description: 'ETag conflict'}, '422': {description: 'Domain validation failed'}, '428': {description: 'Required control header missing'}}}
    },
    '/api/v1/campaigns/{campaignId}/mission-contract': {get: {summary: 'Read the persisted future AgentTeams adapter input contract', parameters: [organizationHeader(), campaignId()], responses: {'200': {description: 'Mission contract/source digest'}, '404': {description: 'Not found'}}}},
    '/api/v1/campaigns/{campaignId}/schedule-preview': {post: {summary: 'Resolve an IANA wall time and constrained RRULE without executing it', parameters: [organizationHeader(), campaignId()], requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/SchedulePreviewInput'}}}}, responses: {'200': {description: 'Non-live proposal; Campaign PUT validates it and re-derives authoritative schedule/occurrence IDs, timestamps, states, scope, and ArtifactRevision bindings'}, '422': {description: 'Invalid IANA zone, DST gap, or constrained RRULE'}}}},
    '/api/v1/campaigns/demo-template': {get: {summary: 'Return a public-safe, non-persisted DEMO_SEED template', responses: {'200': {description: 'Synthetic Campaign document'}}}},
    '/api/v1/campaigns/{campaignId}/shadow-missions': {
      get: {summary: 'List PostgreSQL-owned SHADOW Missions', parameters: [organizationHeader(), campaignId()], responses: {'200': {description: 'Mission list'}}},
      post: {summary: 'Queue an exact-digest six-member DEMO_SEED SHADOW Mission; LOCAL_PRIVATE runtime waits for SDD-007', parameters: [organizationHeader(), idempotencyHeader(), ifMatchHeader(), campaignId()], responses: {'201': {description: 'Queued; no external action'}, '403': {description: 'LOCAL_PRIVATE persistent runtime is not implemented until SDD-007'}}}
    },
    '/api/v1/shadow-missions/{missionId}': {get: {summary: 'Reopen a governed Mission with business state and progressively disclosed evidence', parameters: [organizationHeader()], responses: {'200': {description: 'Mission'}}}},
    '/api/v1/shadow-missions/{missionId}/live-runner/tickets': {post: {summary: 'Exchange a secret-file bootstrap for one short-lived, single-Mission/role/Task/attempt/action ticket', parameters: [organizationHeader()], responses: {'200': {description: 'Single-use scoped ticket; no-store'}, '403': {description: 'Bootstrap unavailable or invalid'}, '409': {description: 'Persisted Mission/Task state is not ready'}, '422': {description: 'Runtime source/image/Mission binding mismatch'}}}},
    '/api/v1/shadow-missions/{missionId}/live-model-generate': {post: {summary: 'Generate one non-Leader domain result through the server-only DeepSeek broker and persist a redacted receipt', parameters: [organizationHeader(), runtimeTicketHeader()], responses: {'200': {description: 'Normalized role output and redacted Canary receipt'}, '403': {description: 'Scoped ticket invalid/reused/expired'}, '502': {description: 'Provider/schema/semantic failure; no Mock fallback'}, '503': {description: 'Compose secret file unavailable; no Mock fallback'}}}},
    '/api/v1/shadow-missions/{missionId}/live-runner/fail': {post: {summary: 'Persist a fail-closed local Runner interruption without fallback', parameters: [organizationHeader(), runtimeTicketHeader()], responses: {'200': {description: 'FAILED state persisted'}}}},
    '/api/v1/shadow-missions/{missionId}/runtime-events': {post: {summary: 'Import exact Project dispatch, Task ACK/Submit, and finalization events from the authenticated AgentTeams adapter; digest/schema/role validation is authoritative in PostgreSQL', parameters: [organizationHeader(), idempotencyHeader(), ifMatchHeader(), runtimeImportHeader()], responses: {'200': {description: 'Runtime event accepted'}, '403': {description: 'Runtime adapter authentication failed'}, '422': {description: 'Runtime submission quarantined or schema rejected'}, '503': {description: 'Runtime import disabled until an ephemeral token is configured'}}}},
    '/api/v1/shadow-missions/{missionId}/public-safe-flight': {post: {summary: 'Run deterministic MOCK_CONFORMANCE fault/re-audit flight; never claims real AgentTeams', parameters: [organizationHeader(), idempotencyHeader(), ifMatchHeader()], responses: {'200': {description: 'Public-safe conformance result'}}}},
    '/api/v1/shadow-missions/{missionId}/owner-reviews': {post: {summary: 'Record exact NON_EXECUTABLE Owner Review; never creates ActionGrant', parameters: [organizationHeader(), idempotencyHeader(), ifMatchHeader()], responses: {'200': {description: 'Review recorded'}}}},
    '/api/v1/shadow-missions/{missionId}/evidence': {get: {summary: 'Export allowlisted, redacted, replayable evidence', parameters: [organizationHeader()], responses: {'200': {description: 'Public-safe evidence'}}}}
  },
  components: {schemas: {
    CampaignDocument: campaignDocumentSchema,
    OrganizationGraph: organizationGraphSchema,
    LocalOwnerProfileInput: {type: 'object', additionalProperties: false, required: ['displayName'], properties: {displayName: {type: 'string', minLength: 1, maxLength: 64}}},
    LocalCampaignIdentityInput: {type: 'object', additionalProperties: false, required: ['organizationName', 'brandName', 'brandPositioning', 'productName', 'productDescription', 'campaignName', 'campaignObjective', 'callToAction'], properties: {organizationName: {type: 'string', minLength: 1, maxLength: 120}, brandName: {type: 'string', minLength: 1, maxLength: 120}, brandPositioning: {type: 'string', minLength: 1, maxLength: 1000}, productName: {type: 'string', minLength: 1, maxLength: 120}, productDescription: {type: 'string', minLength: 1, maxLength: 2000}, campaignName: {type: 'string', minLength: 1, maxLength: 120}, campaignObjective: {type: 'string', minLength: 1, maxLength: 2000}, callToAction: {type: 'string', minLength: 1, maxLength: 500}}},
    LocalOnboardingContext: {type: 'object', additionalProperties: false, required: ['marketCode', 'contentLocale', 'platform', 'timeZone'], properties: {marketCode: {type: 'string', pattern: '^[A-Z]{2}$'}, contentLocale: {type: 'string', pattern: '^[a-z]{2}(?:-[A-Z]{2})?$'}, platform: {enum: ['X', 'BLUESKY', 'LINKEDIN', 'XIAOHONGSHU']}, timeZone: {type: 'string', minLength: 1, maxLength: 80}}},
    ManualPublishHandoffInput: {type: 'object', additionalProperties: false, required: ['organizationId', 'campaignId', 'artifactRevisionId', 'platform', 'action'], properties: {organizationId: {type: 'string', format: 'uuid'}, campaignId: {type: 'string', format: 'uuid'}, artifactRevisionId: {type: 'string', format: 'uuid'}, platform: {enum: ['X', 'BLUESKY', 'LINKEDIN', 'XIAOHONGSHU']}, action: {enum: ['OPEN_OFFICIAL_PAGE', 'OWNER_REPORTED_COMPLETE']}}},
    SchedulePreviewInput: {type: 'object', additionalProperties: false, required: ['localStart', 'timeZone', 'foldPreference', 'misfirePolicy'], properties: {localStart: {type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}$'}, timeZone: {type: 'string', minLength: 1}, rrule: {type: ['string', 'null'], description: 'M1 accepts exactly FREQ=DAILY|WEEKLY;INTERVAL=1..30;COUNT=1..50.'}, foldPreference: {enum: ['EARLIER', 'LATER']}, misfirePolicy: {enum: ['SKIP', 'HOLD_FOR_OWNER']}}}
  }}
} as const;

function organizationHeader() { return {name: 'X-LumiClaw-Organization-Id', in: 'header', required: true, schema: {type: 'string', format: 'uuid'}} as const; }
function idempotencyHeader() { return {name: 'Idempotency-Key', in: 'header', required: true, schema: {type: 'string', minLength: 8, maxLength: 128}} as const; }
function ifMatchHeader() { return {name: 'If-Match', in: 'header', required: true, schema: {type: 'string'}} as const; }
function runtimeImportHeader() { return {name: 'X-LumiClaw-Runtime-Import-Token', in: 'header', required: true, schema: {type: 'string', minLength: 32}, description: 'Ephemeral adapter-to-control-plane credential; never persisted in Mission, trace, ledger, evidence, or source packages.'} as const; }
function runtimeTicketHeader() { return {name: 'X-LumiClaw-Runtime-Ticket', in: 'header', required: true, schema: {type: 'string', minLength: 32}, description: 'Ten-minute single-use ticket bound to one local UAT Mission, role, Task, attempt and action; never persisted or logged.'} as const; }
function campaignId() { return {name: 'campaignId', in: 'path', required: true, schema: {type: 'string', format: 'uuid'}} as const; }
