import {campaignDocumentSchema, organizationGraphSchema} from '@lumiclaw/domain';

export const openApiDocument = {
  openapi: '3.1.0',
  info: {title: 'LumiClaw Presence Control API', version: '0.5.0-sdd009', description: 'Local-first approved knowledge, persistent 7/30-day Goal/Plan and deterministic selected X/Xiaohongshu Mission bundle control plane. Controlled Planner fixtures are labeled and no AgentTeams run, Artifact, ActionGrant, connector, publishing, growth, lead, or revenue result is claimed.'},
  servers: [{url: '/'}],
  paths: {
    '/api/v1/local-workspace': {get: {summary: 'Reopen the PostgreSQL-owned local profile, recoverable knowledge onboarding, Campaign, historical handoffs and publish-authorization gate', responses: {'200': {description: 'No-store local workspace and KnowledgeOverview with row-version ETag; publishing remains blocked'}}}},
    '/api/v1/local-owner-profile': {post: {summary: 'Create the single local display-name-only Owner profile', requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/LocalOwnerProfileInput'}}}}, responses: {'201': {description: 'Local profile ready; no email, password or remote registration'}, '422': {description: 'Closed schema or browser Secret field rejected'}}}},
    '/api/v1/local-owner': {
      get: {summary: 'Reopen the display-name-only local Owner', responses: {'200': {description: 'Local Owner profile'}, '428': {description: 'Local profile required'}}},
      patch: {summary: 'Create an immutable display-name revision without accepting remote identity or Secret fields', requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/LocalOwnerProfileInput'}}}}, responses: {'200': {description: 'Display name updated'}, '422': {description: 'Closed schema or Secret-shaped field rejected'}, '428': {description: 'Local profile required'}}}
    },
    '/api/v1/onboarding/session': {
      get: {summary: 'Recover the current guided onboarding step and KnowledgeOverview', responses: {'200': {description: 'No-store PostgreSQL-owned draft with ETag'}, '428': {description: 'Local profile required'}}},
      put: {summary: 'Save a guided step and independent default Market, Content Locale, and IANA Time Zone', parameters: [idempotencyHeader(), knowledgeIfMatchHeader()], requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/KnowledgeSessionInput'}}}}, responses: {'200': {description: 'Draft saved and new snapshot revision derived'}, '409': {description: 'Idempotency conflict or stale snapshot'}, '422': {description: 'Closed schema or invalid stable code'}, '428': {description: 'Required Owner or concurrency header missing'}}}
    },
    '/api/v1/profiles/persona': {put: knowledgeProfileOperation('Save a new immutable founder/persona profile revision', '#/components/schemas/PersonaProfileInput')},
    '/api/v1/profiles/organization': {put: knowledgeProfileOperation('Save a new immutable organization/brand profile revision', '#/components/schemas/OrganizationProfileInput')},
    '/api/v1/profiles/product': {put: knowledgeProfileOperation('Save a new immutable product profile revision', '#/components/schemas/ProductProfileInput')},
    '/api/v1/profiles/accounts/{platform}': {put: {summary: 'Save one immutable non-secret X or Xiaohongshu operating profile; platform market/locale remain independent', parameters: [idempotencyHeader(), knowledgeIfMatchHeader(), {name: 'platform', in: 'path', required: true, schema: {enum: ['X', 'XIAOHONGSHU']}}], requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/AccountOperatingProfileInput'}}}}, responses: {'200': {description: 'Account profile revision and both platform bindings preserved in the draft'}, '409': {description: 'Idempotency conflict or stale snapshot'}, '422': {description: 'Closed schema, platform mismatch, or Secret-shaped value rejected'}, '428': {description: 'Required Owner or concurrency header missing'}}}},
    '/api/v1/knowledge/sources': {post: {summary: 'Persist one ordinary-user MD/TXT upload as a content-addressed Blob, immutable SourceDocumentRevision, and reviewable source excerpt', parameters: [idempotencyHeader(), knowledgeIfMatchHeader(), {name: 'X-LumiClaw-File-Name', in: 'header', required: true, schema: {type: 'string', minLength: 3, maxLength: 180}}], requestBody: {required: true, content: {'text/markdown': {schema: {type: 'string', format: 'binary', maxLength: 2097152}}, 'text/plain': {schema: {type: 'string', format: 'binary', maxLength: 2097152}}}}, responses: {'201': {description: 'Source content remains usable in snapshot item/source bindings without candidate JSON'}, '409': {description: 'Idempotency conflict or stale snapshot'}, '413': {description: '2 MiB limit exceeded'}, '422': {description: 'UTF-8/type/Secret-shaped value rejected; PDF/DOCX/audio return planned code'}, '428': {description: 'Required Owner or concurrency header missing'}}}},
    '/api/v1/knowledge/sources/text': {post: {summary: 'Persist ordinary pasted text as a content-addressed immutable source; no KnowledgeItem or candidate JSON is accepted from the Web form', parameters: [idempotencyHeader(), knowledgeIfMatchHeader()], requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/KnowledgeTextSourceInput'}}}}, responses: {'201': {description: 'Text source and deterministic excerpt binding created'}, '409': {description: 'Idempotency conflict or stale snapshot'}, '422': {description: 'Closed schema, empty text, or Secret-shaped value rejected'}, '428': {description: 'Required Owner or concurrency header missing'}}}},
    '/api/v1/knowledge/sources/{sourceId}': {
      get: {summary: 'View the current source revision and original extracted text', parameters: [knowledgeSourceId()], responses: {'200': {description: 'Source revision with digest and reviewable text'}, '404': {description: 'Source not found'}}},
      delete: {summary: 'Delete the current source binding and immediately invalidate the current approval path', parameters: [idempotencyHeader(), knowledgeIfMatchHeader(), knowledgeSourceId()], responses: {'200': {description: 'New fail-closed draft derived; history remains immutable'}, '409': {description: 'Idempotency conflict or stale snapshot'}}}
    },
    '/api/v1/knowledge/sources/{sourceId}/confirm': {post: {summary: 'Confirm a migrated legacy source by creating a new immutable READY revision', parameters: [idempotencyHeader(), knowledgeIfMatchHeader(), knowledgeSourceId()], responses: {'200': {description: 'New confirmed revision and source excerpt binding created'}, '409': {description: 'Idempotency conflict or stale snapshot'}}}},
    '/api/v1/knowledge/snapshots/draft': {get: {summary: 'Read structured candidates, source bindings, conflicts, gaps and the exact draft digest', responses: {'200': {description: 'Current immutable draft and KnowledgeOverview'}, '428': {description: 'Local profile required'}}}},
    '/api/v1/knowledge/snapshots/resolve-conflict': {post: {summary: 'Record an explicit Owner authority decision; conflicting values are never silently overwritten', parameters: [idempotencyHeader(), knowledgeIfMatchHeader()], requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/KnowledgeConflictResolutionInput'}}}}, responses: {'200': {description: 'Decision persisted and new digest derived'}, '409': {description: 'Idempotency conflict or stale snapshot'}, '422': {description: 'Closed schema or invalid selection'}}}},
    '/api/v1/knowledge/snapshots/approve': {post: {summary: 'Approve one exact digest as an immutable AuthoritativeKnowledgeSnapshot; fails closed on gaps, conflicts, stale revision, or missing Blob', parameters: [idempotencyHeader(), knowledgeIfMatchHeader()], requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/KnowledgeSnapshotApprovalInput'}}}}, responses: {'200': {description: 'Exact AuthoritativeKnowledgeSnapshot approved; no Agent or Goal launched'}, '409': {description: 'Stale/missing/conflicting/incomplete knowledge blocks approval'}, '422': {description: 'Closed schema or digest mismatch'}}}},
    '/api/v1/knowledge/snapshots/{snapshotId}/role-context': {get: {summary: 'Read RoleContext only for the current approved exact snapshot and digest', parameters: [{name: 'snapshotId', in: 'path', required: true, schema: {type: 'string', format: 'uuid'}}, {name: 'X-LumiClaw-Snapshot-Digest', in: 'header', required: true, schema: {type: 'string', pattern: '^[a-f0-9]{64}$'}}], responses: {'200': {description: 'Approved source/profile/item bindings including both platform account profiles'}, '409': {description: 'Unapproved, stale, changed, deleted, or missing source fails closed'}, '428': {description: 'Exact snapshot digest required'}}}},
    '/api/v1/goals': {
      get:{summary:'Reopen all append-only Goal/Plan/Bundle revisions and effective invalidation states',responses:{'200':{description:'Owner-scoped persistent Goal workspace'}}},
      post:{summary:'Create a 7/30-day OperatingGoal DRAFT bound to one current APPROVED Snapshot and explicitly selected account revisions',parameters:[idempotencyHeader(),knowledgeIfMatchHeader()],requestBody:{required:true,content:{'application/json':{schema:{$ref:'#/components/schemas/OperatingGoalInput'}}}},responses:{'201':{description:'Immutable Goal revision created'},'409':{description:'Idempotency or Producer coverage conflict'},'412':{description:'Snapshot/account binding changed'},'422':{description:'Closed schema, date, locale, market, time-zone or success-signal error'}}}
    },
    '/api/v1/goals/{goalId}':{get:{summary:'Reopen the current Goal revision',parameters:[goalId()],responses:{'200':{description:'Current Goal with exact digest/ETag'},'404':{description:'Goal not found'}}},patch:{summary:'Create a new DRAFT Goal revision; never mutates prior revisions',parameters:[goalId(),idempotencyHeader(),ifMatchHeader()],requestBody:{required:true,content:{'application/json':{schema:{$ref:'#/components/schemas/OperatingGoalPatch'}}}},responses:{'200':{description:'New immutable revision; affected bundles invalidated'},'412':{description:'Stale exact digest/ETag'}}}},
    '/api/v1/goals/{goalId}/activate':{post:{summary:'Create a new ACTIVE Goal revision from an exact DRAFT/PAUSED digest',parameters:[goalId(),idempotencyHeader(),ifMatchHeader()],requestBody:{required:true,content:{'application/json':{schema:{$ref:'#/components/schemas/ExactDigestInput'}}}},responses:{'200':{description:'Goal activated'},'409':{description:'State conflict'},'412':{description:'Stale digest'}}}},
    '/api/v1/goals/{goalId}/pause':{post:{summary:'Create a new PAUSED Goal revision and invalidate affected compiled bundles',parameters:[goalId(),idempotencyHeader(),ifMatchHeader()],requestBody:{required:true,content:{'application/json':{schema:{$ref:'#/components/schemas/ExactDigestInput'}}}},responses:{'200':{description:'Goal paused'},'409':{description:'State conflict'},'412':{description:'Stale digest'}}}},
    '/api/v1/missions/compile':{post:{summary:'Deterministically compile MissionIntent generation 1 from the current ACTIVE Goal, APPROVED Snapshot and only selected X/Xiaohongshu account revisions',parameters:[idempotencyHeader(),ifMatchHeader()],requestBody:{required:true,content:{'application/json':{schema:{$ref:'#/components/schemas/MissionCompileInput'}}}},responses:{'201':{description:'Exactly-six-role MissionIntent compiled; AgentTeams not run'},'409':{description:'PRODUCER_COVERAGE_REQUIRED'},'412':{description:'Stale/tampered input binding'},'422':{description:'Unsupported platform/compiler or closed schema'}}}},
    '/api/v1/mission-bundles/{bundleId}':{get:{summary:'Read one immutable Intent/Execution generation plus effective invalidation reason and recovery action',parameters:[bundleId()],responses:{'200':{description:'Bundle lineage, DAG, input digests and effective state'},'404':{description:'Bundle not found'}}}},
    '/api/v1/content-plans':{post:{summary:'Import a closed-schema Planner submission after exact role/input/schema/Skill digest validation',parameters:[idempotencyHeader(),ifMatchHeader()],requestBody:{required:true,content:{'application/json':{schema:{$ref:'#/components/schemas/PlannerSubmissionV2'}}}},responses:{'201':{description:'Immutable DRAFT/NEEDS_OWNER plan; controlled fixtures remain explicitly labeled'},'412':{description:'Intent digest changed'},'422':{description:'Role/input/schema/Skill/slot binding invalid'}}}},
    '/api/v1/content-plans/{planId}':{get:{summary:'Reopen the current content-plan revision',parameters:[planId()],responses:{'200':{description:'Plan, slots, current brief and exact digest'}}},patch:{summary:'Create a new Owner-edited plan revision',parameters:[planId(),idempotencyHeader(),ifMatchHeader()],requestBody:{required:true,content:{'application/json':{schema:{$ref:'#/components/schemas/ContentPlanEditInput'}}}},responses:{'200':{description:'New immutable revision'},'412':{description:'Stale exact digest'}}}},
    '/api/v1/content-plans/{planId}/approve':{post:{summary:'Approve an exact Plan digest and atomically append the deterministic selected-platform Execution generation',parameters:[planId(),idempotencyHeader(),ifMatchHeader()],requestBody:{required:true,content:{'application/json':{schema:{$ref:'#/components/schemas/ExactDigestInput'}}}},responses:{'200':{description:'APPROVED Plan revision and Execution bundle; no AgentTeams run or external action'},'412':{description:'Stale/tampered binding'},'422':{description:'Incomplete or invalid selected-platform plan'}}}},
    '/api/v1/local-onboarding/example': {post: {summary: 'Choose the public-safe example Organization and Campaign path exactly once', responses: {'201': {description: 'Public-safe example context persisted; external action remains disabled'}, '409': {description: 'LOCAL_ONBOARDING_ALREADY_COMPLETED; completed authority cannot be reopened or replaced'}, '428': {description: 'Local profile required'}}}},
    '/api/v1/local-onboarding/materials-path': {post: {summary: 'Choose the real local-material path before onboarding completion', responses: {'200': {description: 'MD/TXT support and PDF/DOCX PLANNED status returned'}, '409': {description: 'LOCAL_ONBOARDING_ALREADY_COMPLETED; completed authority cannot be reopened'}, '428': {description: 'Local profile required'}}}},
    '/api/v1/local-onboarding/context': {post: {summary: 'Persist multi-select Markets, content Locales, preferred Platforms and one default IANA schedule Time Zone before completion', requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/LocalOnboardingContext'}}}}, responses: {'200': {description: 'Context persisted'}, '409': {description: 'LOCAL_ONBOARDING_ALREADY_COMPLETED; completed context is immutable through onboarding endpoints'}, '422': {description: 'Closed schema, invalid code or browser Secret field rejected'}, '428': {description: 'Local profile required'}}}},
    '/api/v1/local-onboarding/complete': {post: {summary: 'Create a user-confirmed LOCAL_PRIVATE Organization, Brand, Product and Campaign exactly once', requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/LocalCampaignIdentityInput'}}}}, responses: {'200': {description: 'Authoritative LOCAL_PRIVATE Campaign persisted; external action remains disabled'}, '409': {description: 'LOCAL_ONBOARDING_ALREADY_COMPLETED; completed authority cannot be replaced'}, '422': {description: 'Materials/context not ready or closed identity schema invalid'}, '428': {description: 'Local profile required'}}}},
    '/api/v1/local-materials': {
      get: {summary: 'List local material manifests without returning raw Blob bytes', responses: {'200': {description: 'No-store material manifests'}, '428': {description: 'Local profile required'}}},
      post: {summary: 'Extract and persist one UTF-8 MD/TXT file server-side before onboarding completion', parameters: [{name: 'X-LumiClaw-File-Name', in: 'header', required: true, schema: {type: 'string', minLength: 3, maxLength: 180}}], requestBody: {required: true, content: {'text/markdown': {schema: {type: 'string', format: 'binary', maxLength: 2097152}}, 'text/plain': {schema: {type: 'string', format: 'binary', maxLength: 2097152}}}}, responses: {'201': {description: 'Manifest and content-addressed Blob persisted'}, '409': {description: 'LOCAL_ONBOARDING_ALREADY_COMPLETED; use a future authoritative Campaign update/invalidation flow'}, '413': {description: '2 MiB limit exceeded'}, '422': {description: 'Filename, UTF-8, binary or media type rejected; PDF/DOCX return PLANNED code'}, '428': {description: 'Local profile required'}}}
    },
    '/api/v1/local-materials/{materialId}': {delete: {summary: 'Delete an unbound onboarding material; completed-Campaign evidence fails closed', parameters: [{name: 'materialId', in: 'path', required: true, schema: {type: 'string', format: 'uuid'}}], responses: {'200': {description: 'Unbound material deleted'}, '404': {description: 'Material not found'}, '409': {description: 'LOCAL_MATERIAL_BOUND_TO_CAMPAIGN; use a future retract/invalidate flow'}}}},
    '/api/v1/environment-readiness': {get: {summary: 'Probe Web/API/PostgreSQL/AgentTeams adapter/runtime using deterministic provenance-bearing states', responses: {'200': {description: 'No-store readiness; unconfigured runtime reports SDD_007_REQUIRED and never fabricated green'}}}},
    '/api/v1/ai-team': {get: {summary: 'Return the six stable Agent roles and NO_RUNTIME_OBSERVATION metrics', responses: {'200': {description: 'A0-A5 responsibility roster; zero means no authoritative observation'}}}},
    '/api/v1/skills': {get: {summary: 'List repository-owned Skills and role bindings', responses: {'200': {description: 'Repository Skill summaries'}}}},
    '/api/v1/skills/{skillId}': {get: {summary: 'Read one repository-owned SKILL.md', parameters: [{name: 'skillId', in: 'path', required: true, schema: {type: 'string'}}], responses: {'200': {description: 'Skill source and metadata'}, '404': {description: 'Skill not found'}}}},
    '/api/v1/manual-publish-handoffs': {
      get: {summary: 'List historical desktop manual-publish receipts and the current fail-closed authorization gate', responses: {'200': {description: 'Read-only history plus MANUAL_PUBLISH_AUDIT_OWNER_DECISION_REQUIRED'}}},
      post: {summary: 'Fail closed until an independent Audit PASS and exact external-action OwnerDecision authorize the Revision', requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/ManualPublishHandoffInput'}}}}, responses: {'409': {description: 'No handoff row created; Audit PASS and exact external-action OwnerDecision are absent'}, '404': {description: 'Exact Campaign/artifact/platform binding not found'}, '422': {description: 'Closed schema or browser Secret field rejected; review exports are not handoff actions'}}}
    },
    '/api/v1/campaigns': {
      get: {summary: 'List organization-scoped Campaigns', parameters: [organizationHeader()], responses: {'200': {description: 'Campaign summaries'}}},
      post: {summary: 'Create a DEMO_SEED Campaign; LOCAL_PRIVATE authority can be created only by the local onboarding route', parameters: [organizationHeader(), idempotencyHeader()], requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/CampaignDocument'}}}}, responses: {'201': {description: 'Created'}, '403': {description: 'LOCAL_PRIVATE creation rejected outside onboarding'}, '409': {description: 'Idempotency conflict'}, '422': {description: 'Domain validation failed'}, '428': {description: 'Required control header missing'}}}
    },
    '/api/v1/campaigns/{campaignId}': {
      get: {summary: 'Reopen a Campaign', parameters: [organizationHeader(), campaignId()], responses: {'200': {description: 'Campaign aggregate'}, '404': {description: 'Not found'}}},
      put: {summary: 'Save a new Campaign snapshot and server-derive any appended schedule rows', parameters: [organizationHeader(), idempotencyHeader(), ifMatchHeader(), campaignId()], requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/CampaignDocument'}}}}, responses: {'200': {description: 'Saved'}, '409': {description: 'Idempotency conflict'}, '412': {description: 'ETag conflict'}, '422': {description: 'Domain validation failed'}, '428': {description: 'Required control header missing'}}}
    },
    '/api/v1/campaigns/{campaignId}/mission-contract': {get: {summary: 'Read the persisted future AgentTeams adapter input contract', parameters: [organizationHeader(), campaignId()], responses: {'200': {description: 'Mission contract/source digest'}, '404': {description: 'Not found'}}}},
    '/api/v1/campaigns/{campaignId}/schedule-preview': {post: {summary: 'Resolve an IANA wall time and constrained RRULE without executing it', parameters: [organizationHeader(), campaignId()], requestBody: {required: true, content: {'application/json': {schema: {$ref: '#/components/schemas/SchedulePreviewInput'}}}}, responses: {'200': {description: 'Non-live proposal; Campaign PUT validates it and re-derives authoritative schedule/occurrence IDs, timestamps, states, scope, and ArtifactRevision bindings'}, '422': {description: 'Invalid IANA zone, DST gap, or constrained RRULE'}}}},
    '/api/v1/campaigns/demo-template': {get: {summary: 'Return a public-safe, non-persisted DEMO_SEED template', responses: {'200': {description: 'Synthetic Campaign document'}}}},
    '/api/v1/campaigns/{campaignId}/shadow-missions': {
      get: {summary: 'List PostgreSQL-owned SHADOW Missions', parameters: [organizationHeader(), campaignId()], responses: {'200': {description: 'Mission list'}}},
      post: {summary: 'Queue an exact-digest six-member DEMO_SEED SHADOW Mission; LOCAL_PRIVATE runtime waits for SDD-007', parameters: [organizationHeader(), idempotencyHeader(), ifMatchHeader(), campaignId()], responses: {'201': {description: 'Queued; no external action'}, '403': {description: 'LOCAL_PRIVATE persistent runtime is not implemented until SDD-007'}}}
    },
    '/api/v1/shadow-missions/{missionId}': {get: {summary: 'Reopen a governed Mission with business state and progressively disclosed evidence', parameters: [organizationHeader()], responses: {'200': {description: 'Mission'}}}},
    '/api/v1/shadow-missions/{missionId}/live-runner/tickets': {post: {summary: 'Exchange a secret-file bootstrap for one short-lived, single-Mission/role/Task/attempt/action ticket', parameters: [organizationHeader()], responses: {'200': {description: 'Single-use scoped ticket; no-store'}, '403': {description: 'Bootstrap unavailable or invalid'}, '409': {description: 'Persisted Mission/Task state is not ready'}, '422': {description: 'Runtime source/image/Mission binding mismatch'}}}},
    '/api/v1/shadow-missions/{missionId}/live-model-generate': {post: {summary: 'Generate one non-Leader domain result through the server-only DeepSeek broker and persist a redacted receipt', parameters: [organizationHeader(), runtimeTicketHeader()], responses: {'200': {description: 'Normalized role output and redacted Canary receipt'}, '403': {description: 'Scoped ticket invalid/reused/expired'}, '502': {description: 'Provider/schema/semantic failure; no Mock fallback'}, '503': {description: 'Compose secret file unavailable; no Mock fallback'}}}},
    '/api/v1/shadow-missions/{missionId}/live-runner/fail': {post: {summary: 'Persist a fail-closed local Runner interruption without fallback', parameters: [organizationHeader(), runtimeTicketHeader()], responses: {'200': {description: 'FAILED state persisted'}}}},
    '/api/v1/shadow-missions/{missionId}/runtime-events': {post: {summary: 'Import exact Project dispatch, Task ACK/Submit, and finalization events from the authenticated AgentTeams adapter; digest/schema/role validation is authoritative in PostgreSQL', parameters: [organizationHeader(), idempotencyHeader(), ifMatchHeader(), runtimeImportHeader()], responses: {'200': {description: 'Runtime event accepted'}, '403': {description: 'Runtime adapter authentication failed'}, '422': {description: 'Runtime submission quarantined or schema rejected'}, '503': {description: 'Runtime import disabled until an ephemeral token is configured'}}}},
    '/api/v1/shadow-missions/{missionId}/public-safe-flight': {post: {summary: 'Run deterministic MOCK_CONFORMANCE fault/re-audit flight; never claims real AgentTeams', parameters: [organizationHeader(), idempotencyHeader(), ifMatchHeader()], responses: {'200': {description: 'Public-safe conformance result'}}}},
    '/api/v1/shadow-missions/{missionId}/owner-reviews': {post: {summary: 'Record exact NON_EXECUTABLE Owner Review; never creates ActionGrant', parameters: [organizationHeader(), idempotencyHeader(), ifMatchHeader()], responses: {'200': {description: 'Review recorded'}}}},
    '/api/v1/shadow-missions/{missionId}/evidence': {get: {summary: 'Export allowlisted, redacted, replayable evidence', parameters: [organizationHeader()], responses: {'200': {description: 'Public-safe evidence'}}}}
  },
  components: {schemas: {
    CampaignDocument: campaignDocumentSchema,
    OrganizationGraph: organizationGraphSchema,
    LocalOwnerProfileInput: {type: 'object', additionalProperties: false, required: ['displayName'], properties: {displayName: {type: 'string', minLength: 1, maxLength: 64}}},
    KnowledgeSessionInput: {type: 'object', additionalProperties: false, required: ['currentStep'], properties: {currentStep: {enum: ['PERSONA','ORGANIZATION_PRODUCT','SOURCES','X_ACCOUNT','XIAOHONGSHU_ACCOUNT','MARKET_CONTEXT','REVIEW']}, targetMarket: {type: ['string','null'], pattern: '^[A-Z]{2}$'}, contentLocale: {type: ['string','null'], pattern: '^[a-z]{2}(?:-[A-Z]{2})?$'}, timeZone: {type: ['string','null'], minLength: 1, maxLength: 80}}},
    PersonaProfileInput: {type: 'object', additionalProperties: false, required: ['displayName','role','voice','viewpoints','expressionBoundaries','firstPersonRelationship','expressionExamples'], properties: {displayName: shortText(120), role: shortText(300), voice: shortText(1200), viewpoints: textList(12,500), expressionBoundaries: textList(16,500), firstPersonRelationship: shortText(1000), expressionExamples: textList(12,1000)}},
    OrganizationProfileInput: {type: 'object', additionalProperties: false, required: ['name','brandName','description','audiences','facts','approvedClaims'], properties: {name: shortText(160), brandName: shortText(160), description: shortText(3000), audiences: textList(16,500), facts: textList(40,1000), approvedClaims: approvedClaims()}},
    ProductProfileInput: {type: 'object', additionalProperties: false, required: ['name','description','valueProposition','audiences','facts','approvedClaims'], properties: {name: shortText(160), description: shortText(3000), valueProposition: shortText(2000), audiences: textList(16,500), facts: textList(40,1000), approvedClaims: approvedClaims()}},
    AccountOperatingProfileInput: {type: 'object', additionalProperties: false, required: ['platformCode','accountExists','handleOrDisplayName','producerMandates','rolePersona','audience','targetMarket','contentLocale','contentPillars','expressionExamples','dos','donts','ctaPolicy','cadenceHint'], description: 'Non-secret operating profile only. Password, Cookie, OAuth token, API key, and connection credentials are neither modeled nor accepted.', properties: {platformCode: {enum: ['X','XIAOHONGSHU']}, accountExists: {type: 'boolean'}, handleOrDisplayName: shortText(160), producerMandates: {type: 'array', minItems: 1, maxItems: 2, uniqueItems: true, items: {enum: ['FOUNDER_VOICE','PRODUCT_EXPERTISE']}}, rolePersona: shortText(1000), audience: textList(16,500), targetMarket: {type: 'string', pattern: '^[A-Z]{2}$'}, contentLocale: {type: 'string', pattern: '^[a-z]{2}(?:-[A-Z]{2})?$'}, contentPillars: textList(16,500), expressionExamples: textList(12,1000), dos: textList(20,500), donts: textList(20,500), ctaPolicy: shortText(1000), cadenceHint: shortText(500)}},
    KnowledgeTextSourceInput: {type: 'object', additionalProperties: false, required: ['label','text'], description: 'Ordinary Web contract. Candidate JSON and technical metadata are deliberately absent.', properties: {label: shortText(180), text: shortText(2097152)}},
    KnowledgeConflictResolutionInput: {type: 'object', additionalProperties: false, required: ['conflictId','selectedItemId','note'], properties: {conflictId: {type: 'string', format: 'uuid'}, selectedItemId: {type: 'string', format: 'uuid'}, note: shortText(1000)}},
    KnowledgeSnapshotApprovalInput: {type: 'object', additionalProperties: false, required: ['snapshotId','canonicalDigest'], properties: {snapshotId: {type: 'string', format: 'uuid'}, canonicalDigest: {type: 'string', pattern: '^[a-f0-9]{64}$'}}},
    GoalSuccessSignal:{type:'object',additionalProperties:false,required:['code','observation'],properties:{code:{enum:['PUBLISHING_CADENCE','VOICE_CONSISTENCY','OWNER_ACCEPTANCE_RATE','MARKET_LEARNING_NOTES']},observation:shortText(500)}},
    OperatingGoalInput:{type:'object',additionalProperties:false,required:['objective','horizonDays','startsAt','endsAt','cadence','selectedAccountIds','targetMarket','contentLocale','timeZone','successSignals','knowledgeSnapshotId','knowledgeSnapshotDigest'],properties:goalInputProperties()},
    OperatingGoalPatch:{type:'object',additionalProperties:false,required:['canonicalDigest','objective','horizonDays','startsAt','endsAt','cadence','selectedAccountIds','targetMarket','contentLocale','timeZone','successSignals','knowledgeSnapshotId','knowledgeSnapshotDigest'],properties:{...goalInputProperties(),canonicalDigest:digestSchema()}},
    ExactDigestInput:{type:'object',additionalProperties:false,required:['canonicalDigest'],properties:{canonicalDigest:digestSchema()}},
    MissionCompileInput:{type:'object',additionalProperties:false,required:['goalId','goalDigest'],properties:{goalId:{type:'string'},goalDigest:digestSchema()}},
    ContentPlanSlot:{type:'object',additionalProperties:false,required:['slotId','localDate','localTime','platformCode','accountProfileRevisionId','producerRole','theme','contentObjective','claimConstraints','sourceItemIds','status'],properties:{slotId:{type:'string'},localDate:{type:'string',format:'date'},localTime:{type:['string','null'],pattern:'^(?:[01]\\d|2[0-3]):[0-5]\\d$'},platformCode:{enum:['X','XIAOHONGSHU']},accountProfileRevisionId:{type:'string',format:'uuid'},producerRole:{enum:['founder-identity-producer','product-account-producer']},theme:shortText(500),contentObjective:shortText(1000),claimConstraints:{type:'array',maxItems:20,items:shortText(1000)},sourceItemIds:{type:'array',minItems:1,maxItems:100,items:{type:'string'}},status:{const:'PLANNED'}}},
    ContentBrief:{type:'object',additionalProperties:false,required:['briefId','slotId','platformCode','accountProfileRevisionId','producerRole','theme','contentObjective','sourceItemIds','claimConstraints'],properties:{briefId:{type:'string'},slotId:{type:'string'},platformCode:{enum:['X','XIAOHONGSHU']},accountProfileRevisionId:{type:'string',format:'uuid'},producerRole:{enum:['founder-identity-producer','product-account-producer']},theme:shortText(500),contentObjective:shortText(1000),sourceItemIds:{type:'array',minItems:1,items:{type:'string'}},claimConstraints:{type:'array',items:{type:'string'}}}},
    PlanSourceBinding:{type:'object',additionalProperties:false,required:['snapshotId','snapshotDigest','sourceItemIds','claimConstraints'],properties:{snapshotId:{type:'string',format:'uuid'},snapshotDigest:digestSchema(),sourceItemIds:{type:'array',minItems:1,items:{type:'string'}},claimConstraints:{type:'array',items:{type:'string'}}}},
    PlannerSubmissionV2:{type:'object',additionalProperties:false,required:['schemaVersion','roleId','missionIntentId','intentBundleId','intentBundleDigest','taskId','inputDigest','outputSchema','outputSchemaDigest','skillLockDigest','slots','currentBrief','sourceBindings','evidenceMaturity'],properties:{schemaVersion:{const:2},roleId:{const:'campaign-planner'},missionIntentId:{type:'string'},intentBundleId:{type:'string'},intentBundleDigest:digestSchema(),taskId:{type:'string'},inputDigest:digestSchema(),outputSchema:{const:'lumiclaw.content-plan.v2'},outputSchemaDigest:digestSchema(),skillLockDigest:digestSchema(),slots:{type:'array',minItems:1,maxItems:30,items:{$ref:'#/components/schemas/ContentPlanSlot'}},currentBrief:{$ref:'#/components/schemas/ContentBrief'},sourceBindings:{type:'array',minItems:1,items:{$ref:'#/components/schemas/PlanSourceBinding'}},evidenceMaturity:{enum:['CONTROLLED_FIXTURE','AGENTTEAMS_RUNTIME']}}},
    ContentPlanEditInput:{type:'object',additionalProperties:false,required:['canonicalDigest','slots','currentBrief','sourceBindings'],properties:{canonicalDigest:digestSchema(),slots:{type:'array',minItems:1,maxItems:30,items:{$ref:'#/components/schemas/ContentPlanSlot'}},currentBrief:{$ref:'#/components/schemas/ContentBrief'},sourceBindings:{type:'array',minItems:1,items:{$ref:'#/components/schemas/PlanSourceBinding'}}}},
    LocalCampaignIdentityInput: {type: 'object', additionalProperties: false, required: ['organizationName', 'brandName', 'brandPositioning', 'productName', 'productDescription', 'campaignName', 'campaignObjective', 'callToAction'], properties: {organizationName: {type: 'string', minLength: 1, maxLength: 120}, brandName: {type: 'string', minLength: 1, maxLength: 120}, brandPositioning: {type: 'string', minLength: 1, maxLength: 1000}, productName: {type: 'string', minLength: 1, maxLength: 120}, productDescription: {type: 'string', minLength: 1, maxLength: 2000}, campaignName: {type: 'string', minLength: 1, maxLength: 120}, campaignObjective: {type: 'string', minLength: 1, maxLength: 2000}, callToAction: {type: 'string', minLength: 1, maxLength: 500}}},
    LocalOnboardingContext: {type: 'object', additionalProperties: false, required: ['marketCodes', 'contentLocales', 'platforms', 'defaultTimeZone'], properties: {marketCodes: {type: 'array', minItems: 1, maxItems: 12, uniqueItems: true, items: {type: 'string', pattern: '^[A-Z]{2}$'}}, contentLocales: {type: 'array', minItems: 1, maxItems: 12, uniqueItems: true, items: {type: 'string', pattern: '^[a-z]{2}(?:-[A-Z]{2})?$'}}, platforms: {type: 'array', minItems: 1, maxItems: 4, uniqueItems: true, items: {enum: ['X', 'BLUESKY', 'LINKEDIN', 'XIAOHONGSHU']}}, defaultTimeZone: {type: 'string', minLength: 1, maxLength: 80}}},
    ManualPublishHandoffInput: {type: 'object', additionalProperties: false, required: ['organizationId', 'campaignId', 'artifactRevisionId', 'platform', 'action'], properties: {organizationId: {type: 'string', format: 'uuid'}, campaignId: {type: 'string', format: 'uuid'}, artifactRevisionId: {type: 'string', format: 'uuid'}, platform: {enum: ['X', 'BLUESKY', 'LINKEDIN', 'XIAOHONGSHU']}, action: {enum: ['OPEN_OFFICIAL_PAGE', 'OWNER_REPORTED_COMPLETE']}}},
    SchedulePreviewInput: {type: 'object', additionalProperties: false, required: ['localStart', 'timeZone', 'foldPreference', 'misfirePolicy'], properties: {localStart: {type: 'string', pattern: '^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}$'}, timeZone: {type: 'string', minLength: 1}, rrule: {type: ['string', 'null'], description: 'M1 accepts exactly FREQ=DAILY|WEEKLY;INTERVAL=1..30;COUNT=1..50.'}, foldPreference: {enum: ['EARLIER', 'LATER']}, misfirePolicy: {enum: ['SKIP', 'HOLD_FOR_OWNER']}}}
  }}
} as const;

function organizationHeader() { return {name: 'X-LumiClaw-Organization-Id', in: 'header', required: true, schema: {type: 'string', format: 'uuid'}} as const; }
function idempotencyHeader() { return {name: 'Idempotency-Key', in: 'header', required: true, schema: {type: 'string', minLength: 8, maxLength: 128}} as const; }
function ifMatchHeader() { return {name: 'If-Match', in: 'header', required: true, schema: {type: 'string'}} as const; }
function goalId(){return {name:'goalId',in:'path',required:true,schema:{type:'string'}} as const;}
function planId(){return {name:'planId',in:'path',required:true,schema:{type:'string'}} as const;}
function bundleId(){return {name:'bundleId',in:'path',required:true,schema:{type:'string'}} as const;}
function digestSchema(){return {type:'string',pattern:'^[a-f0-9]{64}$'} as const;}
function goalInputProperties(){return {objective:shortText(2000),horizonDays:{enum:[7,30]},startsAt:{type:'string',format:'date'},endsAt:{type:'string',format:'date'},cadence:{enum:['DAILY','WEEKDAYS','THREE_PER_WEEK']},selectedAccountIds:{type:'array',minItems:1,maxItems:2,uniqueItems:true,items:{type:'string',format:'uuid'}},targetMarket:{type:'string',pattern:'^[A-Z]{2}$'},contentLocale:{type:'string',pattern:'^[a-z]{2}(?:-[A-Z]{2})?$'},timeZone:shortText(80),successSignals:{type:'array',minItems:1,maxItems:4,uniqueItems:true,items:{$ref:'#/components/schemas/GoalSuccessSignal'}},knowledgeSnapshotId:{type:'string',format:'uuid'},knowledgeSnapshotDigest:digestSchema()} as const;}
function knowledgeIfMatchHeader() { return {name: 'If-Match', in: 'header', required: true, schema: {type: 'string', pattern: '^"knowledge-[0-9]+"$'}, description: 'Exact PostgreSQL onboarding row version.'} as const; }
function knowledgeSourceId() { return {name: 'sourceId', in: 'path', required: true, schema: {type: 'string', format: 'uuid'}} as const; }
function knowledgeProfileOperation(summary: string, schema: string) { return {summary, parameters: [idempotencyHeader(), knowledgeIfMatchHeader()], requestBody: {required: true, content: {'application/json': {schema: {$ref: schema}}}}, responses: {'200': {description: 'Immutable profile revision saved and new snapshot revision derived'}, '409': {description: 'Idempotency conflict or stale snapshot'}, '422': {description: 'Closed schema or Secret-shaped value rejected'}, '428': {description: 'Required Owner or concurrency header missing'}}} as const; }
function shortText(maxLength: number) { return {type: 'string', minLength: 1, maxLength} as const; }
function textList(maxItems: number, maxLength: number) { return {type: 'array', minItems: 1, maxItems, uniqueItems: true, items: shortText(maxLength)} as const; }
function approvedClaims() { return {type: 'array', maxItems: 20, items: {type: 'object', additionalProperties: false, required: ['statement','evidence'], properties: {statement: shortText(2000), evidence: shortText(2000)}}} as const; }
function runtimeImportHeader() { return {name: 'X-LumiClaw-Runtime-Import-Token', in: 'header', required: true, schema: {type: 'string', minLength: 32}, description: 'Ephemeral adapter-to-control-plane credential; never persisted in Mission, trace, ledger, evidence, or source packages.'} as const; }
function runtimeTicketHeader() { return {name: 'X-LumiClaw-Runtime-Ticket', in: 'header', required: true, schema: {type: 'string', minLength: 32}, description: 'Ten-minute single-use ticket bound to one local UAT Mission, role, Task, attempt and action; never persisted or logged.'} as const; }
function campaignId() { return {name: 'campaignId', in: 'path', required: true, schema: {type: 'string', format: 'uuid'}} as const; }
