import {AGENTTEAMS_IMAGE_DIGESTS,AGENTTEAMS_SOURCE_COMMIT,AGENTTEAMS_SOURCE_TAR_SHA256,missionRunEtag,PersistentRuntimeError,type MissionRun,type PersistentRuntimeRepository} from '@lumiclaw/domain';
import {afterEach,describe,expect,it} from 'vitest';
import {buildApi} from './server.js';

const apps:Array<ReturnType<typeof buildApi>>=[];afterEach(async()=>{await Promise.all(apps.splice(0).map((app)=>app.close()));});
const runId='runtime-mutation-public-safe';
const baseRun:MissionRun={schemaVersion:1,id:runId,ownerId:'owner-filled-by-api',bundleId:'bundle-public-safe',bundleDigest:'a'.repeat(64),bundleKind:'MISSION_INTENT',generation:1,runtimeRequirement:{runtime:'agentteams',version:'v1.2.0',sourceCommit:AGENTTEAMS_SOURCE_COMMIT,sourceTarSha256:AGENTTEAMS_SOURCE_TAR_SHA256,license:'Apache-2.0',imageDigests:AGENTTEAMS_IMAGE_DIGESTS,teamProfileVersion:'2.0.0',teamProfileDigest:'b'.repeat(64)},state:'QUEUED',createdBy:'owner',createdAt:'2026-08-22T12:00:00.000Z',startedAt:null,finishedAt:null,lastReconciledAt:null,errorCode:null,rowVersion:1};

describe('runtime mutation HTTP concurrency contract',()=>{it('requires exact MissionRun ETag + Idempotency-Key and exposes exact replay',async()=>{const repository=new MutationRepository();const app=buildApi({persistentRuntimeRepository:repository as unknown as PersistentRuntimeRepository});apps.push(app);await app.inject({method:'POST',url:'/api/v1/local-owner-profile',payload:{displayName:'Runtime Owner'}});
  expect((await app.inject({method:'POST',url:`/api/v1/mission-runs/${runId}/cancel`,headers:{'idempotency-key':'runtime-cancel-0001'}})).statusCode).toBe(428);
  expect((await app.inject({method:'POST',url:`/api/v1/mission-runs/${runId}/cancel`,headers:{'idempotency-key':'runtime-cancel-0001','if-match':'"runtime-run-wrong-v1"'}})).statusCode).toBe(428);
  const request={method:'POST' as const,url:`/api/v1/mission-runs/${runId}/cancel`,headers:{'idempotency-key':'runtime-cancel-0001','if-match':missionRunEtag(baseRun)}};const responses=await Promise.all([app.inject(request),app.inject(request)]);expect(responses.map((item)=>item.statusCode)).toEqual([200,200]);expect(responses.map((item)=>item.headers['idempotency-replayed']).sort()).toEqual(['false','true']);expect(new Set(responses.map((item)=>item.headers.etag))).toEqual(new Set([missionRunEtag({...baseRun,rowVersion:2})]));expect(repository.mutationCount).toBe(1);
});
  it('maps unsafe blocked retry to stable reconciliation review required',async()=>{const repository=new MutationRepository();repository.retryReview=true;const app=buildApi({persistentRuntimeRepository:repository as unknown as PersistentRuntimeRepository});apps.push(app);await app.inject({method:'POST',url:'/api/v1/local-owner-profile',payload:{displayName:'Runtime Owner'}});const response=await app.inject({method:'POST',url:`/api/v1/mission-runs/${runId}/retry-blocked`,headers:{'idempotency-key':'runtime-retry-0001','if-match':missionRunEtag(baseRun)}});expect(response.statusCode).toBe(409);expect(response.json().code).toBe('RECOVERY_REVIEW_REQUIRED');});
  it('maps a repository row-version conflict to 412 with the stable code and current ETag',async()=>{const repository=new MutationRepository();repository.versionConflict=true;const app=buildApi({persistentRuntimeRepository:repository as unknown as PersistentRuntimeRepository});apps.push(app);await app.inject({method:'POST',url:'/api/v1/local-owner-profile',payload:{displayName:'Runtime Owner'}});const response=await app.inject({method:'POST',url:`/api/v1/mission-runs/${runId}/cancel`,headers:{'idempotency-key':'runtime-cancel-stale-0001','if-match':missionRunEtag(baseRun)}});const current=missionRunEtag({...baseRun,rowVersion:2});expect(response.statusCode).toBe(412);expect(response.json()).toMatchObject({code:'RUN_VERSION_CONFLICT',currentEtag:current});expect(response.headers.etag).toBe(current);});
});

class MutationRepository{public mutationCount=0;public retryReview=false;public versionConflict=false;private result?:MissionRun;private key?:string;async health(){return true;}async getWorkerHeartbeat(){return null;}async cancelRun(_owner:string,_runId:string,_version:number,key:string){if(this.versionConflict)throw new PersistentRuntimeError('RUN_VERSION_CONFLICT','RUN_VERSION_CONFLICT',{runId,rowVersion:2});if(this.key===key&&this.result!==undefined)return {run:this.result,replayed:true};this.key=key;this.mutationCount+=1;this.result={...baseRun,state:'CANCELLED',rowVersion:2,finishedAt:'2026-08-22T12:01:00.000Z'};return {run:this.result,replayed:false};}async retryBlocked(){if(this.retryReview)throw new PersistentRuntimeError('RECOVERY_REVIEW_REQUIRED');return {run:{...baseRun,state:'QUEUED'},replayed:false};}async close(){}}
