import {chmod,mkdtemp,readdir,readFile,stat,symlink,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {afterEach,describe,expect,it,vi} from 'vitest';

const original=process.env.LUMICLAW_RUNTIME_SECRET_ROOT;
afterEach(()=>{vi.resetModules();if(original===undefined)delete process.env.LUMICLAW_RUNTIME_SECRET_ROOT;else process.env.LUMICLAW_RUNTIME_SECRET_ROOT=original;});
describe('terminal-only persistent runtime Secret CLI',()=>{
  it('writes only 0600 files under a 0700 root and returns fingerprint/configured without the key',async()=>{const root=await mkdtemp(path.join(tmpdir(),'lumiclaw-sdd007-secret-'));process.env.LUMICLAW_RUNTIME_SECRET_ROOT=root;const secretCli=await import('./persistent-runtime-secret-cli.mjs');const key='public-safe-test-value-that-never-reaches-output';const status=await secretCli.configureDeepSeek(async()=>key);expect(status).toMatchObject({configured:true,mode:'0600_COMPOSE_SECRET',updatedAt:expect.any(String)});expect(JSON.stringify(status)).not.toContain(key);expect((await stat(root)).mode&0o777).toBe(0o700);for(const name of ['deepseek-api-key','runtime-gateway-bootstrap','model-ticket-signing'])expect((await stat(path.join(root,name))).mode&0o777).toBe(0o600);expect(await readFile(path.join(root,'deepseek-api-key'),'utf8')).toBe(`${key}\n`);});

  it('rejects an external symlink and an unsafe existing file mode instead of following or replacing them',async()=>{const root=await mkdtemp(path.join(tmpdir(),'lumiclaw-sdd007-secret-symlink-'));const external=path.join(await mkdtemp(path.join(tmpdir(),'lumiclaw-sdd007-external-')),'provider-key');await writeFile(external,'external-secret\n',{mode:0o600});await symlink(external,path.join(root,'deepseek-api-key'));process.env.LUMICLAW_RUNTIME_SECRET_ROOT=root;let secretCli=await import('./persistent-runtime-secret-cli.mjs');await expect(secretCli.secretStatus()).rejects.toThrow('SECRET_FILE_SYMLINK_FORBIDDEN');
    const realRoot=await mkdtemp(path.join(tmpdir(),'lumiclaw-sdd007-real-root-'));const rootLink=`${realRoot}-link`;await symlink(realRoot,rootLink);await expect(secretCli.prepareSecretRoot(rootLink)).rejects.toThrow('SECRET_ROOT_SYMLINK_FORBIDDEN');
    const safeRoot=await mkdtemp(path.join(tmpdir(),'lumiclaw-sdd007-secret-mode-'));process.env.LUMICLAW_RUNTIME_SECRET_ROOT=safeRoot;vi.resetModules();secretCli=await import('./persistent-runtime-secret-cli.mjs');await secretCli.configureDeepSeek(async()=>'public-safe-second-value-0123456789');await chmod(path.join(safeRoot,'deepseek-api-key'),0o644);await expect(secretCli.configureDeepSeek(async()=>'replacement-provider-secret-0123456789')).rejects.toThrow('SECRET_FILE_MODE_MUST_BE_0600');expect((await readdir(safeRoot)).filter((name)=>name.startsWith('deepseek-api-key.'))).toEqual([]);await expect(secretCli.secretStatus()).rejects.toThrow('SECRET_FILE_MODE_MUST_BE_0600');
  });

  it('removes the exact secret-bearing temporary file when the atomic rename fails',async()=>{const root=await mkdtemp(path.join(tmpdir(),'lumiclaw-sdd007-secret-rename-'));process.env.LUMICLAW_RUNTIME_SECRET_ROOT=root;const secretCli=await import('./persistent-runtime-secret-cli.mjs');const target=path.join(root,'deepseek-api-key');await expect(secretCli.atomicSecret(target,'provider-secret-that-must-not-remain-0123456789',root,async()=>{throw new Error('FORCED_RENAME_FAILURE');})).rejects.toThrow('FORCED_RENAME_FAILURE');expect((await readdir(root)).filter((name)=>name.startsWith('deepseek-api-key.'))).toEqual([]);await expect(readFile(target,'utf8')).rejects.toMatchObject({code:'ENOENT'});});
});
