import {PostgresModelGatewayTicketRepository} from '@lumiclaw/db';
import {PersistentRuntimeError,runtimeGatewayPolicyDigest,runtimeGatewayRequestDigest,sha256Digest,type ModelGatewayTicketClaims,type ModelGatewayTicketRepository,type RuntimeGatewayGenerateRequest} from '@lumiclaw/domain';
import {DeepSeekModelProvider,PublicSafeMockModelProvider,type ModelProvider} from '@lumiclaw/governed-shadow';
import {ModelGatewayTicketSigner} from '@lumiclaw/runtime-agentteams';
import {randomBytes,timingSafeEqual} from 'node:crypto';
import {readFile,stat} from 'node:fs/promises';
import {Ajv2020,type ErrorObject} from 'ajv/dist/2020.js';
import Fastify,{type FastifyInstance} from 'fastify';

type GatewayMode='DEEPSEEK_CANARY'|'CONTROLLED_FAKE';
type TicketRequest=Omit<ModelGatewayTicketClaims,'schemaVersion'|'expiresAt'|'nonce'>;
type GenerateRequest=RuntimeGatewayGenerateRequest&{controlledOutput?:unknown};
type BuildOptions={repository:ModelGatewayTicketRepository;mode:GatewayMode;bootstrapSecret:string;signingSecret:string;deepseekApiKey?:string;secretUpdatedAt?:string;now?:()=>Date;providerFactory?:(input:{mode:GatewayMode;apiKey?:string;controlledOutput?:unknown;now:()=>Date})=>ModelProvider};

export function buildModelGateway(options:BuildOptions):FastifyInstance{
  const app=Fastify({logger:false,bodyLimit:1_048_576});const now=options.now??(()=>new Date());const signer=new ModelGatewayTicketSigner(options.signingSecret);const configured=options.mode==='CONTROLLED_FAKE'||typeof options.deepseekApiKey==='string';const ajv=new Ajv2020({allErrors:true,strict:true,formats:{'date-time':true}});
  app.addHook('onClose',()=>options.repository.close());
  app.get('/health',async(_request,reply)=>{const db=await options.repository.health().catch(()=>false);const state=!db?'UNREACHABLE':!configured?'NOT_CONFIGURED':'READY';return reply.status(state==='READY'?200:503).header('cache-control','no-store').send({service:'model-gateway',state,providerMode:options.mode,controlledFake:options.mode==='CONTROLLED_FAKE',configured:options.mode==='DEEPSEEK_CANARY'&&configured,fingerprint:options.deepseekApiKey===undefined?null:secretFingerprint(options.deepseekApiKey),updatedAt:options.secretUpdatedAt??null,ticketSignerFingerprint:signer.fingerprint(),secretPresentInResponse:false});});
  app.get('/internal/v1/secret-status',async(_request,reply)=>reply.header('cache-control','no-store').send({configured:options.mode==='DEEPSEEK_CANARY'&&configured,fingerprint:options.deepseekApiKey===undefined?null:secretFingerprint(options.deepseekApiKey),updatedAt:options.secretUpdatedAt??null,collection:'TERMINAL_ONLY',setKeyApi:false}));
  app.post('/internal/v1/tickets',async(request,reply)=>{authorize(request.headers['x-lumiclaw-gateway-bootstrap'],options.bootstrapSecret);if(!ticketRequest(request.body))throw new PersistentRuntimeError('SUBMISSION_SCHEMA_INVALID');const expiresAt=new Date(now().getTime()+60_000).toISOString();const claims:ModelGatewayTicketClaims={schemaVersion:1,...request.body,expiresAt,nonce:randomBytes(32).toString('base64url')};const issued=signer.issue(claims);await options.repository.issue(claims,issued.ticketDigest,now());return reply.status(201).header('cache-control','no-store').send({ticket:issued.ticket,expiresAt,claimsDigest:sha256Digest(safeClaims(claims))});});
  app.post('/internal/v1/generate',async(request,reply)=>{const rawTicket=request.headers['x-lumiclaw-model-ticket'];if(typeof rawTicket!=='string')throw new PersistentRuntimeError('MODEL_TICKET_REPLAYED');const body=parseGenerateRequest(request.body,options.mode);const verified=signer.verify(rawTicket);assertGenerateBinding(verified.claims,body);const validate=ajv.compile(body.outputSchema);const outcome=await options.repository.consume(verified.claims,verified.ticketDigest,now());if(outcome!=='USED')throw new PersistentRuntimeError(outcome==='REPLAYED'?'MODEL_TICKET_REPLAYED':outcome==='EXPIRED'?'TASK_SUBMIT_TIMEOUT':'SUBMISSION_INPUT_MISMATCH');if(!configured)throw new PersistentRuntimeError('RUNTIME_NOT_CONFIGURED');const provider=options.providerFactory?.({mode:options.mode,...(options.deepseekApiKey===undefined?{}:{apiKey:options.deepseekApiKey}),...(body.controlledOutput===undefined?{}:{controlledOutput:body.controlledOutput}),now})??(options.mode==='CONTROLLED_FAKE'?new PublicSafeMockModelProvider(body.controlledOutput,now):new DeepSeekModelProvider({apiKey:options.deepseekApiKey!,executionClass:'CANARY'}));const result=await provider.generateStructured({missionId:body.runId,taskId:body.taskId,model:body.model,system:body.system,input:body.input,outputSchema:body.outputSchema,maxAttempts:1});if(!result.ok)throw new PersistentRuntimeError('MODEL_PROVIDER_FAILED',result.snapshot.error?.code??'MODEL_PROVIDER_FAILED');if(!validate(result.value))throw new PersistentRuntimeError('SUBMISSION_SCHEMA_INVALID','MODEL_OUTPUT_SCHEMA_INVALID',{errors:validate.errors?.map((item:ErrorObject)=>({instancePath:item.instancePath,keyword:item.keyword}))??[]});return reply.header('cache-control','no-store').send({ok:true,value:result.value,outputDigest:sha256Digest(result.value),provider:result.snapshot.provider,maturity:result.snapshot.maturity,controlledFake:options.mode==='CONTROLLED_FAKE',ticketDigest:verified.ticketDigest,snapshot:{...result.snapshot,secretPresent:false}});});
  app.setErrorHandler((error,_request,reply)=>{const code=error instanceof PersistentRuntimeError?error.code:'MODEL_PROVIDER_FAILED';const status=code==='MODEL_TICKET_REPLAYED'?409:code==='RUNTIME_NOT_CONFIGURED'?503:422;return reply.status(status).send({code,secretPresentInResponse:false});});return app;
}

function ticketRequest(value:unknown):value is TicketRequest{if(!record(value))return false;const keys=['attemptId','attemptNumber','inputDigest','jobId','leaseTokenDigest','model','outputSchema','ownerId','phase','policyDigest','requestDigest','runId','runtimeActorId','runtimeTaskId','taskId','workerIdDigest'];return Object.keys(value).sort().join(',')===keys.sort().join(',')&&typeof value.ownerId==='string'&&typeof value.runId==='string'&&typeof value.jobId==='string'&&typeof value.taskId==='string'&&typeof value.attemptId==='string'&&typeof value.runtimeTaskId==='string'&&value.runtimeTaskId.length>0&&typeof value.runtimeActorId==='string'&&Number.isSafeInteger(value.attemptNumber)&&digest(value.workerIdDigest)&&digest(value.leaseTokenDigest)&&['ORCHESTRATE','CLAIM','PLAN','PRODUCE','AUDIT'].includes(String(value.phase))&&['deepseek-v4-flash','deepseek-v4-pro'].includes(String(value.model))&&digest(value.policyDigest)&&digest(value.inputDigest)&&digest(value.requestDigest)&&typeof value.outputSchema==='string';}
function parseGenerateRequest(value:unknown,mode:GatewayMode):GenerateRequest{if(!record(value))throw new PersistentRuntimeError('SUBMISSION_SCHEMA_INVALID');const required=['attemptId','attemptNumber','input','inputDigest','jobId','leaseTokenDigest','model','outputSchema','outputSchemaRef','ownerId','phase','policyDigest','runId','runtimeActorId','runtimeTaskId','system','taskId','workerIdDigest'];const allowed=mode==='CONTROLLED_FAKE'?[...required,'controlledOutput']:required;if(Object.keys(value).sort().join(',')!==allowed.filter((key)=>key!=='controlledOutput'||'controlledOutput'in value).sort().join(',')||required.some((key)=>!(key in value))||typeof value.ownerId!=='string'||typeof value.runId!=='string'||typeof value.jobId!=='string'||typeof value.taskId!=='string'||typeof value.attemptId!=='string'||!Number.isSafeInteger(value.attemptNumber)||typeof value.runtimeTaskId!=='string'||value.runtimeTaskId.length===0||typeof value.runtimeActorId!=='string'||!digest(value.workerIdDigest)||!digest(value.leaseTokenDigest)||typeof value.system!=='string'||typeof value.outputSchemaRef!=='string'||!record(value.outputSchema)||!digest(value.policyDigest)||!digest(value.inputDigest)||!['ORCHESTRATE','CLAIM','PLAN','PRODUCE','AUDIT'].includes(String(value.phase))||!['deepseek-v4-flash','deepseek-v4-pro'].includes(String(value.model))||(mode==='CONTROLLED_FAKE'&&!('controlledOutput'in value)))throw new PersistentRuntimeError('SUBMISSION_SCHEMA_INVALID');return value as GenerateRequest;}
function assertGenerateBinding(claims:ModelGatewayTicketClaims,body:GenerateRequest){const {controlledOutput,...request}=body;void controlledOutput;const requestDigest=runtimeGatewayRequestDigest(request);const policyDigest=runtimeGatewayPolicyDigest({phase:body.phase,model:body.model,system:body.system,outputSchemaRef:body.outputSchemaRef,outputSchema:body.outputSchema});if(claims.ownerId!==body.ownerId||claims.runId!==body.runId||claims.jobId!==body.jobId||claims.taskId!==body.taskId||claims.attemptId!==body.attemptId||claims.attemptNumber!==body.attemptNumber||claims.runtimeTaskId!==body.runtimeTaskId||claims.runtimeActorId!==body.runtimeActorId||claims.workerIdDigest!==body.workerIdDigest||claims.leaseTokenDigest!==body.leaseTokenDigest||claims.phase!==body.phase||claims.model!==body.model||claims.policyDigest!==body.policyDigest||claims.policyDigest!==policyDigest||claims.inputDigest!==body.inputDigest||claims.requestDigest!==requestDigest||claims.outputSchema!==body.outputSchemaRef)throw new PersistentRuntimeError('SUBMISSION_INPUT_MISMATCH');}
function authorize(value:string|string[]|undefined,expected:string){if(typeof value!=='string')throw new PersistentRuntimeError('RUNTIME_UNREACHABLE');const left=Buffer.from(value);const right=Buffer.from(expected);if(left.length!==right.length||!timingSafeEqual(left,right))throw new PersistentRuntimeError('RUNTIME_UNREACHABLE');}
function safeClaims(claims:ModelGatewayTicketClaims){const {nonce,...rest}=claims;return {...rest,nonceDigest:sha256Digest(nonce)};}
function secretFingerprint(value:string){return sha256Digest({kind:'DEEPSEEK_API_KEY_FINGERPRINT_V1',value}).slice(0,16);}
function digest(value:unknown):value is string{return typeof value==='string'&&/^[a-f0-9]{64}$/u.test(value);}
function record(value:unknown):value is Record<string,unknown>{return value!==null&&typeof value==='object'&&!Array.isArray(value);}

async function readSecret(path:string,minimumBytes:number):Promise<{value:string;updatedAt:string}>{const metadata=await stat(path);if(!metadata.isFile()||(metadata.mode&0o077)!==0)throw new Error('SECRET_FILE_MODE_MUST_BE_0400_OR_0600');const value=(await readFile(path,'utf8')).trim();if(Buffer.byteLength(value)<minimumBytes)throw new Error('SECRET_FILE_VALUE_TOO_SHORT');return {value,updatedAt:metadata.mtime.toISOString()};}
async function start(){const connectionString=process.env.DATABASE_URL;if(connectionString===undefined)throw new Error('DATABASE_URL is required.');const mode=(process.env.MODEL_GATEWAY_MODE??'DEEPSEEK_CANARY') as GatewayMode;if(!['DEEPSEEK_CANARY','CONTROLLED_FAKE'].includes(mode))throw new Error('MODEL_GATEWAY_MODE_INVALID');const bootstrap=await readSecret(process.env.RUNTIME_GATEWAY_BOOTSTRAP_FILE??'/run/secrets/lumiclaw_runtime_gateway_bootstrap',32);const signing=await readSecret(process.env.MODEL_TICKET_SIGNING_SECRET_FILE??'/run/secrets/lumiclaw_model_ticket_signing',32);const deepseek=mode==='DEEPSEEK_CANARY'?await readSecret(process.env.DEEPSEEK_SECRET_FILE??'/run/secrets/deepseek_api_key',16):undefined;const app=buildModelGateway({repository:new PostgresModelGatewayTicketRepository(connectionString),mode,bootstrapSecret:bootstrap.value,signingSecret:signing.value,...(deepseek===undefined?{}:{deepseekApiKey:deepseek.value,secretUpdatedAt:deepseek.updatedAt})});await app.listen({host:'0.0.0.0',port:Number.parseInt(process.env.PORT??'4003',10)});}
if(process.argv[1]?.endsWith('/server.js'))start().catch((error:unknown)=>{console.error(error instanceof Error?error.message:'MODEL_GATEWAY_START_FAILED');process.exitCode=1;});
