import {runtimeGatewayPolicy,runtimeGatewayRequestDigest,sha256Digest,type ModelGatewayTicketClaims,type ModelGatewayTicketRepository,type RuntimeGatewayGenerateRequest,type RuntimeTaskContract} from '@lumiclaw/domain';
import {PublicSafeMockModelProvider} from '@lumiclaw/governed-shadow';
import {describe,expect,it} from 'vitest';
import {buildModelGateway} from './server.js';

const now=new Date('2026-08-22T12:00:00.000Z');
const contract:RuntimeTaskContract={schemaVersion:1,runId:'run-public-safe',bundleId:'bundle-public-safe',bundleDigest:'a'.repeat(64),generation:1,taskId:'task-orchestrate',roleId:'presence-mission-leader',kind:'ORCHESTRATE',mandate:'Coordinate only.',dependencyIds:[],inputDigest:'b'.repeat(64),skillLockDigest:'c'.repeat(64),outputSchema:'lumiclaw.orchestration-receipt.v2',substantive:false,externalActionAllowed:false};
const output={schemaVersion:1,taskId:contract.taskId,inputDigest:contract.inputDigest,agentTeamsExecuted:true,completed:true};

describe('SDD-007 Model Gateway binding',()=>{
  it('recomputes request/policy/schema before provider, validates output, and consumes once',async()=>{
    const repository=new MemoryTicketRepository();let providerCalls=0;const app=buildModelGateway({repository,mode:'CONTROLLED_FAKE',bootstrapSecret:'bootstrap-secret-value-01234567890123456789',signingSecret:'signing-secret-value-012345678901234567890',now:()=>now,providerFactory:({controlledOutput})=>{providerCalls+=1;return new PublicSafeMockModelProvider(controlledOutput,()=>now);}});
    const request=generateRequest();const ticket=await issue(app,request);const valid=await app.inject({method:'POST',url:'/internal/v1/generate',headers:{'x-lumiclaw-model-ticket':ticket},payload:{...request,controlledOutput:output}});expect(valid.statusCode,valid.body).toBe(200);expect(valid.json()).toMatchObject({ok:true,controlledFake:true,outputDigest:sha256Digest(output)});expect(providerCalls).toBe(1);
    const replay=await app.inject({method:'POST',url:'/internal/v1/generate',headers:{'x-lumiclaw-model-ticket':ticket},payload:{...request,controlledOutput:output}});expect(replay.statusCode).toBe(409);expect(replay.json().code).toBe('MODEL_TICKET_REPLAYED');expect(providerCalls).toBe(1);

    for(const tampered of [{...request,input:{...(request.input as Record<string,unknown>),tampered:true}},{...request,system:`${request.system} tampered`},{...request,outputSchema:{...request.outputSchema,additionalProperties:true}},{...request,runtimeTaskId:'task-runtime-other'},{...request,runtimeActorId:'@other:matrix.local'},{...request,workerIdDigest:'f'.repeat(64)},{...request,leaseTokenDigest:'0'.repeat(64)}]){const fresh=await issue(app,request);const response=await app.inject({method:'POST',url:'/internal/v1/generate',headers:{'x-lumiclaw-model-ticket':fresh},payload:{...tampered,controlledOutput:output}});expect(response.statusCode,response.body).toBe(422);expect(response.json().code).toBe('SUBMISSION_INPUT_MISMATCH');}
    expect(providerCalls).toBe(1);

    const schemaTicket=await issue(app,request);const invalidOutput={...output,additional:'forbidden'};const invalid=await app.inject({method:'POST',url:'/internal/v1/generate',headers:{'x-lumiclaw-model-ticket':schemaTicket},payload:{...request,controlledOutput:invalidOutput}});expect(invalid.statusCode).toBe(422);expect(invalid.json().code).toBe('MODEL_PROVIDER_FAILED');expect(providerCalls).toBe(2);
    await app.close();
  });

  it('fails closed on an unknown schema or role/kind mismatch',()=>{expect(()=>runtimeGatewayPolicy({...contract,outputSchema:'unknown.schema'},'ORCHESTRATE','deepseek-v4-flash')).toThrowError(expect.objectContaining({code:'SUBMISSION_INPUT_MISMATCH'}));expect(()=>runtimeGatewayPolicy({...contract,roleId:'campaign-planner'},'ORCHESTRATE','deepseek-v4-flash')).toThrowError(expect.objectContaining({code:'SUBMISSION_INPUT_MISMATCH'}));});

  it('keeps providerCalls at zero when PostgreSQL lease fencing rejects a stale ticket',async()=>{let providerCalls=0;const app=buildModelGateway({repository:new MemoryTicketRepository('REJECTED'),mode:'CONTROLLED_FAKE',bootstrapSecret:'bootstrap-secret-value-01234567890123456789',signingSecret:'signing-secret-value-012345678901234567890',now:()=>now,providerFactory:()=>{providerCalls+=1;return new PublicSafeMockModelProvider(output,()=>now);}});const request=generateRequest();const ticket=await issue(app,request);const response=await app.inject({method:'POST',url:'/internal/v1/generate',headers:{'x-lumiclaw-model-ticket':ticket},payload:{...request,controlledOutput:output}});expect(response.statusCode).toBe(422);expect(response.json().code).toBe('SUBMISSION_INPUT_MISMATCH');expect(providerCalls).toBe(0);await app.close();});
});

function generateRequest():RuntimeGatewayGenerateRequest{const phase='ORCHESTRATE' as const;const model='deepseek-v4-flash' as const;const policy=runtimeGatewayPolicy(contract,phase,model);const input={schemaVersion:1,task:{taskId:contract.taskId,inputDigest:contract.inputDigest},publicSafe:true};return {ownerId:'0199a000-0000-7000-8000-000000000009',runId:contract.runId,jobId:'job-public-safe',taskId:contract.taskId,attemptId:'attempt-public-safe',attemptNumber:1,runtimeTaskId:'runtime-task-public-safe',runtimeActorId:'@presence-mission-leader:matrix.local',workerIdDigest:'d'.repeat(64),leaseTokenDigest:'e'.repeat(64),phase,model,policyDigest:policy.digest,inputDigest:contract.inputDigest,outputSchemaRef:contract.outputSchema,system:policy.system,input,outputSchema:policy.outputSchema};}
async function issue(app:ReturnType<typeof buildModelGateway>,request:RuntimeGatewayGenerateRequest){const ticketRequest={ownerId:request.ownerId,runId:request.runId,jobId:request.jobId,taskId:request.taskId,attemptId:request.attemptId,attemptNumber:request.attemptNumber,runtimeTaskId:request.runtimeTaskId,runtimeActorId:request.runtimeActorId,workerIdDigest:request.workerIdDigest,leaseTokenDigest:request.leaseTokenDigest,phase:request.phase,model:request.model,policyDigest:request.policyDigest,inputDigest:request.inputDigest,requestDigest:runtimeGatewayRequestDigest(request),outputSchema:request.outputSchemaRef};const response=await app.inject({method:'POST',url:'/internal/v1/tickets',headers:{'x-lumiclaw-gateway-bootstrap':'bootstrap-secret-value-01234567890123456789'},payload:ticketRequest});expect(response.statusCode,response.body).toBe(201);return response.json().ticket as string;}
class MemoryTicketRepository implements ModelGatewayTicketRepository{readonly used=new Set<string>();public constructor(private readonly forced?:'REJECTED'){}public async health(){return true;}public async issue(claims:ModelGatewayTicketClaims,digest:string,now:Date){void claims;void digest;void now;}public async consume(claims:ModelGatewayTicketClaims,digest:string){void claims;if(this.forced!==undefined)return this.forced;if(this.used.has(digest))return 'REPLAYED' as const;this.used.add(digest);return 'USED' as const;}public async close(){} }
