import type {AccountOperatingProfileInput, ArtifactAuditDecision, ArtifactOwnerDecision, ArtifactPayload, ArtifactRevisionV3,ArtifactRevisionV4, AuditFinding, AuditResult, ContentBrief, ContentPlanRevision, ContentPlanSlot, KnowledgeOverview, KnowledgePlatform, KnowledgeStep, LocalCampaignIdentityInput, LocalOnboardingContext, ManualPublishPackage,ManualPublishPackageV4,MediaAuditDecisionV4, MediaGenerationJob,MediaOwnerDecisionV4,MediaWorkspace, MissionExecutionBundle, MissionIntentBundle, OperatingGoalInput, OperatingGoalRevision, OrganizationProfileInput, OwnerArtifactDecisionResult, PersonaProfileInput, PlanSourceBinding, PlannerSubmission, ProductProfileInput, ProfileKind} from '@lumiclaw/domain';
import type {EnvironmentReadiness, SkillListResponse, TeamResponse, WorkspaceSnapshot} from './production-types';

export class ProductApiError extends Error {
  public constructor(public readonly code: string, public readonly status: number) { super(code); this.name = 'ProductApiError'; }
}

export async function loadWorkspace(): Promise<WorkspaceSnapshot> { return requestJson('/api/v1/local-workspace'); }
export async function loadReadiness(): Promise<EnvironmentReadiness> { return requestJson('/api/v1/environment-readiness'); }
export async function loadTeam(): Promise<TeamResponse> { return requestJson('/api/v1/ai-team'); }
export async function loadSkills(): Promise<SkillListResponse> { return requestJson('/api/v1/skills'); }
export async function createLocalProfile(displayName: string): Promise<void> { await requestJson('/api/v1/local-owner-profile', {method: 'POST', body: JSON.stringify({displayName}), headers: {'content-type': 'application/json'}}); }
export async function selectExampleWorkspace(): Promise<void> { await requestJson('/api/v1/local-onboarding/example', {method: 'POST'}); }
export async function selectMaterialPath(): Promise<void> { await requestJson('/api/v1/local-onboarding/materials-path', {method: 'POST'}); }
export async function uploadLocalMaterial(file: File): Promise<void> {
  await requestJson('/api/v1/local-materials', {method: 'POST', body: await file.arrayBuffer(), headers: {'content-type': file.type || 'application/octet-stream', 'x-lumiclaw-file-name': encodeURIComponent(file.name)}});
}
export async function saveOnboardingContext(context: LocalOnboardingContext): Promise<void> { await requestJson('/api/v1/local-onboarding/context', {method: 'POST', body: JSON.stringify(context), headers: {'content-type': 'application/json'}}); }
export async function completeLocalOnboarding(identity: LocalCampaignIdentityInput): Promise<void> { await requestJson('/api/v1/local-onboarding/complete', {method: 'POST', body: JSON.stringify(identity), headers: {'content-type': 'application/json'}}); }
export async function deleteLocalMaterial(materialId: string): Promise<void> { await requestJson(`/api/v1/local-materials/${materialId}`, {method: 'DELETE'}); }
type KnowledgeMutationResponse={overview:KnowledgeOverview};
const knowledgeHeaders=(version:number,key:string):HeadersInit=>({'content-type':'application/json','if-match':`"knowledge-${version}"`,'idempotency-key':key});
const knowledgeControlHeaders=(version:number,key:string):HeadersInit=>({'if-match':`"knowledge-${version}"`,'idempotency-key':key});
const mutationKey=(prefix:string)=>`${prefix}-${crypto.randomUUID()}`;
export async function saveKnowledgeProfile(kind:Exclude<ProfileKind,'ACCOUNT'>,payload:PersonaProfileInput|OrganizationProfileInput|ProductProfileInput,version:number,nextStep:KnowledgeStep):Promise<KnowledgeOverview>{const saved=await requestJson<KnowledgeMutationResponse>(`/api/v1/profiles/${kind.toLowerCase()}`,{method:'PUT',headers:knowledgeHeaders(version,mutationKey(`profile-${kind}`)),body:JSON.stringify(payload)});return saveKnowledgeSession(saved.overview.session.rowVersion,{currentStep:nextStep});}
export async function saveAccountProfile(platform:KnowledgePlatform,payload:AccountOperatingProfileInput,version:number,nextStep:KnowledgeStep):Promise<KnowledgeOverview>{const saved=await requestJson<KnowledgeMutationResponse>(`/api/v1/profiles/accounts/${platform}`,{method:'PUT',headers:knowledgeHeaders(version,mutationKey(`account-${platform}`)),body:JSON.stringify(payload)});return saveKnowledgeSession(saved.overview.session.rowVersion,{currentStep:nextStep});}
export async function saveKnowledgeSession(version:number,input:{currentStep:KnowledgeStep;targetMarket?:string|null;contentLocale?:string|null;timeZone?:string|null}):Promise<KnowledgeOverview>{const response=await requestJson<KnowledgeMutationResponse>('/api/v1/onboarding/session',{method:'PUT',headers:knowledgeHeaders(version,mutationKey('session')),body:JSON.stringify(input)});return response.overview;}
export async function uploadKnowledgeFiles(files:File[],version:number):Promise<KnowledgeOverview>{let currentVersion=version;let overview:KnowledgeOverview|undefined;for(const file of files){const response=await requestJson<KnowledgeMutationResponse>('/api/v1/knowledge/sources',{method:'POST',headers:{'if-match':`"knowledge-${currentVersion}"`,'idempotency-key':mutationKey('source-file'),'content-type':file.type||'application/octet-stream','x-lumiclaw-file-name':encodeURIComponent(file.name)},body:await file.arrayBuffer()});overview=response.overview;currentVersion=overview.session.rowVersion;}if(overview===undefined)throw new ProductApiError('SOURCE_FILE_REQUIRED',422);return overview;}
export async function addKnowledgeText(label:string,text:string,version:number):Promise<KnowledgeOverview>{const response=await requestJson<KnowledgeMutationResponse>('/api/v1/knowledge/sources/text',{method:'POST',headers:knowledgeHeaders(version,mutationKey('source-text')),body:JSON.stringify({label,text})});return response.overview;}
export async function deleteKnowledgeSource(sourceId:string,version:number):Promise<KnowledgeOverview>{const response=await requestJson<KnowledgeMutationResponse>(`/api/v1/knowledge/sources/${sourceId}`,{method:'DELETE',headers:knowledgeControlHeaders(version,mutationKey('source-delete'))});return response.overview;}
export async function confirmLegacySource(sourceId:string,version:number):Promise<KnowledgeOverview>{const response=await requestJson<KnowledgeMutationResponse>(`/api/v1/knowledge/sources/${sourceId}/confirm`,{method:'POST',headers:knowledgeControlHeaders(version,mutationKey('source-confirm'))});return response.overview;}
export async function resolveKnowledgeConflict(conflictId:string,selectedItemId:string,note:string,version:number):Promise<KnowledgeOverview>{const response=await requestJson<KnowledgeMutationResponse>('/api/v1/knowledge/snapshots/resolve-conflict',{method:'POST',headers:knowledgeHeaders(version,mutationKey('conflict')),body:JSON.stringify({conflictId,selectedItemId,note})});return response.overview;}
export async function approveKnowledgeSnapshot(snapshotId:string,canonicalDigest:string,version:number):Promise<KnowledgeOverview>{const response=await requestJson<KnowledgeMutationResponse>('/api/v1/knowledge/snapshots/approve',{method:'POST',headers:knowledgeHeaders(version,mutationKey('snapshot-approve')),body:JSON.stringify({snapshotId,canonicalDigest})});return response.overview;}
export async function loadSkill(skillId: string): Promise<{skill: {content: string; files: string[]; license: string}}> { return requestJson(`/api/v1/skills/${skillId}`); }

type GoalMutationResponse = {goal: OperatingGoalRevision};
type IntentMutationResponse = {bundle: MissionIntentBundle; plannerExecution: {status: 'NOT_RUN'; fixtureAllowedForEngineering: true; agentTeamsExecuted: false}};
type PlanMutationResponse = {plan: ContentPlanRevision; agentTeamsExecuted: boolean; evidenceMaturity: string};
type ApprovalMutationResponse = {plan: ContentPlanRevision; bundle: MissionExecutionBundle; agentTeamsExecuted: false; externalActionAllowed: false};

export async function createOperatingGoal(value: OperatingGoalInput, knowledgeVersion: number): Promise<OperatingGoalRevision> {
  const response = await requestJson<GoalMutationResponse>('/api/v1/goals', {method: 'POST', headers: knowledgeHeaders(knowledgeVersion, mutationKey('goal-create')), body: JSON.stringify(value)});
  return response.goal;
}
export async function activateOperatingGoal(goal: OperatingGoalRevision): Promise<OperatingGoalRevision> {
  const response = await requestJson<GoalMutationResponse>(`/api/v1/goals/${goal.goalId}/activate`, {method: 'POST', headers: exactHeaders(goalEtagValue(goal), mutationKey('goal-activate')), body: JSON.stringify({canonicalDigest: goal.canonicalDigest})});
  return response.goal;
}
export async function compileMissionIntent(goal: OperatingGoalRevision): Promise<MissionIntentBundle> {
  const response = await requestJson<IntentMutationResponse>('/api/v1/missions/compile', {method: 'POST', headers: exactHeaders(goalEtagValue(goal), mutationKey('mission-intent')), body: JSON.stringify({goalId: goal.goalId, goalDigest: goal.canonicalDigest})});
  return response.bundle;
}
export async function importControlledPlannerSubmission(intent: MissionIntentBundle, submission: PlannerSubmission): Promise<ContentPlanRevision> {
  const response = await requestJson<PlanMutationResponse>('/api/v1/content-plans', {method: 'POST', headers: exactHeaders(bundleEtagValue(intent), mutationKey('plan-import')), body: JSON.stringify(submission)});
  return response.plan;
}
export async function reviseContentPlan(plan: ContentPlanRevision, slots: ContentPlanSlot[], currentBrief: ContentBrief, sourceBindings: PlanSourceBinding[]): Promise<ContentPlanRevision> {
  const response = await requestJson<PlanMutationResponse>(`/api/v1/content-plans/${plan.planId}`, {method: 'PATCH', headers: exactHeaders(planEtagValue(plan), mutationKey('plan-revise')), body: JSON.stringify({canonicalDigest: plan.canonicalDigest, slots, currentBrief, sourceBindings})});
  return response.plan;
}
export async function approveContentPlan(plan: ContentPlanRevision): Promise<ApprovalMutationResponse> {
  return requestJson(`/api/v1/content-plans/${plan.planId}/approve`, {method: 'POST', headers: exactHeaders(planEtagValue(plan), mutationKey('plan-approve')), body: JSON.stringify({canonicalDigest: plan.canonicalDigest})});
}

export async function createControlledArtifact(execution: MissionExecutionBundle, activationUnitId: string, xMode: 'SINGLE'|'THREAD'): Promise<ArtifactRevisionV3> {
  const response=await requestJson<{revision:ArtifactRevisionV3}>(`/api/v1/artifacts/controlled-fixture`,{method:'POST',headers:exactHeaders(bundleEtagValue(execution),mutationKey('artifact-fixture')),body:JSON.stringify({activationUnitId,bundleId:execution.bundleId,xMode})});return response.revision;
}
export async function editArtifact(revision:ArtifactRevisionV3,payload:ArtifactPayload):Promise<ArtifactRevisionV3>{const response=await requestJson<{revision:ArtifactRevisionV3}>(`/api/v1/artifacts/${revision.id}/edit`,{method:'POST',headers:exactHeaders(artifactRevisionEtag(revision),mutationKey('artifact-edit')),body:JSON.stringify({canonicalDigest:revision.canonicalDigest,payload})});return response.revision;}
export async function requestArtifactRegeneration(revision:ArtifactRevisionV3,reason:string):Promise<void>{await requestJson(`/api/v1/artifacts/${revision.id}/regenerate`,{method:'POST',headers:exactHeaders(artifactRevisionEtag(revision),mutationKey('artifact-regenerate')),body:JSON.stringify({canonicalDigest:revision.canonicalDigest,reason})});}
export async function auditArtifact(revision:ArtifactRevisionV3,result:AuditResult,findings:AuditFinding[]=[]):Promise<ArtifactAuditDecision>{const response=await requestJson<{audit:ArtifactAuditDecision}>(`/api/v1/artifacts/${revision.id}/audits`,{method:'POST',headers:exactHeaders(artifactRevisionEtag(revision),mutationKey('artifact-audit')),body:JSON.stringify({canonicalDigest:revision.canonicalDigest,controlledFixture:true,result,findings})});return response.audit;}
export async function decideArtifact(revision:ArtifactRevisionV3,audit:ArtifactAuditDecision,result:OwnerArtifactDecisionResult,reason:string|null):Promise<ArtifactOwnerDecision>{const response=await requestJson<{decision:ArtifactOwnerDecision}>(`/api/v1/artifacts/${revision.id}/owner-decisions`,{method:'POST',headers:exactHeaders(artifactRevisionEtag(revision),mutationKey('artifact-owner')),body:JSON.stringify({canonicalDigest:revision.canonicalDigest,auditDecisionId:audit.id,auditDecisionDigest:audit.canonicalDigest,result,reason})});return response.decision;}
export async function createManualPublishPackage(revision:ArtifactRevisionV3,audit:ArtifactAuditDecision,decision:ArtifactOwnerDecision):Promise<ManualPublishPackage>{const response=await requestJson<{package:ManualPublishPackage}>('/api/v1/manual-publish-packages',{method:'POST',headers:exactHeaders(ownerDecisionEtag(decision),mutationKey('manual-package')),body:JSON.stringify({artifactRevisionId:revision.id,artifactRevisionDigest:revision.canonicalDigest,auditDecisionId:audit.id,auditDecisionDigest:audit.canonicalDigest,ownerDecisionId:decision.id,ownerDecisionDigest:decision.canonicalDigest})});return response.package;}
export function recordPackageEvent(pack:ManualPublishPackage,kind:'copy-event'|'download-event'|'open-official'):{promise:Promise<{officialUrl:string|null;published:false}>,downloadUrl:string}{const promise=requestJson<{officialUrl:string|null;published:false}>(`/api/v1/manual-publish-packages/${pack.id}/${kind}`,{method:'POST',headers:exactHeaders(packageEtag(pack),mutationKey(`package-${kind}`)),body:'{}'});return {promise,downloadUrl:`/api/v1/manual-publish-packages/${pack.id}/download`};}
export async function loadGovernedMedia():Promise<{workspace:MediaWorkspace}>{return requestJson('/api/v1/media');}
export async function loadMediaReadiness():Promise<{state:string;configured:boolean;fingerprint:string|null;updatedAt:string|null;profileMaturity:string;profileRef:string;checkedAt:string;expiresAt:string;purpose:'MEDIA_PROVIDER';controlledFake:{available:true;maturity:string;providerEvidence:false};browserSecretInputAllowed:false;modelProviderGateIndependent:true}>{return requestJson('/api/v1/media/readiness');}
export async function startMediaGeneration(revision:ArtifactRevisionV3,mode:'CONTROLLED_FAKE'|'REAL_PROVIDER'):Promise<{jobs:MediaGenerationJob[]}>{if(revision.payload.kind!=='XIAOHONGSHU')throw new ProductApiError('MEDIA_JOB_STATE_INVALID',422);const imageSpecs=revision.payload.imageSpecs.map((spec)=>({promptText:`无关键中文标题文字、无徽标、无水印的背景插画。视觉要求：${spec.visualBrief}`,altText:spec.altDescription??spec.purpose,overlayCopy:spec.overlayCopy}));return requestJson(`/api/v1/artifacts/${revision.id}/media-generations`,{method:'POST',headers:exactHeaders(artifactRevisionEtag(revision),mutationKey(`media-${mode.toLowerCase()}`)),body:JSON.stringify({artifactRevisionDigest:revision.canonicalDigest,generation:1,mode,imageSpecs})});}
export async function bindFinalMedia(revision:ArtifactRevisionV3,workspace:MediaWorkspace):Promise<ArtifactRevisionV4>{const jobs=latestMediaJobs(workspace.jobs.filter((value)=>value.artifactRevisionDigest===revision.canonicalDigest));const finals=jobs.map((job)=>{const raw=workspace.rawAssets.find((value)=>value.jobId===job.id);return workspace.finalAssets.find((value)=>value.rawAssetId===raw?.id);});if(finals.some((value)=>value===undefined))throw new ProductApiError('MEDIA_SET_INCOMPLETE',422);const first=finals[0]!;const response=await requestJson<{revision:ArtifactRevisionV4}>(`/api/v1/artifacts/${revision.id}/media-bindings`,{method:'POST',headers:exactHeaders(artifactRevisionEtag(revision),mutationKey('media-bind')),body:JSON.stringify({artifactRevisionDigest:revision.canonicalDigest,finalAssetIds:finals.map((value)=>value!.id),brandSnapshot:first.compositionSpec.brandSnapshot,knowledgeSnapshot:first.compositionSpec.knowledgeSnapshot})});return response.revision;}
export async function auditFinalMedia(revision:ArtifactRevisionV4,result:'PASS'|'FAIL'|'ESCALATE'):Promise<MediaAuditDecisionV4>{const response=await requestJson<{audit:MediaAuditDecisionV4}>(`/api/v1/media-revisions/${revision.id}/audits`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({revisionDigest:revision.canonicalDigest,auditorIdentityId:'independent-media-auditor',result})});return response.audit;}
export async function decideFinalMedia(revision:ArtifactRevisionV4,audit:MediaAuditDecisionV4,result:'APPROVE'|'REJECT'):Promise<MediaOwnerDecisionV4>{const response=await requestJson<{decision:MediaOwnerDecisionV4}>(`/api/v1/media-revisions/${revision.id}/owner-decisions`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({revisionDigest:revision.canonicalDigest,auditDecisionId:audit.id,auditDecisionDigest:audit.canonicalDigest,result})});return response.decision;}
export async function packageFinalMedia(revision:ArtifactRevisionV4,audit:MediaAuditDecisionV4,decision:MediaOwnerDecisionV4):Promise<ManualPublishPackageV4>{const response=await requestJson<{package:ManualPublishPackageV4}>('/api/v1/media-publish-packages',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({revisionId:revision.id,revisionDigest:revision.canonicalDigest,auditDecisionId:audit.id,auditDecisionDigest:audit.canonicalDigest,ownerDecisionId:decision.id,ownerDecisionDigest:decision.canonicalDigest})});return response.package;}

function latestMediaJobs(jobs:MediaGenerationJob[]):MediaGenerationJob[]{const byPosition=new Map<number,MediaGenerationJob>();for(const job of jobs){const current=byPosition.get(job.imageSpecPosition);if(current===undefined||job.generation>current.generation||job.generation===current.generation&&job.createdAt>current.createdAt)byPosition.set(job.imageSpecPosition,job);}return [...byPosition.values()].sort((a,b)=>a.imageSpecPosition-b.imageSpecPosition);}

function exactHeaders(etag: string, key: string): HeadersInit { return {'content-type': 'application/json', 'if-match': etag, 'idempotency-key': key}; }
function goalEtagValue(goal: OperatingGoalRevision): string { return `"goal-${goal.goalId}-r${goal.revision}-${goal.canonicalDigest}"`; }
function planEtagValue(plan: ContentPlanRevision): string { return `"plan-${plan.planId}-r${plan.revision}-${plan.canonicalDigest}"`; }
function bundleEtagValue(bundle: MissionIntentBundle|MissionExecutionBundle): string { return `"bundle-${bundle.bundleId}-g${bundle.generation}-${bundle.canonicalDigest}"`; }
function artifactRevisionEtag(value: ArtifactRevisionV3): string { return `"artifact-${value.id}-r${value.revision}-${value.canonicalDigest}"`; }
function ownerDecisionEtag(value: ArtifactOwnerDecision): string { return `"owner-decision-${value.id}-${value.canonicalDigest}"`; }
function packageEtag(value: ManualPublishPackage): string { return `"package-${value.id}-${value.manifestDigest}"`; }
async function requestJson<T>(url: string, init?: RequestInit): Promise<T> {
  const response = await fetch(url, {...init, cache: 'no-store'});
  const payload = await response.json() as {code?: string};
  if (!response.ok) throw new ProductApiError(payload.code ?? 'CONTROL_PLANE_UNAVAILABLE', response.status);
  return payload as T;
}
